#include "Globales.h"
//ENTREGAR
class CBase{
protected:
	string** Vectores = new string*[a];
	string Ciudades[a];
	///////////////////////////////////
	string VLima[a];
	string VSantiago[a];
	string VQuito[a];
	string VGuayaquil[a];
	string VLaPaz[a];
	string VBuenosAires[a];
	string VIquique[a];
	string VCordoba[a];
	string VSantaCruz[a];
	string VPortoAlegre[a];
	string VAsuncion[a];
	string VIguazu[a];
	string VSaoPaulo[a];
	string VBrasilia[a];

	string VMendoza[a];
	string VMontevideo[a];
	string VRosario[a];
	string VFlorianopolis[a];
	string VCiudadDelEste[a];
	string VCuritiba[a];
	string VRioDeJaneiro[a];
	string VBeloHorizonte[a];
	string VPortoSeguro[a];
	string VSalvador[a];
	string VRecife[a];
	string VFortaleza[a];
	string VBelem[a];
	string VManaos[a];
	string VLeticia[a];
	string VCali[a];
	string VBogota[a];
	string VMedellin[a];
	string VPanama[a];
	string VCartagena[a];
	string VAruba[a];
	string VCarajas[a];
	string VVillaHermosa[a];
	string VSanJuan[a];
	string VPuntaCana[a];
	string VAcapulco[a];
	string VCiudadDeMexico[a];
	string VVeracruz[a];
	string VMerida[a];
	string VCancun[a];
	string VLaHabana[a];
	
	string VPuertoVallarta[a];
	string VGuadalajara[a];
	string VLeon[a];
	string VMazatlan[a];
	string VSanJoseCabo[a];
	string VTorreon[a];
	string VMonterrey[a];
	string VMiami[a];
	string VHermosillo[a];
	string VHouston[a];
	string VNewOrleans[a];
	string VTampa[a];
	string VOrlando[a];
	string VTijuana[a];
	string VPhoenix[a];
	string VDallas[a];
	string VAtlanta[a];
	string VSanDiego[a];
	string VLosAngeles[a];
	string VLasVegas[a];
	string VCharlotte[a];
	string VRaleigh[a];
	string VWashington[a];
	string VBaltimore[a];
	string VSanJose[a];
	string VSanFrancisco[a];
	string VReno[a];
	string VDenver[a];
	string VSaltLakeCity[a];
	string VPortland[a];
	string VSeattle[a];
	string VVancouver[a];
	string VCalgary[a];
	string VPhiladelphia[a];
	string VSaintLouis[a];
	string VNewYork[a];
	string VChicago[a];
	string VDetroit[a];
	string VMinneapolis[a];
	string VToronto[a];
	string VBoston[a];
	string VMontreal[a];

	string VPucallpa[a];
	string VAyacucho[a];
	string VCusco[a];
	string VPuertoMaldonado[a];
	string VJuliaca[a];
	string VArequipa[a];
	string VTacna[a];
	string VTarapoto[a];
	string VCajamarca[a];
	string VTrujillo[a];
	string VChiclayo[a];
	string VIquitos[a];
	string VPiura[a];
	string VTalara[a];
	string VTumbes[a];

public:
	CBase(){
		//Inicializamos nuestros strings con espacio, para evitar posibles errores(null)
		IniciarString(VLima);
		IniciarString(VSantiago);
		IniciarString(VQuito);
		IniciarString(VGuayaquil);
		IniciarString(VLaPaz);
		IniciarString(VBuenosAires);
		IniciarString(VIquique);
		IniciarString(VCordoba);
		IniciarString(VSantaCruz);
		IniciarString(VPortoAlegre);
		IniciarString(VAsuncion);
		IniciarString(VIguazu);
		IniciarString(VSaoPaulo);
		IniciarString(VBrasilia);
		IniciarString(VMendoza);
		IniciarString(VMontevideo);
		IniciarString(VRosario);
		IniciarString(VFlorianopolis);
		IniciarString(VCiudadDelEste);
		IniciarString(VCuritiba);
		IniciarString(VRioDeJaneiro);
		IniciarString(VBeloHorizonte);
		IniciarString(VPortoSeguro);
		IniciarString(VSalvador);
		IniciarString(VRecife);
		IniciarString(VFortaleza);
		IniciarString(VBelem);
		IniciarString(VManaos);
		IniciarString(VLeticia);
		IniciarString(VCali);
		IniciarString(VBogota);
		IniciarString(VMedellin);
		IniciarString(VPanama);
		IniciarString(VCartagena);
		IniciarString(VAruba);
		IniciarString(VCarajas);
		IniciarString(VVillaHermosa);
		IniciarString(VSanJuan);
		IniciarString(VPuntaCana);
		IniciarString(VAcapulco);
		IniciarString(VCiudadDeMexico);
		IniciarString(VVeracruz);
		IniciarString(VMerida);
		IniciarString(VCancun);
		IniciarString(VLaHabana);
		IniciarString(VPuertoVallarta);
		IniciarString(VGuadalajara);
		IniciarString(VLeon);
		IniciarString(VMazatlan);
		IniciarString(VSanJoseCabo);
		IniciarString(VTorreon);
		IniciarString(VMonterrey);
		IniciarString(VMiami);
		IniciarString(VHermosillo);
		IniciarString(VHouston);
		IniciarString(VNewOrleans);
		IniciarString(VTampa);
		IniciarString(VOrlando);
		IniciarString(VTijuana);
		IniciarString(VPhoenix);
		IniciarString(VDallas);
		IniciarString(VAtlanta);
		IniciarString(VSanDiego);
		IniciarString(VLosAngeles);
		IniciarString(VLasVegas);
		IniciarString(VCharlotte);
		IniciarString(VRaleigh);
		IniciarString(VWashington);
		IniciarString(VBaltimore);
		IniciarString(VSanJose);
		IniciarString(VSanFrancisco);
		IniciarString(VReno);
		IniciarString(VDenver);
		IniciarString(VSaltLakeCity);
		IniciarString(VPortland);
		IniciarString(VSeattle);
		IniciarString(VVancouver);
		IniciarString(VCalgary);
		IniciarString(VPhiladelphia);
		IniciarString(VSaintLouis);
		IniciarString(VNewYork);
		IniciarString(VChicago);
		IniciarString(VDetroit);
		IniciarString(VMinneapolis);
		IniciarString(VToronto);
		IniciarString(VBoston);
		IniciarString(VMontreal);
		IniciarPeru(VPucallpa);
		IniciarPeru(VAyacucho);
		IniciarPeru(VCusco);
		IniciarPeru(VPuertoMaldonado);
		IniciarPeru(VJuliaca);
		IniciarPeru(VArequipa);
		IniciarPeru(VTacna);
		IniciarPeru(VTarapoto);
		IniciarPeru(VCajamarca);
		IniciarPeru(VTrujillo);
		IniciarPeru(VChiclayo);
		IniciarPeru(VIquitos);
		IniciarPeru(VPiura);
		IniciarPeru(VTalara);
		IniciarPeru(VTumbes);
	

		//Rellenamos el nombre de todas las ciduades: (No es necesario, usar globales)
		Ciudades[0] = "Lima,Peru";
		Ciudades[1] = "Santiago,Chile";
		Ciudades[2] = "Quito,Ecuador";
		Ciudades[3] = "Guayaquil,Ecuador";
		Ciudades[4] = "La Paz,Bolivia";
		Ciudades[5] = "Buenos Aires,Argentina";
		Ciudades[6] = "Iquique,Chile";
		Ciudades[7] = "Cordoba,Argentina";
		Ciudades[8] = "Santa Cruz,Bolivia";
		Ciudades[9] = "Porto Alegre,Brasil";
		Ciudades[10] = "Asuncion,Paraguay";
		Ciudades[11] = "Iguazu,Argentina";
		Ciudades[12] = "Sao Paulo,Brasil";
		Ciudades[13] = "Brasilia,Brasil";
		Ciudades[14] = "Mendoza,Argentina";
		Ciudades[15] = "Montevideo,Uruguay";
		Ciudades[16] = "Rosario,Argentina";
		Ciudades[17] = "Florianopolis,Brasil";
		Ciudades[18] = "Ciudad del Este,Paraguay";
		Ciudades[19] = "Curitiba,Brasil";
		Ciudades[20] = "Rio de Janeiro,Brasil";
		Ciudades[21] = "Belo Horizonte,Brasil";
		Ciudades[22] = "Porto Seguro,Brasil";
		Ciudades[23] = "Salvador,Brasil";
		Ciudades[24] = "Recife,Brasil";
		Ciudades[25] = "Fortaleza,Brasil";
		Ciudades[26] = "Belem,Brasil";
		Ciudades[27] = "Manaos,Brasil";
		Ciudades[28] = "Leticia,Colombia";
		Ciudades[29] = "Cali,Colombia";
		Ciudades[30] = "Bogota,Colombia";
		Ciudades[31] = "Medellin,Colombia";
		Ciudades[32] = "Panama,Panama";
		Ciudades[33] = "Cartagena,Colombia";
		Ciudades[34] = "Aruba,Paises Bajos";
		Ciudades[35] = "Carajas,Brasil";
		Ciudades[36] = "Villa Hermosa,Mexico";
		Ciudades[37] = "San Juan,Puerto Rico";
		Ciudades[38] = "Punta Cana,Republica Dominicana";
		Ciudades[39] = "Acapulco,Mexico";
		Ciudades[40] = "Ciudad de Mexico,Mexico";
		Ciudades[41] = "Veracruz,Mexico";
		Ciudades[42] = "Merida,Mexico";
		Ciudades[43] = "Cancun,Mexico";
		Ciudades[44] = "La Habana,Cuba";
		Ciudades[45] = "Puerto Vallarta,Mexico";
		Ciudades[46] = "Guadalajara,Mexico";
		Ciudades[47] = "Leon,Mexico";
		Ciudades[48] = "Mazatlan,Mexico";
		Ciudades[49] = "San Jose Cabo,Mexico";
		Ciudades[50] = "Torreon,Mexico";
		Ciudades[51] = "Monterrey,Mexico";
		Ciudades[52] = "Miami,E.E.U.U";
		Ciudades[53] = "Hermosillo,Mexico";
		Ciudades[54] = "Houston,E.E.U.U";
		Ciudades[55] = "New Orleans,E.E.U.U";
		Ciudades[56] = "Tampa,E.E.U.U";
		Ciudades[57] = "Orlando,E.E.U.U";
		Ciudades[58] = "Tijuana,E.E.U.U";
		Ciudades[59] = "Phoenix,E.E.U.U";
		Ciudades[60] = "Dallas,E.E.U.U";
		Ciudades[61] = "Atlanta,E.E.U.U";
		Ciudades[62] = "San Diego,E.E.U.U";
		Ciudades[63] = "Los Angeles,E.E.U.U";
		Ciudades[64] = "Las Vegas,E.E.U.U";
		Ciudades[65] = "Charlotte,E.E.U.U";
		Ciudades[66] = "Raleigh,E.E.U.U";
		Ciudades[67] = "Washington,E.E.U.U";
		Ciudades[68] = "Baltimore,E.E.U.U";
		Ciudades[69] = "San Jose,E.E.U.U";
		Ciudades[70] = "San Francisco,E.E.U.U";
		Ciudades[71] = "Reno,E.E.U.U";
		Ciudades[72] = "Denver,E.E.U.U";
		Ciudades[73] = "Sal Lake City,E.E.U.U";
		Ciudades[74] = "Portland,E.E.U.U";
		Ciudades[75] = "Seattle,E.E.U.U";
		Ciudades[76] = "Vancouver,E.E.U.U";
		Ciudades[77] = "Calgary,E.E.U.U";
		Ciudades[78] = "Philadelphia,E.E.U.U";
		Ciudades[79] = "Saint Louis,E.E.U.U";
		Ciudades[80] = "New York,E.E.U.U";
		Ciudades[81] = "Chicago,E.E.U.U";
		Ciudades[82] = "Detroit,E.E.U.U";
		Ciudades[83] = "Minneapolis,E.E.U.U";
		Ciudades[84] = "Toronto,Canada";
		Ciudades[85] = "Boston,E.E.U.U";
		Ciudades[86] = "Montreal,Canada";

		Ciudades[87] = "Pucallpa,Peru";
		Ciudades[88] = "Ayacucho,Peru";
		Ciudades[89] = "Cusco,Peru";
		Ciudades[90] = "Puerto Maldonado,Peru";
		Ciudades[91] = "Juliaca,Peru";
		Ciudades[92] = "Arequipa,Peru";
		Ciudades[93] = "Tacna,Peru";
		Ciudades[94] = "Tarapoto,Peru";
		Ciudades[95] = "Cajamarca,Peru";
		Ciudades[96] = "Trujillo,Peru";
		Ciudades[97] = "Chiclayo,Peru";
		Ciudades[98] = "Iquitos,Peru";
		Ciudades[99] = "Piura,Peru";
		Ciudades[100] = "Talara,Peru";
		Ciudades[101] = "Tumbes,Peru";
	
		//BASE DE DATOS:
		//Lima:
		VLima[Santiago] = "Buenos Aires,null";
		VLima[Quito] = "Guayaquil,null";
		VLima[Guayaquil] = "Quito,null";
		VLima[LaPaz] = "Santiago,null";
		VLima[BuenosAires] = "Santiago,null";
		VLima[Iquique] = "Santiago,Sao Paulo-Santiago";
		VLima[Cordoba] = "Buenos Aires, Santiago-Buenos Aires";
		VLima[SantaCruz] = "Santiago,Santiago-Iquique";
		VLima[PortoAlegre] = "Sao Paulo,Santiago-Sao Paulo";
		VLima[Asuncion] = "Buenos Aires,Sao Paulo-Rio de Janeiro";
		VLima[Iguazu] = "Buenos Aires,Santiago-Buenos Aires";
		VLima[SaoPaulo] = "Santiago,Cordoba-Santiago";
		VLima[Brasilia] = "Sao Paulo,Santiago-Sao Paulo";
		VLima[Mendoza] = "Santiago, Santiago-Buenos Aires";
		VLima[Montevideo] = "Santiago, Santiago-Sao Paulo";
		VLima[Rosario] = "Sao Paulo, Bogota-Sao Paulo";
		VLima[Florianopolis] = "Sao Paulo, Santiago-Sao Paulo";
		VLima[Curitiba] = "Sao Paulo, Santiago-Sao Paulo";
		VLima[RioDeJaneiro] = "Sao Paulo, Santiago-Sao Paulo";
		VLima[BeloHorizonte] = "Sao Paulo, Santiago-Sao Paulo";
		VLima[Salvador] = "Sao Paulo, Santiago-Sao Paulo";
		VLima[Recife] = "Sao Paulo, Santiago-Sao Paulo";
		VLima[Fortaleza] = "Sao Paulo, Santiago-Sao Paulo";
		VLima[Belem] = "Sao Paulo, Santiago-Sao Paulo";
		VLima[Manaos] = "Sao Paulo, Santiago-Sao Paulo";
		VLima[Cali] = "Bogota, Santiago-Bogota";
		VLima[Bogota] = "Santiago, Santiago-Sao Paulo";
		VLima[Medellin] = "Bogota, Sao Paulo-Bogota";
		VLima[Cartagena] = "Bogota, Santiago-Bogota";
		VLima[Aruba] = "null, Santiago-Bogota";
		VLima[VillaHermosa] = "Ciudad de Mexico,Santiago-Ciudad de Mexico";
		VLima[PuntaCana] = "null,Sao Paulo-Brasilia";
		VLima[Acapulco] = "Ciudad de Mexico, null";
		VLima[CiudadDeMexico] = "Sao Paulo, Sao Paulo-Santiago";
		VLima[Veracruz] = "Ciudad de Mexico, null";
		VLima[Merida] = "Ciudad de Mexico, Santiago-Ciudad de Mexico";
		VLima[Cancun] = "Ciudad de Mexico, Santiago-Sao Paulo";

		VLima[PuertoVallarta] = "null, Santiago-Ciudad de Mexico";
		VLima[Guadalajara] = "Ciudad de Mexico, null";
		VLima[Leon] = "Ciudad de Mexico, null";
		VLima[SanJoseCabo] = "null, Sao Paulo-Ciudad de Mexico";
		VLima[Torreon] = "Ciudad de Mexico, null";
		VLima[Monterrey] = "Ciudad de Mexico, Sao Paulo-Ciudad de Mexico";
		VLima[Miami] = "Quito, Guayaquil-Quito";
		VLima[Hermosillo] = "null, Sao Paulo-Ciudad de Mexico";
		VLima[Houston] = "Miami, Quito-Miami";
		VLima[NewOrleans] = "Miami, Quito-Miami";
		VLima[Tampa] = "Miami, Quito-Miami";
		VLima[Orlando] = "Miami, Bogota-Miami";
		VLima[Tijuana] = "null, Sao Paulo-Ciudad de Mexico";
		VLima[Phoenix] = "Los Angeles, Quito-Miami";
		VLima[Dallas] = "Miami, Quito-Miami";
		VLima[Atlanta] = "Miami, Quito-Miami";
		VLima[SanDiego] = "Los Angeles, Miami-Los Angeles";
		VLima[LosAngeles] = "Miami, Orlando-Miami";
		VLima[LasVegas] = "Los Angeles, Quito-Miami";
		VLima[Charlotte] = "Miami, Quito-Miami";
		VLima[Raleigh] = "Miami, Quito-Miami";
		VLima[Washington] = "Miami, Orlando-Miami";
		VLima[Baltimore] = "Miami, Santiago-Miami";
		VLima[SanJose] = "Los Angeles, Miami-Los Angeles";
		VLima[SanFrancisco] = "Los Angeles, Quito-Miami";
		VLima[Reno] = "Los Angeles, Miami-Los Angeles";
		VLima[Denver] = "Los Angeles, Quito-Miami";
		VLima[SaltLakeCity] = "Los Angeles, Miami-Los Angeles";
		VLima[Portland] = "Los Angeles, Miami-Los Angeles";
		VLima[Seattle] = "Los Angeles, Orlando-Miami";
		VLima[Vancouver] = "Los Angeles, null";
		VLima[Calgary] = "Cancun, Miami-Chicago";
		VLima[Philadelphia] = "Miami, Bogota-Miami";
		VLima[SaintLouis] = "Miami, Bogota-Miami";
		VLima[NewYork] = "Sao Paulo, Bogota-Miami";
		VLima[Chicago] = "Miami, Bogota-Miami";
		VLima[Detroit] = "Miami, Bogota-Miami";
		VLima[Minneapolis] = "Los Angeles, Bogota-Miami";
		VLima[Toronto] = "New York, New York-Miami";
		VLima[Boston] = "Miami, Bogota-Miami";
		VLima[Montreal] = "New York, New York-Miami";

		//Santiago:
		VSantiago[Lima] = "Buenos Aires,null";
		VSantiago[Quito] = "Lima,Lima-Guayaquil";
		VSantiago[Guayaquil] = "Lima,Lima-Quito";
		VSantiago[LaPaz] = "Ciudad de Mexico,Ciudad de Mexico-Sao Paulo";
		VSantiago[BuenosAires] = "Sao Paulo,null";
		VSantiago[Cordoba] = "Buenos Aires,null";
		VSantiago[SantaCruz] = "Iquique,Buenos Aires-Lima";
		VSantiago[PortoAlegre] = "Sao Paulo,Rio de Janeiro-Sao Paulo";
		VSantiago[Asuncion] = "Sao Paulo,Rio de Janeiro-Sao Paulo";
		VSantiago[Iguazu] = "Buenos Aires,Asuncion-Buenos Aires";
		VSantiago[SaoPaulo] = "Asuncion,Asuncion-Rio de Janeiro";
		VSantiago[Brasilia] = "Sao Paulo,Sao Paulo-Curitiba";
		VSantiago[Mendoza] = "Buenos Aires, null";
		VSantiago[Montevideo] = "Sao Paulo, Asuncion-Sao Paulo";
		VSantiago[Rosario] = "Lima, Sao Paulo-Lima";
		VSantiago[Florianopolis] = "Sao Paulo, Rio de Janeiro-Sao Paulo";
		VSantiago[Curitiba] = "Sao Paulo, Asuncion-Sao Paulo";
		VSantiago[RioDeJaneiro] = "Sao Paulo, Asuncion-Sao Paulo";
		VSantiago[BeloHorizonte] = "Sao Paulo, Rio de Janeiro-Sao Paulo";
		VSantiago[PortoSeguro] = "Sao Paulo, Buenos Aires-Sao Paulo";
		VSantiago[Salvador] = "Sao Paulo, Rio de Janeiro-Sao Paulo";
		VSantiago[Recife] = "Sao Paulo, Rio de Janeiro-Sao Paulo";
		VSantiago[Fortaleza] = "Sao Paulo, Asuncion-Sao Paulo";
		VSantiago[Belem] = "Sao Paulo, Buenos Aires-Sao Paulo";
		VSantiago[Manaos] = "Sao Paulo, Asuncion-Sao Paulo";
		VSantiago[Leticia] = "Bogota, Lima-Bogota";
		VSantiago[Cali] = "Bogota, Lima-Bogota";
		VSantiago[Bogota] = "Lima, La Paz-Lima";
		VSantiago[Medellin] = "Bogota, Lima-Bogota";
		VSantiago[Cartagena] = "Bogota, Lima-Bogota";
		VSantiago[Aruba] = "null, Lima-Bogota";
		VSantiago[VillaHermosa] = "Ciudad de Mexico, Lima-Ciudad de Mexico";
		VSantiago[PuntaCana] = "Lima, La Paz-Lima";
		VSantiago[Acapulco] = "Ciudad de Mexico, Lima-Ciudad de Mexico";
		VSantiago[CiudadDeMexico] = "Lima., Buenos Aires-Lima";
		VSantiago[Veracruz] = "null, Lima-Ciudad de Mexico";
		VSantiago[Merida] = "Ciudad de Mexico, Lima-Ciudad de Mexico";
		VSantiago[Cancun] = "Lima, La Paz-Lima";
		VSantiago[LaHabana] = "Lima, Buenos Aires-Lima";

		VSantiago[PuertoVallarta] = "Ciudad de Mexico, null";
		VSantiago[Guadalajara] = "Ciudad de Mexico, Lima-Ciudad de Mexico";
		VSantiago[Leon] = "null, Lima-Ciudad de Mexico";
		VSantiago[SanJoseCabo] = "Ciudad de Mexico, null";
		VSantiago[Torreon] = "Ciudad de Mexico, Lima-Ciudad de Mexico";
		VSantiago[Monterrey] = "Ciudad de Mexico, Lima-Ciudad de Mexico";
		VSantiago[Miami] = "Lima, null";
		VSantiago[Hermosillo] = "Ciudad de Mexico, Sao Paulo-Ciudad de Mexico";
		VSantiago[Houston] = "Miami, Lima-Miami";
		VSantiago[NewOrleans] = "Miami, Bogota-Miami";
		VSantiago[Tampa] = "Miami, Bogota-Miami";
		VSantiago[Orlando] = "Lima, Rio de Janeiro-Sao Paulo";
		VSantiago[Tijuana] = "Ciudad de Mexico, Sao Paulo-Ciudad de Mexico";
		VSantiago[Phoenix] = "Los Angeles, Lima-Los Angeles";
		VSantiago[Dallas] = "Miami, Lima-Miami";
		VSantiago[Atlanta] = "Miami, Lima-Miami";
		VSantiago[SanDiego] = "Los Angeles, Lima-Los Angeles";
		VSantiago[LosAngeles] = "Lima, Lima-Miami";
		VSantiago[LasVegas] = "Los Angeles, Lima-Los Angeles";
		VSantiago[Charlotte] = "Miami, Lima-Miami";
		VSantiago[Raleigh] = "Miami, Lima-Miami";
		VSantiago[Washington] = "Miami, Lima-Miami";
		VSantiago[Baltimore] = "Miami, Lima-Miami";
		VSantiago[SanFrancisco] = "Los Angeles, Bogota-Miami";
		VSantiago[Reno] = "Los Angeles, Lima-Los Angeles";
		VSantiago[Denver] = "Los Angeles, Bogota-Miami";
		VSantiago[SaltLakeCity] = "Los Angeles, Lima-Los Angeles";
		VSantiago[Portland] = "Los Angeles, Lima-Los Angeles";
		VSantiago[Seattle] = "Los Angeles, Bogota-Miami";
		VSantiago[Vancouver] = "Los Angeles, Lima-Los Angeles";
		VSantiago[Calgary] = "Los Angeles, Lima-Cancun";
		VSantiago[Philadelphia] = "Miami, Lima-Miami";
		VSantiago[SaintLouis] = "Los Angeles, Bogota-Miami";
		VSantiago[NewYork] = "Lima, Sao Paulo-Rio de Janeiro";
		VSantiago[Chicago] = "Miami, Lima-Miami";
		VSantiago[Detroit] = "null, Bogota-Miami";
		VSantiago[Toronto] = "New York, Lima-New York";
		VSantiago[Boston] = "New York, Bogota-Miami";
		VSantiago[Montreal] = "New York, Lima-New York";
		VSantiago[Pucallpa] = "Lima,null";
		VSantiago[Pucallpa] = "null,Lima-Santiago";
		VSantiago[Ayacucho] = "null,Lima-Santiago";
		VSantiago[Cusco] = "null,Lima-Santiago";
		VSantiago[PuertoMaldonado] = "null,Lima-Santiago";
		VSantiago[Juliaca] = "null,Lima-Santiago";
		VSantiago[Arequipa] = "null,Lima-Santiago";
		VSantiago[Tacna] = "null,Lima-Santiago";
		VSantiago[Tarapoto] = "null,Lima-Santiago";
		VSantiago[Cajamarca] = "null,Lima-Santiago";
		VSantiago[Trujillo] = "null,Lima-Santiago";
		VSantiago[Chiclayo] = "null,Lima-Santiago";
		VSantiago[Iquitos] = "null,Lima-Santiago";
		VSantiago[Piura] = "null,Lima-Santiago";
		VSantiago[Talara] = "null,Lima-Santiago";
		VSantiago[Tumbes] = "null,Lima-Santiago";

		//Quito:
		VQuito[Lima] = "Guayaquil,Guayaquil-Santiago";
		VQuito[Santiago] = "Guayaquil,Lima-La Paz";
		VQuito[LaPaz] = "Lima,Lima-Santiago";
		VQuito[BuenosAires] = "Lima,Lima-Santiago";
		VQuito[Cordoba] = "Lima,null";
		VQuito[SantaCruz] = "Lima,Miami-Lima";
		VQuito[PortoAlegre] = "null,Lima-Sao Paulo";
		VQuito[Asuncion] = "null,Lima-Sao Paulo";
		VQuito[Iguazu] = "null,Lima-Buenos Aires";
		VQuito[SaoPaulo] = "Lima,Guayaquil-Lima";
		VQuito[Brasilia] = "null,Buenos Aires-Sao Paulo";
		VQuito[Mendoza] = "Buenos Aires, Lima-Santiago";
		VQuito[Montevideo] = "Lima, Lima-Santiago";
		VQuito[Rosario] = "Lima, Miami-Lima";
		VQuito[Florianopolis] = "null, Lima-Sao Paulo";
		VQuito[Curitiba] = "null, Lima-Sao Paulo";
		VQuito[RioDeJaneiro] = "Guayaquil, Santiago de Chile";
		VQuito[BeloHorizonte] = "null, Lima-Sao Paulo";
		VQuito[Salvador] = "null, Lima-Sao Paulo";
		VQuito[Recife] = "null, Lima-Sao Paulo";
		VQuito[Fortaleza] = "null, Lima-Sao Paulo";
		VQuito[Manaos] = "null, Lima-Sao Paulo";
		VQuito[Cali] = "null, Lima-Bogota";
		VQuito[Bogota] = "Lima, Guayaquil-Lima";
		VQuito[Medellin] = "Miami, Lima-Bogota";
		VQuito[Cartagena] = "null, Lima-Bogota";
		VQuito[Aruba] = "null, Lima-Bogota";
		VQuito[VillaHermosa] = "null,Lima-Ciudad de Mexico";
		VQuito[PuntaCana] = "Lima, Guayaquil-Lima";
		VQuito[Acapulco] = "null, Lima-Ciudad de Mexico";
		VQuito[CiudadDeMexico] = "Lima, Guayaquil-Santiago";
		VQuito[Veracruz] = "null, Lima-Ciudad de Mexico";
		VQuito[Merida] = "null, Lima-Ciudad de Mexico";
		VQuito[Cancun] = "Lima, Guayaquil-Lima";
		VQuito[LaHabana] = "Lima, Guayaquil-Lima";

		VQuito[Guadalajara] = "null, Lima-Ciudad de Mexico";
		VQuito[Leon] = "null, Lima-Ciudad de Mexico";
		VQuito[Torreon] = "null, Lima-Ciudad de Mexico";
		VQuito[Monterrey] = "null, Lima-Ciudad de Mexico";
		VQuito[Miami] = "Lima, Guayaquil-Lima";
		VQuito[Houston] = "Miami, Lima-Los Angeles";
		VQuito[Tampa] = "Miami, Miami-Charlotte";
		VQuito[Orlando] = "Lima, Guayaquil-Santiago";
		VQuito[Dallas] = "Miami, Lima-Los Angeles";
		VQuito[Atlanta] = "Miami, Guayaquil-New York";
		VQuito[SanDiego] = "Miami, Lima-Los Angeles";
		VQuito[LosAngeles] = "Lima, Guayaquil-Lima";
		VQuito[LasVegas] = "Miami, Lima-Los Angeles";
		VQuito[Charlotte] = "Miami, Guayaquil-Miami";
		VQuito[Raleigh] = "Miami, Guayaquil-New York";
		VQuito[Washington] = "Miami, Guayaquil-New York";
		VQuito[Baltimore] = "Miami, Guayaquil-New York";
		VQuito[SanFrancisco] = "Miami, Lima-Los Angeles";
		VQuito[Reno] = "null, Lima-Los Angeles";
		VQuito[Vancouver] = "null, Guayaquil-New York";
		VQuito[Calgary] = "null, Guayaquil-New York";
		VQuito[Philadelphia] = "Miami, null";
		VQuito[NewYork] = "Guayaquil, Lima-Miami";
		VQuito[Chicago] = "Miami, Guayaquil-New York";
		VQuito[Minneapolis] = "Miami, Lima-Los Angeles";
		VQuito[Toronto] = "Miami, Lima-New York";
		VQuito[Boston] = "Miami, Miami-New York";
		VQuito[Montreal] = "Miami, Lima-New York";
		VQuito[Pucallpa] = "Lima,null";
		VQuito[Pucallpa] = "Lima,null";
		VQuito[Ayacucho] = "Lima,null";
		VQuito[Cusco] = "Lima,null";
		VQuito[PuertoMaldonado] = "Lima,null";
		VQuito[Juliaca] = "Lima,null";
		VQuito[Arequipa] = "Lima,null";
		VQuito[Tacna] = "Lima,null";
		VQuito[Tarapoto] = "Lima,null";
		VQuito[Cajamarca] = "Lima,null";
		VQuito[Trujillo] = "Lima,null";
		VQuito[Chiclayo] = "Lima,null";
		VQuito[Iquitos] = "Lima,null";
		VQuito[Piura] = "Lima,null";
		VQuito[Talara] = "Lima,null";
		VQuito[Tumbes] = "Lima,null";

		//Guayaquil:
		VGuayaquil[Lima] = "Quito,Galapagos-Quito";
		VGuayaquil[Santiago] = "Lima,Quito-Lima";
		VGuayaquil[Quito] = "Galapagos,null";
		VGuayaquil[LaPaz] = "null,Quito-Lima";
		VGuayaquil[BuenosAires] = "Lima,null";
		VGuayaquil[Iquique] = "Santiago,Lima-Santiago";
		VGuayaquil[Cordoba] = "null,Quito-Lima";
		VGuayaquil[SantaCruz] = "null,Quito-Lima";
		VGuayaquil[PortoAlegre] = "null,Santiago-Sao Paulo";
		VGuayaquil[Asuncion] = "Lima,Santiago-Buenos Aires";
		VGuayaquil[Iguazu] = "null,Miami-Buenos Aires";
		VGuayaquil[SaoPaulo] = "New York,Lima-Santiago";
		VGuayaquil[Brasilia] = "null,Santiago-Sao Paulo";
		VGuayaquil[Mendoza] = "null, Santiago-Buenos Aires";
		VGuayaquil[Montevideo] = "Santiago, Lima-Sao Paulo";
		VGuayaquil[Rosario] = "null, Quito-Lima";
		VGuayaquil[Curitiba] = "null, Lima-Sao Paulo";
		VGuayaquil[RioDeJaneiro] = "Santiago, Lima-Sao Paulo";
		VGuayaquil[BeloHorizonte] = "null, Santiago-Sao Paulo";
		VGuayaquil[Salvador] = "null, Santiago-Rio de Janeiro";
		VGuayaquil[Recife] = "null, Santiago-Rio de Janeiro";
		VGuayaquil[Fortaleza] = "null, Lima-Sao Paulo";
		VGuayaquil[Belem] = "null, Santiago-Sao Paulo";
		VGuayaquil[Manaos] = "null, Lima-Sao Paulo";
		VGuayaquil[Cali] = "Miami, Lima-Bogota";
		VGuayaquil[Bogota] = "Lima, Quito-Lima";
		VGuayaquil[Medellin] = "Miami, Lima-Bogota";
		VGuayaquil[Cartagena] = "null, Lima-Bogota";
		VGuayaquil[Aruba] = "null, Santiago-Bogota";
		VGuayaquil[VillaHermosa] = "null, Santiago-Ciudad de Mexico";
		VGuayaquil[PuntaCana] = "Lima, Quito-Lima";
		VGuayaquil[Acapulco] = "null, Santiago-Ciudad de Mexico";
		VGuayaquil[CiudadDeMexico] = "Santiago, Quito-Lima";
		VGuayaquil[Veracruz] = "null, Santiago-Ciudad de Mexico";
		VGuayaquil[Merida] = "null, Santiago-Ciudad de Mexico";
		VGuayaquil[Cancun] = "Lima, Quito-Lima";
		VGuayaquil[LaHabana] = "null,Quito-Lima";

		VGuayaquil[PuertoVallarta] = "null, Santiago-Ciudad de Mexico";
		VGuayaquil[Guadalajara] = "null, Santiago-Ciudad de Mexico";
		VGuayaquil[Leon] = "null, Santiago-Ciudad de Mexico";
		VGuayaquil[SanJoseCabo] = "null, Santiago-Ciudad de Mexico";
		VGuayaquil[Torreon] = "null, Santiago-Ciudad de Mexico";
		VGuayaquil[Monterrey] = "null, Santiago-Ciudad de Mexico";
		VGuayaquil[Miami] = "Quito, Quito-Lima";
		VGuayaquil[Hermosillo] = "null, Santiago-Ciudad de Mexico";
		VGuayaquil[Houston] = "null, Quito-Miami";
		VGuayaquil[NewOrleans] = "null, Quito-Miami";
		VGuayaquil[Tampa] = "null, Quito-Miami";
		VGuayaquil[Orlando] = "null, Quito-Lima";
		VGuayaquil[Tijuana] = "null, Santiago-Ciudad de Mexico";
		VGuayaquil[Dallas] = "null, Quito-Miami";
		VGuayaquil[Atlanta] = "null, Quito-Miami";
		VGuayaquil[LosAngeles] = "Lima, Quito-Lima";
		VGuayaquil[Cancun] = "Lima, Quito-Lima";
		VGuayaquil[LasVegas] = "New York, Lima-Los Angeles";
		VGuayaquil[Charlotte] = "null, Quito-Miami";
		VGuayaquil[Washington] = "Nueva York, Lima-Miami";
		VGuayaquil[Baltimore] = "Nueva York, Lima-Miami";
		VGuayaquil[SanFrancisco] = "New York, Lima-Los Angeles";
		VGuayaquil[Reno] = "Dallas,null";
		VGuayaquil[Denver] = "null, Lima-Los Angeles";
		VGuayaquil[Seattle] = "New York, Quito-Miami";
		VGuayaquil[Vancouver] = "New York, New York-Seattle";
		VGuayaquil[Calgary] = "New York, New York-Toronto";
		VGuayaquil[Philadelphia] = "null, Lima-Miami";
		VGuayaquil[NewYork] = "Lima, Lima-Miami";
		VGuayaquil[Chicago] = "New York, Quito-Miami";
		VGuayaquil[Detroit] = "null, Quito-Miami";
		VGuayaquil[Toronto] = "null, Santiago-New York";
		VGuayaquil[Boston] = "New York, Lima-Miami";
		VGuayaquil[Montreal] = "null, Santiago-New York";



		//LaPaz:
		VLaPaz[Lima] = "Santiago,Santiago-Buenos Aires";
		VLaPaz[Santiago] = "Lima,null";
		VLaPaz[Quito] = "Lima,Lima-Guayaquil";
		VLaPaz[Guayaquil] = "Lima,Lima-Quito";
		VLaPaz[BuenosAires] = "Santiago,Lima-Santiago";
		VLaPaz[Iquique] = "Santiago,null";
		VLaPaz[Cordoba] = "Santiago,Santiago-Buenos Aires";
		VLaPaz[Iguazu] = "Lima,Lima-Sao Paulo";
		VLaPaz[SaoPaulo] = "Santiago,Lima-Buenos Aires";
		VLaPaz[Brasilia] = "null,Santiago-Sao Paulo";
		VLaPaz[Mendoza] = "Santiago, Santiago-Buenos Aires";
		VLaPaz[Montevideo] = "Santiago, Lima-Sao Paulo";
		VLaPaz[RioDeJaneiro] = "Santiago, Lima-Sao Paulo";
		VLaPaz[BeloHorizonte] = "null, Lima-Sao Paulo";
		VLaPaz[Salvador] = "null, Santiago-Rio de Janeiro";
		VLaPaz[Bogota] = "Lima, Santiago-Lima";
		VLaPaz[Medellin] = "null, Lima-Bogota";
		VLaPaz[Cartagena] = "null, Lima-Bogota";
		VLaPaz[VillaHermosa] = "null, Santiago-Ciudad de Mexico";
		VLaPaz[PuntaCana] = "Lima, Santiago-Lima";
		VLaPaz[CiudadDeMexico] = "Santiago, Lima-Sao Paulo";
		VLaPaz[Veracruz] = "null, Lima-Ciudad de Mexico";
		VLaPaz[Merida] = "null, Santiago-Ciudad de Mexico";
		VLaPaz[Cancun] = "Lima, Santiago-Lima";

		VLaPaz[Guadalajara] = "null, Santiago-Ciudad de Mexico";
		VLaPaz[Leon] = "null, Lima-Ciudad de Mexico";
		VLaPaz[Monterrey] = "null, Santiago-Ciudad de Mexico";
		VLaPaz[Miami] = "Lima, Santiago-Sao Paulo";
		VLaPaz[Orlando] = "null, Santiago-Lima";
		VLaPaz[Tijuana] = "null, Santiago-Ciudad de Mexico";
		VLaPaz[LosAngeles] = "null, Santiago-Lima";
		VLaPaz[Washington] = "null, Lima-Miami";
		VLaPaz[Baltimore] = "null, Lima-Miami";
		VLaPaz[NewYork] = "Lima, Santiago-Lima";
		VLaPaz[Pucallpa] = "Lima,Lima-Santiago";
		VLaPaz[Ayacucho] = "Lima,Lima-Santiago";
		VLaPaz[Cusco] = "Lima,Lima-Santiago";
		VLaPaz[PuertoMaldonado] = "Lima,Lima-Santiago";
		VLaPaz[Juliaca] = "Lima,Lima-Santiago";
		VLaPaz[Arequipa] = "Lima,Lima-Santiago";
		VLaPaz[Tacna] = "Lima,Lima-Santiago";
		VLaPaz[Tarapoto] = "Lima,Lima-Santiago";
		VLaPaz[Cajamarca] = "Lima,Lima-Santiago";
		VLaPaz[Trujillo] = "Lima,Lima-Santiago";
		VLaPaz[Chiclayo] = "Lima,Lima-Santiago";
		VLaPaz[Iquitos] = "Lima,Lima-Santiago";
		VLaPaz[Piura] = "Lima,Lima-Santiago";
		VLaPaz[Talara] = "Lima,Lima-Santiago";
		VLaPaz[Tumbes] = "Lima,Lima-Santiago";

		//Buenos Aires:
		VBuenosAires[Lima] = "Cordoba,null";
		VBuenosAires[Santiago] = "Cordoba,null";
		VBuenosAires[Quito] = "Lima,Santiago-Lima";
		VBuenosAires[Guayaquil] = "Lima,Lima-Quito";
		VBuenosAires[LaPaz] = "Lima,Santiago-Lima";
		VBuenosAires[Iquique] = "Santiago,San Juan-Santiago";
		VBuenosAires[SantaCruz] = "Lima,Santiago-Lima";
		VBuenosAires[PortoAlegre] = "Sao Paulo,Brasilia-Sao Paulo";
		VBuenosAires[Asuncion] = "Santiago,Cordoba-Sao Paulo";
		VBuenosAires[SaoPaulo] = "Cordoba,Rio de Janeiro-Brasilia";
		VBuenosAires[Brasilia] = "Rio de Janeiro,Sao Paulo-Belo Horizonte";
		VBuenosAires[Montevideo] = "Santiago,null";
		VBuenosAires[Florianopolis] = "Sao Paulo, Rio de Janeiro-Sao Paulo";
		VBuenosAires[Curitiba] = "Sao Paulo, Rio de Janeiro-Sao Paulo";
		VBuenosAires[RioDeJaneiro] = "Sao Paulo, Sao Paulo-Curitiba";
		VBuenosAires[BeloHorizonte] = "Sao Paulo, Rio de Janeiro-Sao Paulo";
		VBuenosAires[PortoSeguro] = "Sao Paulo, Cordoba-Sao Paulo";
		VBuenosAires[Salvador] = "Sao Paulo, Sao Paulo-Belo Horizonte";
		VBuenosAires[Recife] = "Brasilia, Rio de Janeiro-Sao Paulo";
		VBuenosAires[Fortaleza] = "Brasilia, Sao Paulo-Salvador";
		VBuenosAires[Belem] = "Sao Paulo, Sao Paulo-Brasilia";
		VBuenosAires[Manaos] = "Brasilia, Sao Paulo-Brasilia";
		VBuenosAires[Leticia] = "null, Santiago-Bogota";
		VBuenosAires[Cali] = "Miami, Santiago-Bogota";
		VBuenosAires[Bogota] = "Lima, Santiago-Lima";
		VBuenosAires[Medellin] = "null, Sao Paulo-Bogota";
		VBuenosAires[Cartagena] = "null, Sao Paulo-Bogota";
		VBuenosAires[Aruba] = "null, Santiago-Bogota";
		VBuenosAires[VillaHermosa] = "null, Lima-Ciudad de Mexico";
		VBuenosAires[SanJuan] = "Miami, Lima-Miami";
		VBuenosAires[PuntaCana] = "Lima, Sao Paulo-Lima";
		VBuenosAires[Acapulco] = "null, Lima-Ciudad de Mexico";
		VBuenosAires[CiudadDeMexico] = "Santiago, Santiago-Lima";
		VBuenosAires[Veracruz] = "null, Lima-Ciudad de Mexico";
		VBuenosAires[Merida] = "null, Lima-Ciudad de Mexico";
		VBuenosAires[Cancun] = "Lima, Santiago-Bogota";
		VBuenosAires[LaHabana] = "null, Sao Paulo-Lima";

		VBuenosAires[PuertoVallarta] = "null, Santiago-Ciudad de Mexico";
		VBuenosAires[Guadalajara] = "null, Lima-Ciudad de Mexico";
		VBuenosAires[Leon] = "null, Lima-Ciudad de Mexico";
		VBuenosAires[SanJoseCabo] = "null, Santiago-Ciudad de Mexico";
		VBuenosAires[Torreon] = "null, Lima-Ciudad de Mexico";
		VBuenosAires[Monterrey] = "null, Santiago-Ciudad de Mexico";
		VBuenosAires[Miami] = "Santiago, Santiago-Lima";
		VBuenosAires[Hermosillo] = "null, Santiago-Ciudad de Mexico";
		VBuenosAires[Houston] = "Miami, Lima-Miami";
		VBuenosAires[Tampa] = "Miami, Santiago-Miami";
		VBuenosAires[Orlando] = "Lima, Santiago-Lima";
		VBuenosAires[Tijuana] = "null, Santiago-Ciudad de Mexico";
		VBuenosAires[Phoenix] = "Miami, Sao Paulo-Miami";
		VBuenosAires[Dallas] = "Miami, Lima-Miami";
		VBuenosAires[Atlanta] = "Miami, Lima-Miami";
		VBuenosAires[SanDiego] = "Miami, Lima-Los Angeles";
		VBuenosAires[LosAngeles] = "Santiago, Santiago-Lima";
		VBuenosAires[LasVegas] = "Miami, Lima-Los Angeles";
		VBuenosAires[Charlotte] = "Miami, Santiago-Miami";
		VBuenosAires[Raleigh] = "Miami, Santiago-Miami";
		VBuenosAires[Washington] = "Miami, Lima-Miami";
		VBuenosAires[Baltimore] = "Miami, Lima-Miami";
		VBuenosAires[SanJose] = "null, Santiago-Los Angeles";
		VBuenosAires[SanFrancisco] = "Miami, Santiago-Los Angeles";
		VBuenosAires[Reno] = "null, Santiago-Los Angeles";
		VBuenosAires[Denver] = "Miami, Lima-Los Angeles";
		VBuenosAires[SaltLakeCity] = "null, Santiago-Buenos Aires";
		VBuenosAires[Portland] = "null, Santiago-Los Angeles";
		VBuenosAires[Seattle] = "null, Santiago-Los Angeles";
		VBuenosAires[Vancouver] = "null, Santiago-Los Angeles";
		VBuenosAires[Calgary] = "null, Santiago-Los Angeles";
		VBuenosAires[Philadelphia] = "Miami, Lima-Miami";
		VBuenosAires[SaintLouis] = "Miami, Lima-Miami";
		VBuenosAires[NewYork] = "Sao Paullo, Santiago-Lima";
		VBuenosAires[Chicago] = "Miami, Sao Paulo-Miami";
		VBuenosAires[Detroit] = "Miami, Santiago-Miami";
		VBuenosAires[Minneapolis] = "Miami, Sao Paulo-Miami";
		VBuenosAires[Toronto] = "Miami, Santiago-Miami";
		VBuenosAires[Boston] = "Miami, Sao Paulo-Miami";
		VBuenosAires[Montreal] = "Miami, Santiago-Miami";
		VBuenosAires[Pucallpa] = "Lima,null";
		VBuenosAires[Pucallpa] = "Lima,null";
		VBuenosAires[Ayacucho] = "Lima,null";
		VBuenosAires[Cusco] = "Lima,null";
		VBuenosAires[PuertoMaldonado] = "Lima,null";
		VBuenosAires[Juliaca] = "Lima,null";
		VBuenosAires[Arequipa] = "Lima,null";
		VBuenosAires[Tacna] = "Lima,null";
		VBuenosAires[Tarapoto] = "Lima,null";
		VBuenosAires[Cajamarca] = "Lima,null";
		VBuenosAires[Trujillo] = "Lima,null";
		VBuenosAires[Chiclayo] = "Lima,null";
		VBuenosAires[Iquitos] = "Lima,null";
		VBuenosAires[Piura] = "Lima,null";
		VBuenosAires[Talara] = "Lima,null";
		VBuenosAires[Tumbes] = "Lima,null";

		//Iquique
		VIquique[Lima] = "Santiago,Santiago-Buenos Aires";
		VIquique[Santiago] = "Antofagasta,null";
		VIquique[Guayaquil] = "Santiago,Santiago-Lima";
		VIquique[LaPaz] = "Lima,Sao Paulo-Lima";
		VIquique[BuenosAires] = "Santiago,Santiago-San Juan";
		VIquique[Cordoba] = "Santiago,Santiago-Buenos Aires";
		VIquique[Asuncion] = "Santiago,Antofagasta-Santiago";
		VIquique[Iguazu] = "null,Santiago-Buenos Aires";
		VIquique[SaoPaulo] = "Santiago,Santiago-Rio de Janeiro";
		VIquique[Brasilia] = "Santiago, Santiago-Asuncion";
		VIquique[Mendoza] = "Santiago, Santiago-Buenos Aires";
		VIquique[Montevideo] = "Santiago, Santiago-Sao Paulo";
		VIquique[Florianopolis] = "null, Santiago-Sao Paulo";
		VIquique[RioDeJaneiro] = "Santiago, Santiago-Sao Paulo";
		VIquique[Fortaleza] = "null, Santiago-Sao Paulo";
		VIquique[Belem] = "null, Santiago-Sao Paulo";
		VIquique[Cali] = "null, Santiago-Bogota";
		VIquique[Bogota] = "Santiago, Santiago-Lima";
		VIquique[Cartagena] = "null,Santiago-Bogota";
		VIquique[Aruba] = "null,Santiago-Bogota";
		VIquique[VillaHermosa] = "null,Santiago-Ciudad de Mexico";
		VIquique[SanJuan] = "null,Santiago-Buenos Aires";
		VIquique[PuntaCana] = "null,Santiago-Lima";
		VIquique[CiudadDeMexico] = "Santiago,Santiago-Lima";
		VIquique[Veracruz] = "null,Santiago-Ciudad de Mexico";
		VIquique[Merida] = "null,Santiago-Ciudad de Mexico";
		VIquique[Cancun] = "null,Santiago-Lima";
		VIquique[LaHabana] = "null,Santiago-Lima";
		VIquique[Pucallpa] = "null,Lima-Santiago";
		VIquique[Ayacucho] = "null,Lima-Santiago";
		VIquique[Cusco] = "null,Lima-Santiago";
		VIquique[PuertoMaldonado] = "null,Lima-Santiago";
		VIquique[Juliaca] = "null,Lima-Santiago";
		VIquique[Arequipa] = "null,Lima-Santiago";
		VIquique[Tacna] = "null,Lima-Santiago";
		VIquique[Tarapoto] = "null,Lima-Santiago";
		VIquique[Cajamarca] = "null,Lima-Santiago";
		VIquique[Trujillo] = "null,Lima-Santiago";
		VIquique[Chiclayo] = "null,Lima-Santiago";
		VIquique[Iquitos] = "null,Lima-Santiago";
		VIquique[Piura] = "null,Lima-Santiago";
		VIquique[Talara] = "null,Lima-Santiago";
		VIquique[Tumbes] = "null,Lima-Santiago";

		//Cordoba
		VCordoba[Lima] = "Santiago,Buenos Aires-Santiago";
		VCordoba[Santiago] = "Buenos Aires,null";
		VCordoba[Quito] = "Buenos Aires,Lima-Guayaquil";
		VCordoba[Guayaquil] = "Lima,Buenos Aires-Santiago";
		VCordoba[LaPaz] = "Santiago,Santiago-Lima";
		VCordoba[Iquique] = "Santiago,Buenos Aires-Santiago";
		VCordoba[Asuncion] = "Buenos Aires,null";
		VCordoba[Iguazu] = "Buenos Aires,null";
		VCordoba[SaoPaulo] = "Santiago,Buenos Aires-Brasilia";
		VCordoba[Brasilia] = "Buenos Aires,Sao Paulo-Rio de Janeiro";
		VCordoba[Mendoza] = "Buenos Aires,null";
		VCordoba[Montevideo] = "Sao Paulo,Buenos Aires-Santiago";
		VCordoba[Florianopolis] = "Sao Paulo, Buenos Aires-Sao Paulo";
		VCordoba[Curitiba] = "Sao Paulo, Buenos Aires-Sao Paulo";
		VCordoba[RioDeJaneiro] = "Sao Paulo, Buenos Aires-Sao Paulo";
		VCordoba[BeloHorizonte] = "Sao Paulo, Buenos Aires-Sao Paulo";
		VCordoba[PortoSeguro] = "null, Buenos Aires-Sao Paulo";
		VCordoba[Salvador] = "Sao Paulo, Santiago-Sao Paulo";
		VCordoba[Fortaleza] = "Sao Paulo, Santiago-Sao Paulo";
		VCordoba[Manaos] = "Sao Paulo, Buenos Aires-Sao Paulo";
		VCordoba[Cali] = "null, Buenos Aires-Bogota";
		VCordoba[Bogota] = "Buenos Aires,null";
		VCordoba[Medellin] = "null, Buenos Aires-Bogota";
		VCordoba[Cartagena] = "null,Lima-Bogota";
		VCordoba[Aruba] = "null,Santiago-Bogota";
		VCordoba[VillaHermosa] = "null,Sao Paulo-Ciudad de Mexico";
		VCordoba[SanJuan] = "null,Santiago-Miami";
		VCordoba[PuntaCana] = "Lima,Buenos Aires-Lima";
		VCordoba[Acapulco] = "null,Sao Paulo-Ciudad de Mexico";
		VCordoba[CiudadDeMexico] = "Santiago,Buenos Aires-Sao Paulo";
		VCordoba[Veracruz] = "null,Sao Paulo-Ciudad de Mexico";
		VCordoba[Merida] = "null,Sao Paulo-Ciudad de Mexico";
		VCordoba[Cancun] = "Lima,Sao Paulo-Miami";
		VCordoba[LaHabana] = "null,Buenos Aires-Lima";
		VCordoba[Cusco] = "null,Buenos Aires-Lima";
		VCordoba[PuertoMaldonado] = "null,Buenos Aires-Lima";
		VCordoba[Juliaca] = "null,Buenos Aires-Lima";
		VCordoba[Arequipa] = "null,Buenos Aires-Lima";
		VCordoba[Tacna] = "null,Buenos Aires-Lima";
		VCordoba[Tarapoto] = "null,Buenos Aires-Lima";
		VCordoba[Cajamarca] = "null,Buenos Aires-Lima";
		VCordoba[Trujillo] = "null,Buenos Aires-Lima";
		VCordoba[Chiclayo] = "null,Buenos Aires-Lima";
		VCordoba[Iquitos] = "null,Buenos Aires-Lima";
		VCordoba[Piura] = "null,Buenos Aires-Lima";
		VCordoba[Talara] = "null,Buenos Aires-Lima";
		VCordoba[Tumbes] = "null,Buenos Aires-Lima";
		VCordoba[Pucallpa] = "null,Buenos Aires-Lima";


		//SantaCruz
		VSantaCruz[Lima] = "null,Iquique-Santiago";
		VSantaCruz[Santiago] = "Lima,Lima-Montevideo";
		VSantaCruz[Quito] = "Lima,Lima-Guayaquil";
		VSantaCruz[Guayaquil] = "null,Lima-Quito";
		VSantaCruz[BuenosAires] = "Lima,Lima-Santiago";
		VSantaCruz[Iquique] = "null,Lima-Santiago";
		VSantaCruz[Cordoba] = "null,Lima-Bogota";
		VSantaCruz[SaoPaulo] = "Lima,Lima-Montevideo";
		VSantaCruz[Mendoza] = "null,Lima-Santiago";
		VSantaCruz[Montevideo] = "Lima,Lima-Sao Paulo";
		VSantaCruz[RioDeJaneiro] = "Santiago, Lima-Sao Paulo";
		VSantaCruz[Cali] = "null,Lima-Bogota";
		VSantaCruz[Bogota] = "Lima,Lima-Santiago";
		VSantaCruz[Medellin] = "null,Lima-Bogota";
		VSantaCruz[Panama] = "null,Lima-Bogota";
		VSantaCruz[VillaHermosa] = "null,Lima-Ciudad de Mexico";
		VSantaCruz[PuntaCana] = "Lima,null";
		VSantaCruz[CiudadDeMexico] = "Lima,null";
		VSantaCruz[Veracruz] = "null,Lima-Ciudad de Mexico";
		VSantaCruz[Merida] = "null,Lima-Ciudad de Mexico";
		VSantaCruz[Cancun] = "null,Lima-Ciudad de Mexico";
		VSantaCruz[LaHabana] = "null,Santiago-Lima";

		//PortoAlegre
		VPortoAlegre[Lima] = "Sao Paulo,Sao Paulo-Santiago";
		VPortoAlegre[Santiago] = "Rio de Janeiro,Sao Paulo-Buenos Aires";
		VPortoAlegre[Quito] = "null,Sao Paolo-Lima";
		VPortoAlegre[Guayaquil] = "null,Sao Paolo-Santiago";
		VPortoAlegre[BuenosAires] = "Sao Paulo,Sao Paulo-Rio de Janeiro";
		VPortoAlegre[SaoPaulo] = "Curitiba,null";
		VPortoAlegre[Mendoza] = "Sao Paulo,null";
		VPortoAlegre[Montevideo] = "Sao Paulo, Brasilia-Sao Paulo";
		VPortoAlegre[RioDeJaneiro] = "Sao Paulo, null";
		VPortoAlegre[Cali] = "Sao Paulo, Bogota";
		VPortoAlegre[Bogota] = "Sao Paulo, Sao Paulo-Lima";
		VPortoAlegre[Medellin] = "null,Sao Paulo-Bogota";
		VPortoAlegre[Cartagena] = "null, Sao Paulo-Bogota";
		VPortoAlegre[VillaHermosa] = "null, Sao Paulo-Ciudad de Mexico";
		VPortoAlegre[PuntaCana] = "Brasilia, Sao Paulo-Lima";
		VPortoAlegre[CiudadDeMexico] = "Sao Paulo, Brasilia-Sao Paulo";
		VPortoAlegre[Veracruz] = "null,Sao Paulo-Ciudad de Mexico";
		VPortoAlegre[Cancun] = "null,Sao Paulo-Lima";


		//Asuncion
		VAsuncion[Lima] = "Santiago,Buenos Aires-Santiago";
		VAsuncion[Santiago] = "Buenos Aires,Sao Paulo-Rio de Janeiro";
		VAsuncion[Quito] = "Buenos Aires,Lima-Guayaquil";
		VAsuncion[Guayaquil] = "Lima,Sao Paulo-Santiago";
		VAsuncion[BuenosAires] = "Santiago,null";
		VAsuncion[Iquique] = "Lima,Lima-Santiago";
		VAsuncion[Cordoba] = "Buenos Aires,Santiago-Buenos Aires";
		VAsuncion[SaoPaulo] = "Buenos Aires,null";
		VAsuncion[Mendoza] = "Buenos Aires, Santiago-Buenos Aires";
		VAsuncion[Montevideo] = "Sao Paulo, Buenos Aires-Santiago";
		VAsuncion[RioDeJaneiro] = "Sao Paulo, Sao Paulo-Brasilia";
		VAsuncion[Cali] = "null,Buenos Aires-Bogota";
		VAsuncion[Bogota] = "Sao Paulo, Buenos Aires-Sao Paulo";
		VAsuncion[Cartagena] = "null,Buenos Aires-Bogota";
		VAsuncion[VillaHermosa] = "null,Santiago-Ciudad de Mexico";
		VAsuncion[CiudadDeMexico] = "Sao Paulo, Sau Paulo-Lima";
		VAsuncion[Merida] = "null, Sao Paulo-Ciudad de Mexico";
		VAsuncion[Cancun] = "null, Sao Paulo-Ciudad de Mexico";

		//Iguazu
		VIguazu[Lima] = "Buenos Aires,Buenos Aires-Santiago";
		VIguazu[Santiago] = "Buenos Aires,Buenos Aires-Sao Paulo";
		VIguazu[Quito] = "Buenos Aires,Buenos Aires-Lima";
		VIguazu[Guayaquil] = "null,Buenos Aires-Lima";
		VIguazu[Iquique] = "null,Buenos Aires-Santiago";
		VIguazu[Cordoba] = "Buenos Aires,null";
		VIguazu[Mendoza] = "Buenos Aires,null";
		VIguazu[Montevideo] = "null,Buenos Aires-Santiago";
		VIguazu[RioDeJaneiro] = "Buenos Aires,Buenos Aires-Santiago";
		VIguazu[Cali] = "null,Buenos Aires-Santiago";
		VIguazu[Cartagena] = "null,Buenos Aires-Lima";
		VIguazu[SanJuan] = "Buenos Aires,null";
		VIguazu[CiudadDeMexico] = "null,Buenos Aires-Sao Paulo";
		VIguazu[Cancun] = "null,Buenos Aires-Lima";

		//SaoPaulo
		VSaoPaulo[Lima] = "Foz de Iguazu,Asuncion-Santiago";
		VSaoPaulo[Santiago] = "Asuncion,Rio de Janeiro-Buenos Aires";
		VSaoPaulo[Quito] = "Lima,Santiago-Guayaquil";
		VSaoPaulo[Guayaquil] = "Santiago,Lima-Quito";
		VSaoPaulo[LaPaz] = "Lima,Santiago-Lima";
		VSaoPaulo[BuenosAires] = "Rio de Janeiro,Asuncion-Santiago";
		VSaoPaulo[Iquique] = "Santiago,Rio de Janeiro";
		VSaoPaulo[Cordoba] = "Lima,Santiago-Buenos Aires";
		VSaoPaulo[SantaCruz] = "Lima,Santiago-Lima";
		VSaoPaulo[PortoAlegre] = "Curitiba,null";
		VSaoPaulo[Asuncion] = "Santiago,Rio de Janeiro-Buenos Aires";
		VSaoPaulo[Brasilia] = "Belo Horizonte,null";
		VSaoPaulo[Mendoza] = "Buenos Aires,Santiago-Buenos Aires";
		VSaoPaulo[Montevideo] = "Rio de Janeiro,Buenos Aires-Santiago";
		VSaoPaulo[Rosario] = "Lima,Santiago-Lima";
		VSaoPaulo[Florianopolis] = "Rio de Janeiro,null";
		VSaoPaulo[Curitiba] = "Porto Alegre,null";
		VSaoPaulo[BeloHorizonte] = "Rio de Janeiro,null";
		VSaoPaulo[Salvador] = "Brasilia,null";
		VSaoPaulo[Recife] = "Brasilia,null";
		VSaoPaulo[Fortaleza] = "Salvador,null";
		VSaoPaulo[Belem] = "Rio de Janeiro,null";
		VSaoPaulo[Manaos] = "Brasilia,null";
		VSaoPaulo[Leticia] = "Bogota,Santiago-Bogota";
		VSaoPaulo[Cali] = "Bogota,Buenos Aires-Bogota";
		VSaoPaulo[Bogota] = "Lima,Santiago-Lima";
		VSaoPaulo[Medellin] = "Bogota,Lima-Bogota";
		VSaoPaulo[Cartagena] = "Bogota,Lima-Bogota";
		VSaoPaulo[Aruba] = "Bogota,Santiago-Bogota";
		VSaoPaulo[VillaHermosa] = "Ciudad de Mexico,Santiago-Ciudad de Mexico";
		VSaoPaulo[SanJuan] = "Miami,Lima-Miami";
		VSaoPaulo[PuntaCana] = "Brasilia,Santiago-Lima";
		VSaoPaulo[Acapulco] = "null,Lima-Ciudad de Mexico";
		VSaoPaulo[CiudadDeMexico] = "Santiago,Buenos Aires-Santiago";
		VSaoPaulo[Veracruz] = "null,Lima-Ciudad de Mexico";
		VSaoPaulo[Merida] = "Ciudad de Mexico,Santiago-Ciudad de Mexico";
		VSaoPaulo[Cancun] = "Bogota,null";
		VSaoPaulo[LaHabana] = "Lima,Santiago-Lima";

		//Brasilia
		VBrasilia[Lima] = "Sao Paulo,Belo Horizonte-Sao Paulo";
		VBrasilia[Santiago] = "Sao Paulo,Rio de Janeiro-Sao Paulo";
		VBrasilia[Quito] = "null,Sao Paulo-Lima";
		VBrasilia[Guayaquil] = "null,Sao Paulo-Santiago";
		VBrasilia[LaPaz] = "null,Sao Paulo-Lima";
		VBrasilia[BuenosAires] = "Sao Paulo,Sao Paulo-Rio de Janeiro";
		VBrasilia[Cordoba] = "Buenos Aires,Rio de Janeiro-Sao Paulo";
		VBrasilia[SaoPaulo] = "Rio de Janeiro,null";
		VBrasilia[Mendoza] = "Buenos Aires,Sao Paulo-Buenos Aires";
		VBrasilia[Montevideo] = "Sao Paulo,Sao Paulo-Rio de Janeiro";
		VBrasilia[RioDeJaneiro] = "Sao Paulo,null";
		VBrasilia[Fortaleza] = "Salvador,null";
		VBrasilia[Manaos] = "null,Rio de Janeiro";
		VBrasilia[Cali] = "null,Sao Paulo-Bogota";
		VBrasilia[Bogota] = "Sao Paulo,Sao Paulo-Lima";
		VBrasilia[Medellin] = "null,Sao Paulo-Bogota";
		VBrasilia[Cartagena] = "null,Sao Paulo-Bogota";
		VBrasilia[VillaHermosa] = "null,Sao Paulo-Ciudad de Mexico";
		VBrasilia[CiudadDeMexico] = "Sao Paulo,Rio de Janeiro-Sao Paulo";
		VBrasilia[Cancun] = "null,Sao Paulo-Lima";


		//Mendoza
		VMendoza[Lima] = "Santiago,null";
		VMendoza[Santiago] = "Buenos Aires,null";
		VMendoza[Quito] = "Buenos Aires,Santiago-Lima";
		VMendoza[Guayaquil] = "Buenos Aires,Buenos Aires-Santiago";
		VMendoza[LaPaz] = "Santiago,Santiago-Lima";
		VMendoza[Iquique] = "Santiago,Buenos Aires-Santiago";
		VMendoza[Cordoba] = "Buenos Aires,null";
		VMendoza[SantaCruz] = "null,Santiago-Lima";
		VMendoza[PortoAlegre] = "null,Buenos Aires-Sao Paulo";
		VMendoza[Asuncion] = "Santiago,Buenos Aires-Santiago";;
		VMendoza[Iguazu] = "Buenos Aires,null";
		VMendoza[SaoPaulo] = "Buenos Aires,Santiago-Asuncion";
		VMendoza[Brasilia] = "Buenos Aires,Buenos Aires-Sao Paulo";
		VMendoza[Montevideo] = "Santiago,Santiago-Sao Paulo";
		VMendoza[Florianopolis] = "null,Santiago-Sao Paulo";
		VMendoza[Curitiba] = "null,Buenos Aires-Sao Paulo";
		VMendoza[RioDeJaneiro] = "Santiago,Santiago-Sao Paulo";
		VMendoza[BeloHorizonte] = "null,Buenos Aires-Sao Paulo";
		VMendoza[Salvador] = "null,Buenos Aires-Sao Paulo";
		VMendoza[Recife] = "null,Santiago-Rio de Janeiro";
		VMendoza[Belem] = "null,Buenos Aires-Brasilia";
		VMendoza[Cali] = "null,Santiago-Bogota";
		VMendoza[Bogota] = "Santiago,Santiago-Lima";
		VMendoza[Medellin] = "null,Santiago-Bogota";
		VMendoza[Cartagena] = "null,Santiago-Bogota";
		VMendoza[Aruba] = "null,Santiago-Bogota";
		VMendoza[SanJuan] = "Buenos Aires,null";
		VMendoza[PuntaCana] = "null,Buenos Aires-Lima";
		VMendoza[CiudadDeMexico] = "Santiago,Buenos Aires-Santiago";
		VMendoza[Merida] = "null,Santiago-Ciudad de Mexico";
		VMendoza[Cancun] = "null,Buenos Aires-Lima";
		VMendoza[LaHabana] = "null,Buenos Aires-Lima";

		VBogota[Lima] = "Santiago,null";
		VBogota[Santiago] = "Lima,null";
		VBogota[Quito] = "Lima,null";
		VBogota[Guayaquil] = "Lima,null";
		VBogota[LaPaz] = "Santiago, Santiago-Lima";
		VBogota[BuenosAires] = "Lima,Lima-Santiago";
		VBogota[Iquique] = "Santiago,Lima-Santiago";
		VBogota[Cordoba] = "Lima,Lima-Buenos Aires";
		VBogota[SantaCruz] = "Lima,Santiago-Lima";
		VBogota[PortoAlegre] = "Sao Paulo,Santiago-Sao Paulo";
		VBogota[Asuncion] = "Lima,Buenos Aires-SaoPaulo";
		VBogota[Iguazu] = "null,Sao Paulo-Buenos Aires";
		VBogota[SaoPaulo] = "Lima,Lima-Montevideo";
		VBogota[Brasilia] = "Sao Paulo,Sao Paulo-Rio de Janeiro";
		VBogota[Mendoza] = "Lima,Lima-Guayaquil";
		VBogota[Montevideo] = "Lima,Lima-Sao Paulo";
		VBogota[Rosario] = "Lima,Sao Paulo-Lima";
		VBogota[Florianopolis] = "Sao Paulo,Santiago-Sao Paulo";
		VBogota[Curitiba] = "Sao Paulo, Sao Paulo-Porto Alegre";
		VBogota[RioDeJaneiro] = "Sao Paulo,Sao Paulo-Florianopolis";
		VBogota[BeloHorizonte] = "Sao Paulo,Santiago-Sao Paulo";
		VBogota[Salvador] = "Sao Paulo,Sao Paulo-Belo Horizonte";
		VBogota[Recife] = "Sao Paulo,Sao Paulo-Belo Horizonte";
		VBogota[Fortaleza] = "sao Paulo,Lima-Sao Paulo";
		VBogota[Manaos] = "Sao Paulo,Brasilia-Sao Paulo";
		VBogota[Medellin] = "Cartagena de Indias,null";
		VBogota[Panama] = "Lima,null";
		VBogota[Cartagena] = "Medellin,null";
		VBogota[PuntaCana] = "Lima,null";
		VBogota[Acapulco] = "null,Lima-Ciudad de Mexico";
		VBogota[CiudadDeMexico] = "Lima,Miami-Lima";
		VBogota[Veracruz] = "null,Lima-Ciudad de Mexico";
		VBogota[Cancun] = "null,Miami-Lima";
		VBogota[LaHabana] = "Lima,Santiago-Lima";
		VBogota[Pucallpa] = "null,Quito-Lima";
		VBogota[Ayacucho] = "null,Quito-Lima";
		VBogota[Cusco] = "null,Quito-Lima";
		VBogota[PuertoMaldonado] = "null,Quito-Lima";
		VBogota[Juliaca] = "null,Quito-Lima";
		VBogota[Arequipa] = "null,Quito-Lima";
		VBogota[Tacna] = "null,Quito-Lima";
		VBogota[Tarapoto] = "null,Quito-Lima";
		VBogota[Cajamarca] = "null,Quito-Lima";
		VBogota[Trujillo] = "null,Quito-Lima";
		VBogota[Chiclayo] = "null,Quito-Lima";
		VBogota[Iquitos] = "null,Quito-Lima";
		VBogota[Piura] = "null,Quito-Lima";
		VBogota[Talara] = "null,Quito-Lima";
		VBogota[Tumbes] = "null,Quito-Lima";

		VMedellin[Lima] = "Bogota,Bogota-Santiago";
		VMedellin[Santiago] = "Bogota,Bogota-Lima";
		VMedellin[Quito] = "null,Bogota-Lima";
		VMedellin[Guayaquil] = "Miami,Bogota-Miami";
		VMedellin[LaPaz] = "null,Bogota-Lima";
		VMedellin[BuenosAires] = "Miami,Bogota-Lima";
		VMedellin[Cordoba] = "null,Bogota-Sao Paulo";
		VMedellin[SantaCruz] = "null,Bogota-Lima";
		VMedellin[PortoAlegre] = "null,Bogota-Sao Paulo";
		VMedellin[Iguazu] = "null,Bogota-Buenos Aires";
		VMedellin[SaoPaulo] = "Bogota,Bogota-Santiago";
		VMedellin[Brasilia] = "null,Bogota-Sao Paulo";
		VMedellin[Mendoza] = "null,Bogota-Buenos Aires";
		VMedellin[Montevideo] = "null,Bogota-Sao Paulo";
		VMedellin[Rosario] = "null,Bogota-Lima";
		VMedellin[Florianopolis] = "null,Bogota-Sao Paulo";
		VMedellin[Curitiba] = "null,Bogota-Sao Paulo";
		VMedellin[RioDeJaneiro] = "Miami,Bogota-Sao Paulo";
		VMedellin[BeloHorizonte] = "null,Bogota-Sao Paulo";
		VMedellin[Salvador] = "null,Bogota-Sao Paulo";
		VMedellin[Recife] = "null,Bogota-Sao Paulo";
		VMedellin[Fortaleza] = "null,Bogota-Sao Paulo";
		VMedellin[Manaos] = "Sao Paulo,Brasilia-Sao Paulo";
		VMedellin[Leticia] = "Bogota,null";
		VMedellin[Cali] = "Bogota,Cartagena-Bogota";
		VMedellin[Bogota] = "Cartagena de Indias,null";
		VMedellin[Cartagena] = "Bogota,null";
		VMedellin[Aruba] = "Bogota,Cartagena-Bogota";
		VMedellin[CiudadDeMexico] = "null,Bogota-Sao Paulo";
		VMedellin[Cancun] = "Bogota,Miami-Lima";

		VCartagena[Lima] = "Bogota,Medellin-Bogota";
		VCartagena[Santiago] = "Bogota,Medellin-Bogota";
		VCartagena[Quito] = "null,Bogota-Lima";
		VCartagena[Guayaquil] = "null,Bogota-Miami";
		VCartagena[LaPaz] = "null,Bogota-Lima";
		VCartagena[BuenosAires] = "null,Sao Paulo-Bogota";
		VCartagena[Iquique] = "null,Bogota-Santiago";
		VCartagena[Cordoba] = "null,Bogota-Sao Paulo";
		VCartagena[PortoAlegre] = "null,Lima-Sao Paulo";
		VCartagena[SaoPaulo] = "Buenos Aires,null";
		VCartagena[Mendoza] = "Buenos Aires,Santiago-Buenos Aires";
		VCartagena[Montevideo] = "Sao Paulo,null";
		VCartagena[RioDeJaneiro] = "Buenos Aires, Santiago-Sao Paulo";
		VCartagena[Cali] = "null,Santiago-Bogota";
		VCartagena[Bogota] = "medellin, Santiago-Lima";
		VCartagena[Medellin] = "Bogota,Bogota-San Andres";
		VCartagena[VillaHermosa] = "Santiago,Ciudad de Mexico";
		VCartagena[CiudadDeMexico] = "Sao Paulo, Santiago-Lima";
		VCartagena[Cancun] = "Bogota,Bogota-Lima";

		VAruba[Lima] = "Bogota,Bogota-Santiago";
		VAruba[Santiago] = "Bogota,Bogota-Lima";
		VAruba[Guayaquil] = "null,Bogota-Lima";
		VAruba[BuenosAires] = "null,Bogota-Santiago";
		VAruba[Iquique] = "null,Bogota-Santiago";
		VAruba[Cordoba] = "null,Bogota-Santiago";
		VAruba[SaoPaulo] = "Bogota,Bogota-Santiago";
		VAruba[Mendoza] = "null,Bogota-Santiago";
		VAruba[Montevideo] = "Sao Paulo,null";
		VAruba[RioDeJaneiro] = "null,Bogota-Santiago";
		VAruba[Cali] = "Bogota,Bogota-San Andres";
		VAruba[Medellin] = "Bogota,null";
		VAruba[Cartagena] = "Bogota,null";

		VVillaHermosa[Lima] = "Ciudad de Mexico,null";
		VVillaHermosa[Santiago] = "Ciudad de Mexico,Ciudad de Mexico-Lima";
		VVillaHermosa[Quito] = "null,Ciudad de Mexico-Lima";
		VVillaHermosa[LaPaz] = "null,Ciudad de Mexico-Lima";
		VVillaHermosa[BuenosAires] = "null,Ciudad de Mexico-Lima";
		VVillaHermosa[Iquique] = "null,Ciudad de Mexico-Santiago";
		VVillaHermosa[Cordoba] = "null,Ciudad de Mexico-Lima";
		VVillaHermosa[SantaCruz] = "null,Ciudad de Mexico-Lima";
		VVillaHermosa[PortoAlegre] = "null,Ciudad de Mexico-Lima";
		VVillaHermosa[Asuncion] = "null,Ciudad de Mexico-Lima";
		VVillaHermosa[SaoPaulo] = "Ciudad de Mexico,Ciudad de Mexico-Lima";
		VVillaHermosa[Brasilia] = "null,Ciudad de Mexico-Sao Paulo";
		VVillaHermosa[Mendoza] = "null,Ciudad de Mexico-Santiago";
		VVillaHermosa[Montevideo] = "null,Ciudad de Mexico-Santiago";
		VVillaHermosa[Rosario] = "null,Ciudad de Mexico-Lima";
		VVillaHermosa[Curitiba] = "null,Ciudad de Mexico-Sao Paulo";
		VVillaHermosa[RioDeJaneiro] = "null,Ciudad de Mexico-Santiago";
		VVillaHermosa[PortoSeguro] = "null,Ciudad de Mexico-Sao Paulo";
		VVillaHermosa[Belem] = "null,Ciudad de Mexico-Sao Paulo";
		VVillaHermosa[Manaos] = "null,Ciudad de Mexico-Sao Paulo";
		VVillaHermosa[Bogota] = "null,Ciudad de Mexico-Lima";

		VSanJuan[Lima] = "Buenos Aires,Buenos Aires-Sao Paulo";
		VSanJuan[Santiago] = "Buenos Aires,null";
		VSanJuan[Quito] = "Buenos Aires,Buenos Aires-Lima";
		VSanJuan[Iquique] = "null,Buenos Aires-Santiago";
		VSanJuan[Iguazu] = "Buenos Aires,null";
		VSanJuan[Montevideo] = "null,Buenos Aires-Santiago";
		VSanJuan[Florianopolis] = "null,Buenos Aires-Sao Paulo";
		VSanJuan[RioDeJaneiro] = "Buenos Aires,Buenos Aires-Sao Paulo";
		VSanJuan[Cali] = "null,Buenos Aires-Miami";
		VSanJuan[CiudadDeMexico] = "null,Buenos Aires-Lima";
		VSanJuan[Cancun] = "null,Buenos Aires-Lima";

		VPuntaCana[Santiago] = "Lima,Miami-Lima";
		VPuntaCana[Quito] = "Lima,Lima-Guayaquil";
		VPuntaCana[Guayaquil] = "Lima,Lima-Quito";
		VPuntaCana[LaPaz] = "Lima,Lima-Santiago";
		VPuntaCana[BuenosAires] = "Lima,Lima-Cordoba";
		VPuntaCana[Iquique] = "null,Lima-Santiago";
		VPuntaCana[Cordoba] = "Lima,Lima-Buenos Aires";
		VPuntaCana[SantaCruz] = "Lima,null";
		VPuntaCana[PortoAlegre] = "null,Lima-Sao Paulo";
		VPuntaCana[SaoPaulo] = "Lima,Lima-Santiago";
		VPuntaCana[Mendoza] = "null,Lima-Santiago";
		VPuntaCana[Montevideo] = "Lima,Miami-Santiago";
		VPuntaCana[Florianopolis] = "null,Santiago-Sao Paulo";
		VPuntaCana[Curitiba] = "null,Lima-Sao Paulo";
		VPuntaCana[RioDeJaneiro] = "Santiago,Lima-Sao Paulo";
		VPuntaCana[PortoSeguro] = "null,Santiago-Sao Paulo";
		VPuntaCana[Salvador] = "null,Lima-Sao paulo";
		VPuntaCana[Recife] = "null,Lima-Sao Paulo";
		VPuntaCana[Belem] = "null,Lima-Sao Paulo";
		VPuntaCana[Manaos] = "null,Lima-Sao Paulo";
		VPuntaCana[Cali] = "null,Lima-Bogota";
		VPuntaCana[Bogota] = "Lima,null";	

		VAcapulco[Lima] = "null,Ciudad de Mexico-Santiago";
		VAcapulco[Santiago] = "Ciudad de Mexico,null";
		VAcapulco[Quito] = "null,Ciudad de Mexico-Lima";
		VAcapulco[BuenosAires] = "null,Ciudad de Mexico-Santiago";
		VAcapulco[Cordoba] = "null,Ciudad de Mexico-Santiago";
		VAcapulco[SaoPaulo] = "null,Ciudad de Mexico-Santiago";
		VAcapulco[Montevideo] = "null,Ciudad de Mexico-Santiago";
		VAcapulco[RioDeJaneiro] = "null,Ciudad de Mexico-Santiago";
		VAcapulco[Pucallpa] = "null,Ciudad de Mexico-Lima";
		VAcapulco[Ayacucho] = "null,Ciudad de Mexico-Lima";
		VAcapulco[Cusco] = "null,Ciudad de Mexico-Lima";
		VAcapulco[PuertoMaldonado] = "null,Ciudad de Mexico-Lima";
		VAcapulco[Juliaca] = "null,Ciudad de Mexico-Lima";
		VAcapulco[Arequipa] = "null,Ciudad de Mexico-Lima";
		VAcapulco[Tacna] = "null,Ciudad de Mexico-Lima";
		VAcapulco[Tarapoto] = "null,Ciudad de Mexico-Lima";
		VAcapulco[Cajamarca] = "null,Ciudad de Mexico-Lima";
		VAcapulco[Trujillo] = "null,Ciudad de Mexico-Lima";
		VAcapulco[Chiclayo] = "null,Ciudad de Mexico-Lima";
		VAcapulco[Iquitos] = "null,Ciudad de Mexico-Lima";
		VAcapulco[Piura] = "null,Ciudad de Mexico-Lima";
		VAcapulco[Talara] = "null,Ciudad de Mexico-Lima";
		VAcapulco[Tumbes] = "null,Ciudad de Mexico-Lima";

		VCiudadDeMexico[Lima] = "Santiago,Sao Paulo-Santiago";
		VCiudadDeMexico[Santiago] = "Sao Paulo,Sao Paulo-Rio de Janeiro";
		VCiudadDeMexico[Quito] = "Lima,null";
		VCiudadDeMexico[Guayaquil] = "Santiago, Lima - Quito";
		VCiudadDeMexico[BuenosAires] = "Santiago,Lima-Santiago";
		VCiudadDeMexico[Iquique] = "Santiago,Lima-Santiago";
		VCiudadDeMexico[Cordoba] = "Santiago,Sao Paulo-Buenos Aires";
		VCiudadDeMexico[SantaCruz] = "null,Santiago-Lima";
		VCiudadDeMexico[PortoAlegre] = "Sao Paulo,Santiago-Sao Paulo";
		VCiudadDeMexico[Asuncion] = "Sao Paulo,Sao Paulo-Santiago";
		VCiudadDeMexico[Iguazu] = "null,Santiago-Buenos Aires";
		VCiudadDeMexico[SaoPaulo] = "Lima,Santiago-Rio de Janeiro";
		VCiudadDeMexico[Brasilia] = "Sao Paulo,Sao Paulo-Belo Horizonte";
		VCiudadDeMexico[Mendoza] = "Santiago,Sao Paulo-Buenos Aires";
		VCiudadDeMexico[Montevideo] = "Santiago,Santiago-Sao Paulo";
		VCiudadDeMexico[Rosario] = "Lima,Santiago-Sao Paulo";
		VCiudadDeMexico[Florianopolis] = "Sao Paulo,Santiago-Sao Paulo";
		VCiudadDeMexico[Curitiba] = "Sao Paulo,Santiago-Sao Paulo";
		VCiudadDeMexico[RioDeJaneiro] = "Santiago,Sao Paulo-Belo Horizonte";
		VCiudadDeMexico[BeloHorizonte] = "Sao Paulo,null";
		VCiudadDeMexico[PortoSeguro] = "Sao Paulo,Santiago-Sao Paulo";
		VCiudadDeMexico[Salvador] = "Sao Paulo,Santiago-Sao Paulo";
		VCiudadDeMexico[Recife] = "Sao Paulo,null";
		VCiudadDeMexico[Fortaleza] = "Sao Paulo,Sao Paulo-Rio de Janeiro";
		VCiudadDeMexico[Belem] = "Sao Paulo,Sao Paulo-Santiago";
		VCiudadDeMexico[Manaos] = "Sao Paulo,Sao Paulo-Brasilia";
		VCiudadDeMexico[Leticia] = "null,Cancun-Bogota";
		VCiudadDeMexico[Cali] = "null,Cancun-Bogota";
		VCiudadDeMexico[Bogota] = "Cancun,Cancun-Lima";
		VCiudadDeMexico[Medellin] = "null,Cancun-Bogota";
		VCiudadDeMexico[Cartagena] = "null,Cancun-Bogota";
		VCiudadDeMexico[SanJuan] = "null,Santiago-BUenos Aires";
		VCiudadDeMexico[PuntaCana] = "null,Sao Paulo-Brasilia";
		VCiudadDeMexico[Pucallpa] = "Lima,null";
		VCiudadDeMexico[Pucallpa] = "Lima,null";
		VCiudadDeMexico[Ayacucho] = "Lima,null";
		VCiudadDeMexico[Juliaca] = "Lima,null";
		VCiudadDeMexico[Arequipa] = "Lima,null";
		VCiudadDeMexico[Tacna] = "Lima,null";
		VCiudadDeMexico[Tarapoto] = "Lima,null";
		VCiudadDeMexico[Cajamarca] = "Lima,null";
		VCiudadDeMexico[Trujillo] = "Lima,null";
		VCiudadDeMexico[Chiclayo] = "Lima,null";
		VCiudadDeMexico[Iquitos] = "Lima,null";
		VCiudadDeMexico[Piura] = "Lima,null";
		VCiudadDeMexico[Talara] = "Lima,null";
		VCiudadDeMexico[Tumbes] = "Lima,null";

		VVeracruz[Lima] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[Santiago] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[BuenosAires] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[PortoAlegre] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[Asuncion] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[SaoPaulo] = "Ciudad de Mexico,null";
		VVeracruz[Brasilia] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[Montevideo] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[Rosario] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[Florianopolis] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[Curitiba] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[RioDeJaneiro] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[BeloHorizonte] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[PortoSeguro] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[Recife] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[Fortaleza] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[Belem] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[Manaos] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[Bogota] = "null,Ciudad de Mexico-Sao Paulo";
		VVeracruz[Pucallpa] = "null,Ciudad de Mexico-Lima";
		VVeracruz[Ayacucho] = "null,Ciudad de Mexico-Lima";
		VVeracruz[Cusco] = "null,Ciudad de Mexico-Lima";
		VVeracruz[PuertoMaldonado] = "null,Ciudad de Mexico-Lima";
		VVeracruz[Juliaca] = "null,Ciudad de Mexico-Lima";
		VVeracruz[Arequipa] = "null,Ciudad de Mexico-Lima";
		VVeracruz[Tacna] = "null,Ciudad de Mexico-Lima";
		VVeracruz[Tarapoto] = "null,Ciudad de Mexico-Lima";
		VVeracruz[Cajamarca] = "null,Ciudad de Mexico-Lima";
		VVeracruz[Trujillo] = "null,Ciudad de Mexico-Lima";
		VVeracruz[Chiclayo] = "null,Ciudad de Mexico-Lima";
		VVeracruz[Iquitos] = "null,Ciudad de Mexico-Lima";
		VVeracruz[Piura] = "null,Ciudad de Mexico-Lima";
		VVeracruz[Talara] = "null,Ciudad de Mexico-Lima";
		VVeracruz[Tumbes] = "null,Ciudad de Mexico-Lima";

		VMerida[Lima] = "Ciudad de Mexico,Ciudad de Mexico-Santiago";
		VMerida[Santiago] = "Ciudad de Mexico,Ciudad de Mexico-Lima";
		VMerida[Quito] = "Ciudad de Mexico,Ciudad de Mexico-Lima";
		VMerida[LaPaz] = "Ciudad de Mexico,Ciudad de Mexico-Lima";
		VMerida[BuenosAires] = "null,Ciudad de Mexico-Lima";
		VMerida[Iquique] = "null,Ciudad de Mexico-Santiago";
		VMerida[Cordoba] = "null,Ciudad de Mexico-Lima";
		VMerida[SantaCruz] = "null,Ciudad de Mexico-Lima";
		VMerida[PortoAlegre] = "null,Ciudad de Mexico-Sao Paulo";
		VMerida[Asuncion] = "null,Ciudad de Mexico-Lima";
		VMerida[SaoPaulo] = "Ciudad de Mexico,Ciudad de Mexico-Lima";
		VMerida[Brasilia] = "null,Ciudad de Mexico-Sao Paulo";
		VMerida[Mendoza] = "null,Ciudad de Mexico-Santiago";
		VMerida[Montevideo] = "null,Ciudad de Mexico-Santiago";
		VMerida[Rosario] = "null,Ciudad de Mexico-Lima";
		VMerida[Florianopolis] = "null,Ciudad de Mexico-Sao Paulo";
		VMerida[Curitiba] = "null,Ciudad de Mexico-Sao Paulo";
		VMerida[RioDeJaneiro] = "null,Ciudad de Mexico-Sao Paulo";
		VMerida[BeloHorizonte] = "null,Ciudad de Mexico-Sao Paulo";
		VMerida[PortoSeguro] = "null,Ciudad de Mexico-Sao Paulo";
		VMerida[Recife] = "null,Ciudad de Mexico-Sao Paulo";
		VMerida[Fortaleza] = "null,Ciudad de Mexico-Sao Paulo";
		VMerida[Belem] = "null,Ciudad de Mexico-Sao Paulo";
		VMerida[Manaos] = "null,Ciudad de Mexico-Sao Paulo";

		VCancun[Lima] = "Ciudad de Mexico,Ciudad de Mexico-Santiago";
		VCancun[Santiago] = "Ciudad de Mexico,Ciudad de Mexico-Lima";
		VCancun[Quito] = "Lima,Ciudad de Mexico-Lima";
		VCancun[Guayaquil] = "Lima,Ciudad de Mexico-Santiago";
		VCancun[LaPaz] = "null,Lima-Santiago";
		VCancun[BuenosAires] = "Lima,Lima-Santiago";
		VCancun[Iquique] = "null,Lima-Santiago";
		VCancun[Cordoba] = "Lima,Lima-Santiago";
		VCancun[SantaCruz] = "Lima,Ciudad de Mexico-Lima";
		VCancun[PortoAlegre] = "null,Lima-Sao Paulo";
		VCancun[Asuncion] = "Lima,Bogota-Santiago";
		VCancun[Iguazu] = "null,Lima-Buenos Aires";
		VCancun[SaoPaulo] = "Ciudad de Mexico,Ciudad de Mexico-Lima";
		VCancun[Brasilia] = "null,Bogota-Sao Paulo";
		VCancun[Mendoza] = "null,Lima-Santiago";
		VCancun[Montevideo] = "Lima,Ciudad de Mexico-Santiago";
		VCancun[Rosario] = "Lima,Ciudad de Mexico-Lima";
		VCancun[Florianopolis] = "null,Santiago-Sao Paulo";
		VCancun[Curitiba] = "null,Lima-Sao Paulo";
		VCancun[RioDeJaneiro] = "null,Bogota-Sao Paulo";
		VCancun[BeloHorizonte] = "null,Bogota-Sao Paulo";
		VCancun[PortoSeguro] = "null,Bogota-Sao Paulo";
		VCancun[Recife] = "null,Lima-Sao Paulo";
		VCancun[Fortaleza] = "Miami,null";
		VCancun[Belem] = "null,Lima-Sao Paulo";
		VCancun[Manaos] = "null,Lima-Sao Paulo";
		VCancun[Leticia] = "null,Miami-Bogota";
		VCancun[Cali] = "Bogota,Miami-Bogota";
		VCancun[Bogota] = "Miami,Lima-Miami";
		VCancun[Medellin] = "Bogota,Miami-Bogota";
		VCancun[Cartagena] = "Bogota,Miami-Bogota";
		VCancun[SanJuan] = "null,Lima-Buenos Aires";

		VLaHabana[Santiago] = "Lima,Lima-Sao Paulo";
		VLaHabana[Quito] = "Lima,null";
		VLaHabana[Guayaquil] = "null,Lima-Quito";
		VLaHabana[BuenosAires] = "Lima,Lima-Sao Paulo";
		VLaHabana[Iquique] = "null,Lima-Santiago";
		VLaHabana[Cordoba] = "Lima,Lima-Santiago";
		VLaHabana[SantaCruz] = "Lima,null";
		VLaHabana[SaoPaulo] = "Lima,Lima-Santiago";
		VLaHabana[Mendoza] = "null,Lima-Santiago";
		VLaHabana[Montevideo] = "Lima,Lima-Santiago";
		VLaHabana[RioDeJaneiro] = "null,Lima-Santiago";
	
		VPucallpa[Santiago] = "Lima,null";
		VPucallpa[Quito] = "Lima,null";
		VPucallpa[Guayaquil] = "null,Lima-Quito";
		VPucallpa[BuenosAires] = "Lima,null";
		VPucallpa[Iquique] = "null,Lima-Santiago";
		VPucallpa[Cordoba] = "Lima,Lima-Buenos Aires";
		VPucallpa[SantaCruz] = "Lima,null";
		VPucallpa[SaoPaulo] = "Lima,null";
		VPucallpa[Mendoza] = "null,Lima-Santiago";
		VPucallpa[Montevideo] = "Lima,null";
		VPucallpa[RioDeJaneiro] = "Lima,null";
		VPucallpa[Bogota] = "Lima,Lima-Quito";
		VPucallpa[CiudadDeMexico] = "Lima,null";
		VPucallpa[Veracruz] = "null,Lima-Ciudad de Mexico";
		VPucallpa[Cancun] = "null,Lima-Ciudad de Mexico";
		VPucallpa[PuertoMaldonado] = "Lima,null";
		VPucallpa[Juliaca] = "Lima,null";
		VPucallpa[Arequipa] = "Lima,null";
		VPucallpa[Tacna] = "Lima,null";
		VPucallpa[Tarapoto] = "Lima,null";
		VPucallpa[Cajamarca] = "Lima,null";
		VPucallpa[Trujillo] = "Lima,null";
		VPucallpa[Chiclayo] = "Lima,null";
		VPucallpa[Iquitos] = "Lima,null";
		VPucallpa[Piura] = "Lima,null";
		VPucallpa[Talara] = "Lima,null";
		VPucallpa[Tumbes] = "Lima,null";
		VPucallpa[Cusco] = "Lima,null";
		VPucallpa[Ayacucho] = "Lima,null";

		VAyacucho[Santiago] = "Lima,null";
		VAyacucho[Quito] = "Lima,null";
		VAyacucho[Guayaquil] = "null,Lima-Quito";
		VAyacucho[BuenosAires] = "Lima,null";
		VAyacucho[Iquique] = "null,Lima-Santiago";
		VAyacucho[Cordoba] = "Lima,Lima-Buenos Aires";
		VAyacucho[SantaCruz] = "Lima,null";
		VAyacucho[Mendoza] = "null,Lima-Santiago";
		VAyacucho[Montevideo] = "Lima,null";
		VAyacucho[RioDeJaneiro] = "Lima,null";
		VAyacucho[Bogota] = "Lima,Lima-Quito";
		VAyacucho[CiudadDeMexico] = "Lima,null";
		VAyacucho[Pucallpa] = "Lima,null";
		VAyacucho[PuertoMaldonado] = "Lima,null";
		VAyacucho[Juliaca] = "Lima,null";
		VAyacucho[Arequipa] = "Lima,null";
		VAyacucho[Tacna] = "Lima,null";
		VAyacucho[Tarapoto] = "Lima,null";
		VAyacucho[Cajamarca] = "Lima,null";
		VAyacucho[Trujillo] = "Lima,null";
		VAyacucho[Chiclayo] = "Lima,null";
		VAyacucho[Iquitos] = "Lima,null";
		VAyacucho[Piura] = "Lima,null";
		VAyacucho[Talara] = "Lima,null";
		VAyacucho[Tumbes] = "Lima,null";
		VAyacucho[Cusco] = "Lima,null";
		

		VCusco[Santiago] = "Lima,null";
		VCusco[Quito] = "Lima,null";
		VCusco[Guayaquil] = "null,Lima-Quito";
		VCusco[BuenosAires] = "Lima,null";
		VCusco[Iquique] = "null,Lima-Santiago";
		VCusco[Cordoba] = "Lima,Lima-Buenos Aires";
		VCusco[SantaCruz] = "Lima,null";
		VCusco[SaoPaulo] = "Lima,null";
		VCusco[Mendoza] = "null,Lima-Santiago";
		VCusco[Montevideo] = "Lima,null";
		VCusco[RioDeJaneiro] = "Lima,null";
		VCusco[Bogota] = "Lima,Lima-Quito";
		VCusco[CiudadDeMexico] = "Lima,null";
		VCusco[Pucallpa] = "Lima,null";
		VCusco[Ayacucho] = "Lima,null";
		VCusco[PuertoMaldonado] = "Lima,null";
		VCusco[Juliaca] = "Lima,null";
		VCusco[Arequipa] = "Lima,null";
		VCusco[Tacna] = "Lima,null";
		VCusco[Tarapoto] = "Lima,null";
		VCusco[Cajamarca] = "Lima,null";
		VCusco[Trujillo] = "Lima,null";
		VCusco[Chiclayo] = "Lima,null";
		VCusco[Iquitos] = "Lima,null";
		VCusco[Piura] = "Lima,null";
		VCusco[Talara] = "Lima,null";
		VCusco[Tumbes] = "Lima,null";

		VPuertoMaldonado[Santiago] = "Lima,null";
		VPuertoMaldonado[Quito] = "Lima,null";
		VPuertoMaldonado[Guayaquil] = "null,Lima-Quito";
		VPuertoMaldonado[BuenosAires] = "Lima,null";
		VPuertoMaldonado[Iquique] = "null,Lima-Santiago";
		VPuertoMaldonado[Cordoba] = "Lima,Lima-Buenos Aires";
		VPuertoMaldonado[SantaCruz] = "Lima,null";
		VPuertoMaldonado[SaoPaulo] = "Lima,null";
		VPuertoMaldonado[Mendoza] = "null,Lima-Santiago";
		VPuertoMaldonado[Montevideo] = "Lima,null";
		VPuertoMaldonado[RioDeJaneiro] = "Lima,null";
		VPuertoMaldonado[Bogota] = "Lima,Lima-Quito";
		VPuertoMaldonado[CiudadDeMexico] = "Lima,null";
		VPuertoMaldonado[Pucallpa] = "Lima,null";
		VPuertoMaldonado[Ayacucho] = "Lima,null";
		VPuertoMaldonado[Cusco] = "Lima,null";
		VPuertoMaldonado[Tarapoto] = "Lima,null";
		VPuertoMaldonado[Tacna] = "Lima,null";
		VPuertoMaldonado[Trujillo] = "Lima,null";
		VPuertoMaldonado[Chiclayo] = "Lima,null";
		VPuertoMaldonado[Iquitos] = "Lima,null";
		VPuertoMaldonado[Piura] = "Lima,null";
		VPuertoMaldonado[Talara] = "Lima,null";
		VPuertoMaldonado[Tumbes] = "Lima,null";
		VPuertoMaldonado[Tacna] = "Lima,null";

		VJuliaca[Santiago] = "Lima,null";
		VJuliaca[Quito] = "Lima,null";
		VJuliaca[Guayaquil] = "null,Lima-Quito";
		VJuliaca[BuenosAires] = "Lima,null";
		VJuliaca[Iquique] = "null,Lima-Santiago";
		VJuliaca[Cordoba] = "Lima,Lima-Buenos Aires";
		VJuliaca[SantaCruz] = "Lima,null";
		VJuliaca[SaoPaulo] = "Lima,null";
		VJuliaca[Mendoza] = "null,Lima-Santiago";
		VJuliaca[Montevideo] = "Lima,null";
		VJuliaca[RioDeJaneiro] = "Lima,null";
		VJuliaca[Bogota] = "Lima,Lima-Quito";
		VJuliaca[CiudadDeMexico] = "Lima,null";
		VJuliaca[Pucallpa] = "Lima,null";
		VJuliaca[Ayacucho] = "Lima,null";
		VJuliaca[Cusco] = "Lima,null";
		VJuliaca[Tarapoto] = "Lima,null";
		VJuliaca[Tacna] = "Lima,null";
		VJuliaca[Trujillo] = "Lima,null";
		VJuliaca[Chiclayo] = "Lima,null";
		VJuliaca[Iquitos] = "Lima,null";
		VJuliaca[Piura] = "Lima,null";
		VJuliaca[Talara] = "Lima,null";
		VJuliaca[Tumbes] = "Lima,null";
		VJuliaca[Tacna] = "Lima,null";
		VJuliaca[PuertoMaldonado] = "Lima,null";

		VArequipa[Santiago] = "Lima,null";
		VArequipa[Quito] = "Lima,null";
		VArequipa[Guayaquil] = "null,Lima-Quito";
		VArequipa[BuenosAires] = "Lima,null";
		VArequipa[Iquique] = "null,Lima-Santiago";
		VArequipa[Cordoba] = "Lima,Lima-Buenos Aires";
		VArequipa[SantaCruz] = "Lima,null";
		VArequipa[SaoPaulo] = "Lima,null";
		VArequipa[Mendoza] = "null,Lima-Santiago";
		VArequipa[Montevideo] = "Lima,null";
		VArequipa[RioDeJaneiro] = "Lima,null";
		VArequipa[Bogota] = "Lima,Lima-Quito";
		VArequipa[CiudadDeMexico] = "Lima,null";
		VArequipa[Pucallpa] = "Lima,null";
		VArequipa[Ayacucho] = "Lima,null";
		VArequipa[Cusco] = "Lima,null";
		VArequipa[PuertoMaldonado] = "Lima,null";
		VArequipa[Juliaca] = "Lima,null";
		VArequipa[Tarapoto] = "Lima,null";
		VArequipa[Tacna] = "Lima,null";
		VArequipa[Trujillo] = "Lima,null";
		VArequipa[Chiclayo] = "Lima,null";
		VArequipa[Iquitos] = "Lima,null";
		VArequipa[Piura] = "Lima,null";
		VArequipa[Talara] = "Lima,null";
		VArequipa[Tumbes] = "Lima,null";
		VArequipa[Tacna] = "Lima,null";

		VTacna[Santiago] = "Lima,null";
		VTacna[Quito] = "Lima,null";
		VTacna[Guayaquil] = "null,Lima-Quito";
		VTacna[BuenosAires] = "Lima,null";
		VTacna[Iquique] = "null,Lima-Santiago";
		VTacna[Cordoba] = "Lima,Lima-Buenos Aires";
		VTacna[SantaCruz] = "Lima,null";
		VTacna[SaoPaulo] = "Lima,null";
		VTacna[Mendoza] = "null,Lima-Santiago";
		VTacna[Montevideo] = "Lima,null";
		VTacna[RioDeJaneiro] = "Lima,null";
		VTacna[Bogota] = "Lima,Lima-Quito";
		VTacna[CiudadDeMexico] = "Lima,null";
		VTacna[Cusco] = "Lima,null";
		VTacna[PuertoMaldonado] = "Lima,null";
		VTacna[Juliaca] = "Lima,null";
		VTacna[Arequipa] = "Lima,null";
		VTacna[Tarapoto] = "Lima,null";
		VTacna[Trujillo] = "Lima,null";
		VTacna[Chiclayo] = "Lima,null";
		VTacna[Iquitos] = "Lima,null";
		VTacna[Piura] = "Lima,null";
		VTacna[Talara] = "Lima,null";
		VTacna[Tumbes] = "Lima,null";

		VTarapoto[Santiago] = "Lima,null";
		VTarapoto[Quito] = "Lima,null";
		VTarapoto[Guayaquil] = "null,Lima-Quito";
		VTarapoto[BuenosAires] = "Lima,null";
		VTarapoto[Iquique] = "null,Lima-Santiago";
		VTarapoto[Cordoba] = "Lima,Lima-Buenos Aires";
		VTarapoto[SantaCruz] = "Lima,null";
		VTarapoto[SaoPaulo] = "Lima,null";
		VTarapoto[Mendoza] = "null,Lima-Santiago";
		VTarapoto[Montevideo] = "Lima,null";
		VTarapoto[RioDeJaneiro] = "Lima,null";
		VTarapoto[Bogota] = "Lima,Lima-Quito";
		VTarapoto[CiudadDeMexico] = "Lima,null";
		VTarapoto[Pucallpa] = "Lima,null";
		VTarapoto[Ayacucho] = "Lima,null";
		VTarapoto[Cusco] = "Lima,null";
		VTarapoto[PuertoMaldonado] = "Lima,null";
		VTarapoto[Juliaca] = "Lima,null";
		VTarapoto[Cajamarca] = "Lima,null";
		VTarapoto[Arequipa] = "Lima,null";
		VTarapoto[Tacna] = "Lima,null";
		VTarapoto[Trujillo] = "Lima,null";
		VTarapoto[Chiclayo] = "Lima,null";
		VTarapoto[Iquitos] = "Lima,null";
		VTarapoto[Piura] = "Lima,null";
		VTarapoto[Talara] = "Lima,null";
		VTarapoto[Tumbes] = "Lima,null";

		VCajamarca[Santiago] = "Lima,null";
		VCajamarca[Quito] = "Lima,null";
		VCajamarca[Guayaquil] = "null,Lima-Quito";
		VCajamarca[BuenosAires] = "Lima,null";
		VCajamarca[Iquique] = "null,Lima-Santiago";
		VCajamarca[Cordoba] = "Lima,Lima-Buenos Aires";
		VCajamarca[SantaCruz] = "Lima,null";
		VCajamarca[SaoPaulo] = "Lima,null";
		VCajamarca[Mendoza] = "null,Lima-Santiago";
		VCajamarca[Montevideo] = "Lima,null";
		VCajamarca[RioDeJaneiro] = "Lima,null";
		VCajamarca[Bogota] = "Lima,Lima-Quito";
		VCajamarca[CiudadDeMexico] = "Lima,null";
		VCajamarca[Pucallpa] = "Lima,null";
		VCajamarca[Ayacucho] = "Lima,null";
		VCajamarca[Cusco] = "Lima,null";
		VCajamarca[PuertoMaldonado] = "Lima,null";
		VCajamarca[Juliaca] = "Lima,null";
		VCajamarca[Arequipa] = "Lima,null";
		VCajamarca[Tacna] = "Lima,null";
		VCajamarca[Tarapoto] = "Lima,null";
		VCajamarca[Trujillo] = "Lima,null";
		VCajamarca[Chiclayo] = "Lima,null";
		VCajamarca[Iquitos] = "Lima,null";
		VCajamarca[Piura] = "Lima,null";
		VCajamarca[Talara] = "Lima,null";
		VCajamarca[Tumbes] = "Lima,null";

		VTrujillo[Santiago] = "Lima,null";
		VTrujillo[Quito] = "Lima,null";
		VTrujillo[Guayaquil] = "null,Lima-Quito";
		VTrujillo[BuenosAires] = "Lima,null";
		VTrujillo[Iquique] = "null,Lima-Santiago";
		VTrujillo[Cordoba] = "Lima,Lima-Buenos Aires";
		VTrujillo[SantaCruz] = "Lima,null";
		VTrujillo[SaoPaulo] = "Lima,null";
		VTrujillo[Mendoza] = "null,Lima-Santiago";
		VTrujillo[Montevideo] = "Lima,null";
		VTrujillo[RioDeJaneiro] = "Lima,null";
		VTrujillo[Bogota] = "Lima,Lima-Quito";
		VTrujillo[CiudadDeMexico] = "Lima,null";
		VTrujillo[Pucallpa] = "Lima,null";
		VTrujillo[Ayacucho] = "Lima,null";
		VTrujillo[Cusco] = "Lima,null";
		VTrujillo[PuertoMaldonado] = "Lima,null";
		VTrujillo[Juliaca] = "Lima,null";
		VTrujillo[Arequipa] = "Lima,null";
		VTrujillo[Tacna] = "Lima,null";
		VTrujillo[Tarapoto] = "Lima,null";
		VTrujillo[Cajamarca] = "Lima,null";
		VTrujillo[Chiclayo] = "Lima,null";
		VTrujillo[Iquitos] = "Lima,null";
		VTrujillo[Piura] = "Lima,null";
		VTrujillo[Talara] = "Lima,null";
		VTrujillo[Tumbes] = "Lima,null";

		VChiclayo[Santiago] = "Lima,null";
		VChiclayo[Quito] = "Lima,null";
		VChiclayo[Guayaquil] = "null,Lima-Quito";
		VChiclayo[BuenosAires] = "Lima,null";
		VChiclayo[Iquique] = "null,Lima-Santiago";
		VChiclayo[Cordoba] = "Lima,Lima-Buenos Aires";
		VChiclayo[SantaCruz] = "Lima,null";
		VChiclayo[SaoPaulo] = "Lima,null";
		VChiclayo[Mendoza] = "null,Lima-Santiago";
		VChiclayo[Montevideo] = "Lima,null";
		VChiclayo[RioDeJaneiro] = "Lima,null";
		VChiclayo[Bogota] = "Lima,Lima-Quito";
		VChiclayo[CiudadDeMexico] = "Lima,null";
		VChiclayo[Pucallpa] = "Lima,null";
		VChiclayo[Ayacucho] = "Lima,null";
		VChiclayo[Cusco] = "Lima,null";
		VChiclayo[PuertoMaldonado] = "Lima,null";
		VChiclayo[Juliaca] = "Lima,null";
		VChiclayo[Arequipa] = "Lima,null";
		VChiclayo[Tacna] = "Lima,null";
		VChiclayo[Tarapoto] = "Lima,null";
		VChiclayo[Cajamarca] = "Lima,null";
		VChiclayo[Trujillo] = "Lima,null";
		VChiclayo[Iquitos] = "Lima,null";
		VChiclayo[Piura] = "Lima,null";
		VChiclayo[Talara] = "Lima,null";
		VChiclayo[Tumbes] = "Lima,null";

		VIquitos[Santiago] = "Lima,null";
		VIquitos[Quito] = "Lima,null";
		VIquitos[Guayaquil] = "null,Lima-Quito";
		VIquitos[BuenosAires] = "Lima,null";
		VIquitos[Iquique] = "null,Lima-Santiago";
		VIquitos[Cordoba] = "Lima,Lima-Buenos Aires";
		VIquitos[SantaCruz] = "Lima,null";
		VIquitos[SaoPaulo] = "Lima,null";
		VIquitos[Mendoza] = "null,Lima-Santiago";
		VIquitos[Montevideo] = "Lima,null";
		VIquitos[RioDeJaneiro] = "Lima,null";
		VIquitos[Bogota] = "Lima,Lima-Quito";
		VIquitos[CiudadDeMexico] = "Lima,null";
		VIquitos[Pucallpa] = "Lima,null";
		VIquitos[Ayacucho] = "Lima,null";
		VIquitos[Cusco] = "Lima,null";
		VIquitos[PuertoMaldonado] = "Lima,null";
		VIquitos[Juliaca] = "Lima,null";
		VIquitos[Arequipa] = "Lima,null";
		VIquitos[Tacna] = "Lima,null";
		VIquitos[Tarapoto] = "Lima,null";
		VIquitos[Cajamarca] = "Lima,null";
		VIquitos[Trujillo] = "Lima,null";
		VIquitos[Chiclayo] = "Lima,null";
		VIquitos[Piura] = "Lima,null";
		VIquitos[Talara] = "Lima,null";
		VIquitos[Tumbes] = "Lima,null";

		VPiura[Santiago] = "Lima,null";
		VPiura[Quito] = "Lima,null";
		VPiura[Guayaquil] = "null,Lima-Quito";
		VPiura[BuenosAires] = "Lima,null";
		VPiura[Iquique] = "null,Lima-Santiago";
		VPiura[Cordoba] = "Lima,Lima-Buenos Aires";
		VPiura[SantaCruz] = "Lima,null";
		VPiura[SaoPaulo] = "Lima,null";
		VPiura[Mendoza] = "null,Lima-Santiago";
		VPiura[Montevideo] = "Lima,null";
		VPiura[RioDeJaneiro] = "Lima,null";
		VPiura[Bogota] = "Lima,Lima-Quito";
		VPiura[CiudadDeMexico] = "Lima,null";
		VPiura[Pucallpa] = "Lima,null";
		VPiura[Ayacucho] = "Lima,null";
		VPiura[Cusco] = "Lima,null";
		VPiura[PuertoMaldonado] = "Lima,null";
		VPiura[Juliaca] = "Lima,null";
		VPiura[Arequipa] = "Lima,null";
		VPiura[Tacna] = "Lima,null";
		VPiura[Tarapoto] = "Lima,null";
		VPiura[Cajamarca] = "Lima,null";
		VPiura[Trujillo] = "Lima,null";
		VPiura[Chiclayo] = "Lima,null";
		VPiura[Iquitos] = "Lima,null";
		VPiura[Talara] = "Lima,null";
		VPiura[Tumbes] = "Lima,null";

		VTalara[Santiago] = "Lima,null";
		VTalara[Quito] = "Lima,null";
		VTalara[Guayaquil] = "null,Lima-Quito";
		VTalara[BuenosAires] = "Lima,null";
		VTalara[Iquique] = "null,Lima-Santiago";
		VTalara[Cordoba] = "Lima,Lima-Buenos Aires";
		VTalara[SantaCruz] = "Lima,null";
		VTalara[SaoPaulo] = "Lima,null";
		VTalara[Mendoza] = "null,Lima-Santiago";
		VTalara[Montevideo] = "Lima,null";
		VTalara[RioDeJaneiro] = "Lima,null";
		VTalara[Bogota] = "Lima,Lima-Quito";
		VTalara[CiudadDeMexico] = "Lima,null";
		VTalara[Pucallpa] = "Lima,null";
		VTalara[Ayacucho] = "Lima,null";
		VTalara[Cusco] = "Lima,null";
		VTalara[PuertoMaldonado] = "Lima,null";
		VTalara[Juliaca] = "Lima,null";
		VTalara[Arequipa] = "Lima,null";
		VTalara[Tacna] = "Lima,null";
		VTalara[Tarapoto] = "Lima,null";
		VTalara[Cajamarca] = "Lima,null";
		VTalara[Trujillo] = "Lima,null";
		VTalara[Chiclayo] = "Lima,null";
		VTalara[Iquitos] = "Lima,null";
		VTalara[Piura] = "Lima,null";
		VTalara[Tumbes] = "Lima,null";

		VTumbes[Santiago] = "Lima,null";
		VTumbes[Quito] = "Lima,null";
		VTumbes[Guayaquil] = "null,Lima-Quito";
		VTumbes[BuenosAires] = "Lima,null";
		VTumbes[Iquique] = "null,Lima-Santiago";
		VTumbes[Cordoba] = "Lima,Lima-Buenos Aires";
		VTumbes[SantaCruz] = "Lima,null";
		VTumbes[SaoPaulo] = "Lima,null";
		VTumbes[Mendoza] = "null,Lima-Santiago";
		VTumbes[Montevideo] = "Lima,null";
		VTumbes[RioDeJaneiro] = "Lima,null";
		VTumbes[Bogota] = "Lima,Lima-Quito";
		VTumbes[CiudadDeMexico] = "Lima,null";
		VTumbes[Pucallpa] = "Lima,null";
		VTumbes[Ayacucho] = "Lima,null";
		VTumbes[Cusco] = "Lima,null";
		VTumbes[PuertoMaldonado] = "Lima,null";
		VTumbes[Juliaca] = "Lima,null";
		VTumbes[Arequipa] = "Lima,null";
		VTumbes[Tacna] = "Lima,null";
		VTumbes[Tarapoto] = "Lima,null";
		VTumbes[Cajamarca] = "Lima,null";
		VTumbes[Trujillo] = "Lima,null";
		VTumbes[Chiclayo] = "Lima,null";
		VTumbes[Iquitos] = "Lima,null";
		VTumbes[Piura] = "Lima,null";
		VTumbes[Talara] = "Lima,null";



		//Guardamos los datos en Vectores, vector el cual guarda vectores de strings:
		Vectores[0] = VLima;
		Vectores[1] = VSantiago;
		Vectores[2] = VQuito;
		Vectores[3] = VGuayaquil;
		Vectores[4] = VLaPaz;
		Vectores[5] = VBuenosAires;
		Vectores[6] = VIquique;
		Vectores[7] = VCordoba;
		Vectores[8] = VSantaCruz;
		Vectores[9] = VPortoAlegre;
		Vectores[10] = VAsuncion;
		Vectores[11] = VIguazu;
		Vectores[12] = VSaoPaulo;
		Vectores[13] = VBrasilia;
		Vectores[14] = VMendoza;
		Vectores[15] = VMontevideo;
		Vectores[16] = VRosario;
		Vectores[17] = VFlorianopolis;
		Vectores[18] = VCiudadDelEste;
		Vectores[19] = VCuritiba;
		Vectores[20] = VRioDeJaneiro;
		Vectores[21] = VBeloHorizonte;
		Vectores[22] = VPortoSeguro;
		Vectores[23] = VSalvador;
		Vectores[24] = VRecife;
		Vectores[25] = VFortaleza;
		Vectores[26] = VBelem;
		Vectores[27] = VManaos;
		Vectores[28] = VLeticia;
		Vectores[29] = VCali;
		Vectores[30] = VBogota;
		Vectores[31] = VMedellin;
		Vectores[32] = VPanama;
		Vectores[33] = VCartagena;
		Vectores[34] = VAruba;
		Vectores[35] = VCarajas;
		Vectores[36] = VVillaHermosa;
		Vectores[37] = VSanJuan;
		Vectores[38] = VPuntaCana;
		Vectores[39] = VAcapulco;
		Vectores[40] = VCiudadDeMexico;
		Vectores[41] = VVeracruz;
		Vectores[42] = VMerida;
		Vectores[43] = VCancun;
		Vectores[44] = VLaHabana;	
		Vectores[45] = VPuertoVallarta;
		Vectores[46] =	VGuadalajara;
		Vectores[47] =  VLeon;
		Vectores[48] = VMazatlan;
		Vectores[49] = VSanJoseCabo;
		Vectores[50] = VTorreon;
		Vectores[51] = VMonterrey;
		Vectores[52] = VMiami;
		Vectores[53] = VHermosillo;
		Vectores[54] = VHouston;
		Vectores[55] = VNewOrleans;
		Vectores[56] = VTampa;
		Vectores[57] = VOrlando;
		Vectores[58] = VTijuana;
		Vectores[59] = VPhoenix;
		Vectores[60] = VDallas;
		Vectores[61] = VAtlanta;
		Vectores[62] = VSanDiego;
		Vectores[63] = VLosAngeles;
		Vectores[64] = VLasVegas;
		Vectores[65] = VCharlotte;
		Vectores[66] = VRaleigh;
		Vectores[67] = VWashington;
		Vectores[68] = VBaltimore;
		Vectores[69] = VSanJose;
		Vectores[70] = VSanFrancisco;
		Vectores[71] = VReno;
		Vectores[72] = VDenver;
		Vectores[73] = VSaltLakeCity;
		Vectores[74] = VPortland;
		Vectores[75] = VSeattle;
		Vectores[76] = VVancouver;
		Vectores[77] = VCalgary;
		Vectores[78] = VPhiladelphia;
		Vectores[79] = VSaintLouis;
		Vectores[80] = VNewYork;
		Vectores[81] = VChicago;
		Vectores[82] = VDetroit;
		Vectores[83] = VMinneapolis;
		Vectores[84] = VToronto;
		Vectores[85] = VBoston;
		Vectores[86] = VMontreal;
		Vectores[87] = VPucallpa;
		Vectores[88] = VAyacucho;
		Vectores[89] = VCusco;
		Vectores[90] = VPuertoMaldonado;
		Vectores[91] = VJuliaca;
		Vectores[92] = VArequipa;
		Vectores[93] = VTacna;
		Vectores[94] = VTarapoto;
		Vectores[95] = VCajamarca;
		Vectores[96] = VTrujillo;
		Vectores[97] = VChiclayo;
		Vectores[98] = VIquitos;
		Vectores[99] = VPiura;
		Vectores[100] = VTalara;
		Vectores[101] = VTumbes;
	}
	~CBase(){}
	void IniciarString(string str[a]){
		for (int i = 0; i < a; i++){ str[i] = "null,null"; }
	}
	void IniciarPeru(string str[a]){ for (int i = 0; i < a; i++){ str[i] = "Lima,null";}}
};