//Librerias:
#include "Base_de_Datos.h"
//ENTREGAR
class DatosM:public CBase
{
public:
	int matrizR1[a][b];
	int matrizR2[a][b];
	int matrizR3[a][b];
	int matriz_caminos[a][b];
	void M_Matricez(int mat1[a][b], int mat2[a][b], int mat3[a][b]){
		for (int m = 0; m < a; m++){
			for (int i = 0; i < a; i++){
				int Mul = 1;
				int Suma = 0;
				for (int j = 0; j < b; j++){
					Mul = mat1[m][j] * mat2[j][m];
					Suma = Mul + Suma;
				}
				if (Suma>0) Suma = 1;
				mat3[m][i] = Suma;
			}
		}
	}
	void sumarFilasMatriz(int matriz[a][b], int indiceX, int indiceY){
		for (int i = 0; i < a; i++)
		{
			matriz[i][indiceY] = matriz[i][indiceY] + matriz[i][indiceX];
			if (matriz[i][indiceY]>0)
				matriz[i][indiceY] = 1;
		}
	}
	void HallarMatrizCaminos(int matriz[a][b]){
		int matriztemp[a] = { 0, 0, 0, 0, 0 };
		int cont = 0;
		for (int j = 0; j < a; j++)
		{
			while (true)
			{
				//ingreso valores, antes de modificar, de la fila "j" de la matriz de caminos
				for (int i = 0; i < a; i++)
				{
					matriztemp[i] = matriz[i][j];
				}
				for (int i = 0; i < b; i++)
				{
					/*cuando el valor de la posicion i,j es verdadera suma los valores de la fila con valor "i"
					a la fila con valor "j" con la funcion sumarFilasMatriz*/
					if (matriz[i][j] == 1)
					{
						sumarFilasMatriz(matriz, i, j);
					}
				}
				/*Igualo los valores de la matriz temporal con toda la fila "j" despues de utilizar la funcion
				sumarFilasMatriz*/
				for (int i = 0; i < a; i++)
				{
					if (matriztemp[i] == matriz[i][j])
						cont++;
				}
				/*Si todos los valores son iguales quiere decir que terminó de analizar la fila y
				saldrá del while, de lo contrario seguirá haciendo el mismo procedimiento hasta que los valores sean
				iguales*/
				if (cont == a)
					break;
				else
					cont = 0;
			}
	}
}
	void CopiarMatriz(int mat1[a][b],int mat2[a][b]){
		for (int i = 0; i < a; i++){
			for (int j = 0; j < b;j++){
				mat2[a][b] = mat1[a][b];
			}
		}
	}
	void SumarMatricez(int mat1[a][b], int mat2[a][b], int mat3[a][b]){
		for (int i = 0; i < a;i++){
			for (int j = 0; j < b;j++){
				mat3[i][j] = mat1[i][j] + mat2[i][j];
				if (mat3[i][j]>0) mat3[i][j] = 1;
			}
		}
	}

	DatosM(){
		//Inicializamos todo 1:
		RellenarVacios(matrizR1, 1);

		//COMPLETAMOS DATOS:
		//Incorporamos 0:...
		//DIRECTO:
		matrizR1[Lima][Iquique] = 0;
		matrizR1[Lima][PortoAlegre] = 0;
		matrizR1[Lima][Mendoza] = 0;
		matrizR1[Lima][Florianopolis] = 0;
		matrizR1[Lima][CiudadDelEste] = 0;
		matrizR1[Lima][Curitiba] = 0;
		matrizR1[Lima][RioDeJaneiro] = 0;
		matrizR1[Lima][BeloHorizonte] = 0;
		matrizR1[Lima][PortoSeguro] = 0;
		matrizR1[Lima][Salvador] = 0;
		matrizR1[Lima][Recife] = 0;
		matrizR1[Lima][Fortaleza] = 0;
		matrizR1[Lima][Belem] = 0;
		matrizR1[Lima][Manaos] = 0;
		matrizR1[Lima][Leticia] = 0;
		matrizR1[Lima][Cali] = 0;
		matrizR1[Lima][Medellin] = 0;
		matrizR1[Lima][Panama] = 0;
		matrizR1[Lima][Cartagena] = 0;
		matrizR1[Lima][Aruba] = 0;
		matrizR1[Lima][Carajas] = 0;
		matrizR1[Lima][VillaHermosa] = 0;
		matrizR1[Lima][SanJuan] = 0;
		matrizR1[Lima][Acapulco] = 0;
		matrizR1[Lima][Veracruz] = 0;
		matrizR1[Lima][Merida] = 0;
		matrizR1[Lima][PuertoVallarta] = 0;
		matrizR1[Lima][Guadalajara] = 0;
		matrizR1[Lima][Leon] = 0;
		matrizR1[Lima][Mazatlan] = 0;
		matrizR1[Lima][SanJoseCabo] = 0;
		matrizR1[Lima][Torreon] = 0;
		matrizR1[Lima][Monterrey] = 0;
		matrizR1[Lima][Hermosillo] = 0;
		matrizR1[Lima][Houston] = 0;
		matrizR1[Lima][NewOrleans] = 0;
		matrizR1[Lima][Tampa] = 0;
		matrizR1[Lima][Tijuana] = 0;
		matrizR1[Lima][Phoenix] = 0;
		matrizR1[Lima][Atlanta] = 0;
		matrizR1[Lima][SanDiego] = 0;
		matrizR1[Lima][LasVegas] = 0;
		matrizR1[Lima][Charlotte] = 0;
		matrizR1[Lima][Raleigh] = 0;
		matrizR1[Lima][Washington] = 0;
		matrizR1[Lima][Baltimore] = 0;
		matrizR1[Lima][SanJose] = 0;
		matrizR1[Lima][SanFrancisco] = 0;
		matrizR1[Lima][Reno] = 0;
		matrizR1[Lima][Denver] = 0;
		matrizR1[Lima][SaltLakeCity] = 0;
		matrizR1[Lima][Portland] = 0;
		matrizR1[Lima][Seattle] = 0;
		matrizR1[Lima][Vancouver] = 0;
		matrizR1[Lima][Calgary] = 0;
		matrizR1[Lima][Philadelphia] = 0;
		matrizR1[Lima][SaintLouis] = 0;
		matrizR1[Lima][NewYork] = 0;
		matrizR1[Lima][Chicago] = 0;
		matrizR1[Lima][Detroit] = 0;
		matrizR1[Lima][Minneapolis] = 0;
		matrizR1[Lima][Toronto] = 0;
		matrizR1[Lima][Boston] = 0;
		matrizR1[Lima][Montreal] = 0;

		matrizR1[Santiago][Iguazu] = 0;
		matrizR1[Santiago][Brasilia] = 0;
		matrizR1[Santiago][Rosario] = 0;
		matrizR1[Santiago][Florianopolis] = 0;
		matrizR1[Santiago][CiudadDelEste] = 0;
		matrizR1[Santiago][Curitiba] = 0;
		matrizR1[Santiago][BeloHorizonte] = 0;
		matrizR1[Santiago][PortoSeguro] = 0;
		matrizR1[Santiago][Salvador] = 0;
		matrizR1[Santiago][Recife] = 0;
		matrizR1[Santiago][Fortaleza] = 0;
		matrizR1[Santiago][Belem] = 0;
		matrizR1[Santiago][Manaos] = 0;
		matrizR1[Santiago][Leticia] = 0;
		matrizR1[Santiago][Cali] = 0;
		matrizR1[Santiago][Medellin] = 0;
		matrizR1[Santiago][Panama] = 0;
		matrizR1[Santiago][Cartagena] = 0;
		matrizR1[Santiago][Aruba] = 0;
		matrizR1[Santiago][Carajas] = 0;
		matrizR1[Santiago][VillaHermosa] = 0;
		matrizR1[Santiago][SanJuan] = 0;
		matrizR1[Santiago][PuntaCana] = 0;
		matrizR1[Santiago][Acapulco] = 0;
		matrizR1[Santiago][Veracruz] = 0;
		matrizR1[Santiago][Merida] = 0;
		matrizR1[Santiago][Cancun] = 0;
		matrizR1[Santiago][LaHabana] = 0;

		matrizR1[Santiago][PuertoVallarta] = 0;
		matrizR1[Santiago][Guadalajara] = 0;
		matrizR1[Santiago][Leon] = 0;
		matrizR1[Santiago][Mazatlan] = 0;
		matrizR1[Santiago][SanJoseCabo] = 0;
		matrizR1[Santiago][Torreon] = 0;
		matrizR1[Santiago][Monterrey] = 0;
		matrizR1[Santiago][Hermosillo] = 0;
		matrizR1[Santiago][Houston] = 0;
		matrizR1[Santiago][NewOrleans] = 0;
		matrizR1[Santiago][Tampa] = 0;
		matrizR1[Santiago][Tijuana] = 0;
		matrizR1[Santiago][Phoenix] = 0;
		matrizR1[Santiago][Dallas] = 0;
		matrizR1[Santiago][Atlanta] = 0;
		matrizR1[Santiago][SanDiego] = 0;
		matrizR1[Santiago][LasVegas] = 0;
		matrizR1[Santiago][Charlotte] = 0;
		matrizR1[Santiago][Raleigh] = 0;
		matrizR1[Santiago][Washington] = 0;
		matrizR1[Santiago][Baltimore] = 0;
		matrizR1[Santiago][SanJose] = 0;
		matrizR1[Santiago][SanFrancisco] = 0;
		matrizR1[Santiago][Reno] = 0;
		matrizR1[Santiago][Denver] = 0;
		matrizR1[Santiago][SaltLakeCity] = 0;
		matrizR1[Santiago][Portland] = 0;
		matrizR1[Santiago][Seattle] = 0;
		matrizR1[Santiago][Vancouver] = 0;
		matrizR1[Santiago][Calgary] = 0;
		matrizR1[Santiago][Philadelphia] = 0;
		matrizR1[Santiago][SaintLouis] = 0;
		matrizR1[Santiago][Chicago] = 0;
		matrizR1[Santiago][Detroit] = 0;
		matrizR1[Santiago][Minneapolis] = 0;
		matrizR1[Santiago][Toronto] = 0;
		matrizR1[Santiago][Boston] = 0;
		matrizR1[Santiago][Montreal] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Santiago][i] = 0;
		}

		matrizR1[Quito][LaPaz] = 0;
		matrizR1[Quito][Iquique] = 0;
		matrizR1[Quito][SantaCruz] = 0;
		matrizR1[Quito][PortoAlegre] = 0;
		matrizR1[Quito][Asuncion] = 0;
		matrizR1[Quito][Iguazu] = 0;
		matrizR1[Quito][SaoPaulo] = 0;
		matrizR1[Quito][Brasilia] = 0;
		matrizR1[Quito][Mendoza] = 0;
		matrizR1[Quito][Montevideo] = 0;
		matrizR1[Quito][Rosario] = 0;
		matrizR1[Quito][Florianopolis] = 0;
		matrizR1[Quito][CiudadDelEste] = 0;
		matrizR1[Quito][Curitiba] = 0;
		matrizR1[Quito][RioDeJaneiro] = 0;
		matrizR1[Quito][BeloHorizonte] = 0;
		matrizR1[Quito][PortoSeguro] = 0;
		matrizR1[Quito][Salvador] = 0;
		matrizR1[Quito][Recife] = 0;
		matrizR1[Quito][Fortaleza] = 0;
		matrizR1[Quito][Belem] = 0;
		matrizR1[Quito][Manaos] = 0;
		matrizR1[Quito][Leticia] = 0;
		matrizR1[Quito][Cali] = 0;
		matrizR1[Quito][Bogota] = 0;
		matrizR1[Quito][Medellin] = 0;
		matrizR1[Quito][Panama] = 0;
		matrizR1[Quito][Cartagena] = 0;
		matrizR1[Quito][Aruba] = 0;
		matrizR1[Quito][Carajas] = 0;
		matrizR1[Quito][VillaHermosa] = 0;
		matrizR1[Quito][SanJuan] = 0;
		matrizR1[Quito][PuntaCana] = 0;
		matrizR1[Quito][Acapulco] = 0;
		matrizR1[Quito][CiudadDeMexico] = 0;
		matrizR1[Quito][Veracruz] = 0;
		matrizR1[Quito][Merida] = 0;
		matrizR1[Quito][Cancun] = 0;
		matrizR1[Quito][LaHabana] = 0;

		matrizR1[Quito][PuertoVallarta] = 0;
		matrizR1[Quito][Guadalajara] = 0;
		matrizR1[Quito][Mazatlan] = 0;
		matrizR1[Quito][SanJoseCabo] = 0;
		matrizR1[Quito][Torreon] = 0;
		matrizR1[Quito][Monterrey] = 0;
		matrizR1[Quito][Hermosillo] = 0;
		matrizR1[Quito][Houston] = 0;
		matrizR1[Quito][NewOrleans] = 0;
		matrizR1[Quito][Tampa] = 0;
		matrizR1[Quito][Orlando] = 0;
		matrizR1[Quito][Tijuana] = 0;
		matrizR1[Quito][Phoenix] = 0;
		matrizR1[Quito][Dallas] = 0;
		matrizR1[Quito][Atlanta] = 0;
		matrizR1[Quito][SanDiego] = 0;
		matrizR1[Quito][LosAngeles] = 0;
		matrizR1[Quito][LasVegas] = 0;
		matrizR1[Quito][Charlotte] = 0;
		matrizR1[Quito][Raleigh] = 0;
		matrizR1[Quito][Washington] = 0;
		matrizR1[Quito][Baltimore] = 0;
		matrizR1[Quito][SanJose] = 0;
		matrizR1[Quito][SanFrancisco] = 0;
		matrizR1[Quito][Reno] = 0;
		matrizR1[Quito][Denver] = 0;
		matrizR1[Quito][SaltLakeCity] = 0;
		matrizR1[Quito][Portland] = 0;
		matrizR1[Quito][Seattle] = 0;
		matrizR1[Quito][Vancouver] = 0;
		matrizR1[Quito][Calgary] = 0;
		matrizR1[Quito][Philadelphia] = 0;
		matrizR1[Quito][SaintLouis] = 0;
		matrizR1[Quito][NewYork] = 0;
		matrizR1[Quito][Chicago] = 0;
		matrizR1[Quito][Detroit] = 0;
		matrizR1[Quito][Minneapolis] = 0;
		matrizR1[Quito][Toronto] = 0;
		matrizR1[Quito][Boston] = 0;
		matrizR1[Quito][Montreal] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Quito][i] = 0;
		}

		matrizR1[Guayaquil][Iquique] = 0;
		matrizR1[Guayaquil][Cordoba] = 0;
		matrizR1[Guayaquil][SantaCruz] = 0;
		matrizR1[Guayaquil][PortoAlegre] = 0;
		matrizR1[Guayaquil][Asuncion] = 0;
		matrizR1[Guayaquil][Iguazu] = 0;
		matrizR1[Guayaquil][SaoPaulo] = 0;
		matrizR1[Guayaquil][Brasilia] = 0;
		matrizR1[Guayaquil][Mendoza] = 0;
		matrizR1[Guayaquil][Montevideo] = 0;
		matrizR1[Guayaquil][Rosario] = 0;
		matrizR1[Guayaquil][Florianopolis] = 0;
		matrizR1[Guayaquil][CiudadDelEste] = 0;
		matrizR1[Guayaquil][Curitiba] = 0;
		matrizR1[Guayaquil][RioDeJaneiro] = 0;
		matrizR1[Guayaquil][BeloHorizonte] = 0;
		matrizR1[Guayaquil][PortoSeguro] = 0;
		matrizR1[Guayaquil][Salvador] = 0;
		matrizR1[Guayaquil][Recife] = 0;
		matrizR1[Guayaquil][Fortaleza] = 0;
		matrizR1[Guayaquil][Belem] = 0;
		matrizR1[Guayaquil][Manaos] = 0;
		matrizR1[Guayaquil][Leticia] = 0;
		matrizR1[Guayaquil][Cali] = 0;
		matrizR1[Guayaquil][Bogota] = 0;
		matrizR1[Guayaquil][Medellin] = 0;
		matrizR1[Guayaquil][Panama] = 0;
		matrizR1[Guayaquil][Cartagena] = 0;
		matrizR1[Guayaquil][Aruba] = 0;
		matrizR1[Guayaquil][Carajas] = 0;
		matrizR1[Guayaquil][VillaHermosa] = 0;
		matrizR1[Guayaquil][SanJuan] = 0;
		matrizR1[Guayaquil][PuntaCana] = 0;
		matrizR1[Guayaquil][Acapulco] = 0;
		matrizR1[Guayaquil][CiudadDeMexico] = 0;
		matrizR1[Guayaquil][Veracruz] = 0;
		matrizR1[Guayaquil][Merida] = 0;
		matrizR1[Guayaquil][Cancun] = 0;
		matrizR1[Guayaquil][LaHabana] = 0;

		matrizR1[Guayaquil][PuertoVallarta] = 0;
		matrizR1[Guayaquil][Guadalajara] = 0;
		matrizR1[Guayaquil][Leon] = 0;
		matrizR1[Guayaquil][Mazatlan] = 0;
		matrizR1[Guayaquil][SanJoseCabo] = 0;
		matrizR1[Guayaquil][Torreon] = 0;
		matrizR1[Guayaquil][Monterrey] = 0;
		matrizR1[Guayaquil][Miami] = 0;
		matrizR1[Guayaquil][Hermosillo] = 0;
		matrizR1[Guayaquil][Houston] = 0;
		matrizR1[Guayaquil][NewOrleans] = 0;
		matrizR1[Guayaquil][Tampa] = 0;
		matrizR1[Guayaquil][Orlando] = 0;
		matrizR1[Guayaquil][Tijuana] = 0;
		matrizR1[Guayaquil][Phoenix] = 0;
		matrizR1[Guayaquil][Dallas] = 0;
		matrizR1[Guayaquil][Atlanta] = 0;
		matrizR1[Guayaquil][SanDiego] = 0;
		matrizR1[Guayaquil][LosAngeles] = 0;
		matrizR1[Guayaquil][Cancun] = 0;
		matrizR1[Guayaquil][LasVegas] = 0;
		matrizR1[Guayaquil][Charlotte] = 0;
		matrizR1[Guayaquil][Raleigh] = 0;
		matrizR1[Guayaquil][Washington] = 0;
		matrizR1[Guayaquil][Baltimore] = 0;
		matrizR1[Guayaquil][SanJose] = 0;
		matrizR1[Guayaquil][SanFrancisco] = 0;
		matrizR1[Guayaquil][Reno] = 0;
		matrizR1[Guayaquil][Denver] = 0;
		matrizR1[Guayaquil][SaltLakeCity] = 0;
		matrizR1[Guayaquil][Portland] = 0;
		matrizR1[Guayaquil][Seattle] = 0;
		matrizR1[Guayaquil][Vancouver] = 0;
		matrizR1[Guayaquil][Calgary] = 0;
		matrizR1[Guayaquil][Philadelphia] = 0;
		matrizR1[Guayaquil][SaintLouis] = 0;
		matrizR1[Guayaquil][Chicago] = 0;
		matrizR1[Guayaquil][Detroit] = 0;
		matrizR1[Guayaquil][Minneapolis] = 0;
		matrizR1[Guayaquil][Toronto] = 0;
		matrizR1[Guayaquil][Boston] = 0;
		matrizR1[Guayaquil][Montreal] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Guayaquil][i] = 0;
		}

		matrizR1[LaPaz][Quito] = 0;
		matrizR1[LaPaz][Guayaquil] = 0;
		matrizR1[LaPaz][BuenosAires] = 0;
		matrizR1[LaPaz][Iquique] = 0;
		matrizR1[LaPaz][Cordoba] = 0;
		matrizR1[LaPaz][SantaCruz] = 0;
		matrizR1[LaPaz][PortoAlegre] = 0;
		matrizR1[LaPaz][Asuncion] = 0;
		matrizR1[LaPaz][Iguazu] = 0;
		matrizR1[LaPaz][SaoPaulo] = 0;
		matrizR1[LaPaz][Brasilia] = 0;
		matrizR1[LaPaz][Mendoza] = 0;
		matrizR1[LaPaz][Montevideo] = 0;
		matrizR1[LaPaz][Rosario] = 0;
		matrizR1[LaPaz][Florianopolis] = 0;
		matrizR1[LaPaz][CiudadDelEste] = 0;
		matrizR1[LaPaz][Curitiba] = 0;
		matrizR1[LaPaz][RioDeJaneiro] = 0;
		matrizR1[LaPaz][BeloHorizonte] = 0;
		matrizR1[LaPaz][PortoSeguro] = 0;
		matrizR1[LaPaz][Salvador] = 0;
		matrizR1[LaPaz][Recife] = 0;
		matrizR1[LaPaz][Fortaleza] = 0;
		matrizR1[LaPaz][Belem] = 0;
		matrizR1[LaPaz][Manaos] = 0;
		matrizR1[LaPaz][Leticia] = 0;
		matrizR1[LaPaz][Cali] = 0;
		matrizR1[LaPaz][Bogota] = 0;
		matrizR1[LaPaz][Medellin] = 0;
		matrizR1[LaPaz][Panama] = 0;
		matrizR1[LaPaz][Cartagena] = 0;
		matrizR1[LaPaz][Aruba] = 0;
		matrizR1[LaPaz][Carajas] = 0;
		matrizR1[LaPaz][VillaHermosa] = 0;
		matrizR1[LaPaz][SanJuan] = 0;
		matrizR1[LaPaz][PuntaCana] = 0;
		matrizR1[LaPaz][Acapulco] = 0;
		matrizR1[LaPaz][CiudadDeMexico] = 0;
		matrizR1[LaPaz][Veracruz] = 0;
		matrizR1[LaPaz][Merida] = 0;
		matrizR1[LaPaz][Cancun] = 0;
		matrizR1[LaPaz][LaHabana] = 0;
		
		matrizR1[LaPaz][PuertoVallarta] = 0;
		matrizR1[LaPaz][Guadalajara] = 0;
		matrizR1[LaPaz][Leon] = 0;
		matrizR1[LaPaz][Mazatlan] = 0;
		matrizR1[LaPaz][SanJoseCabo] = 0;
		matrizR1[LaPaz][Torreon] = 0;
		matrizR1[LaPaz][Monterrey] = 0;
		matrizR1[LaPaz][Miami] = 0;
		matrizR1[LaPaz][Hermosillo] = 0;
		matrizR1[LaPaz][Houston] = 0;
		matrizR1[LaPaz][NewOrleans] = 0;
		matrizR1[LaPaz][Tampa] = 0;
		matrizR1[LaPaz][Orlando] = 0;
		matrizR1[LaPaz][Tijuana] = 0;
		matrizR1[LaPaz][Phoenix] = 0;
		matrizR1[LaPaz][Dallas] = 0;
		matrizR1[LaPaz][Atlanta] = 0;
		matrizR1[LaPaz][SanDiego] = 0;
		matrizR1[LaPaz][LosAngeles] = 0;
		matrizR1[LaPaz][LasVegas] = 0;
		matrizR1[LaPaz][Charlotte] = 0;
		matrizR1[LaPaz][Raleigh] = 0;
		matrizR1[LaPaz][Washington] = 0;
		matrizR1[LaPaz][Baltimore] = 0;
		matrizR1[LaPaz][SanJose] = 0;
		matrizR1[LaPaz][SanFrancisco] = 0;
		matrizR1[LaPaz][Reno] = 0;
		matrizR1[LaPaz][Denver] = 0;
		matrizR1[LaPaz][SaltLakeCity] = 0;
		matrizR1[LaPaz][Portland] = 0;
		matrizR1[LaPaz][Seattle] = 0;
		matrizR1[LaPaz][Vancouver] = 0;
		matrizR1[LaPaz][Calgary] = 0;
		matrizR1[LaPaz][Philadelphia] = 0;
		matrizR1[LaPaz][SaintLouis] = 0;
		matrizR1[LaPaz][NewYork] = 0;
		matrizR1[LaPaz][Chicago] = 0;
		matrizR1[LaPaz][Detroit] = 0;
		matrizR1[LaPaz][Minneapolis] = 0;
		matrizR1[LaPaz][Toronto] = 0;
		matrizR1[LaPaz][Boston] = 0;
		matrizR1[LaPaz][Montreal] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[LaPaz][i] = 0;
		}

		matrizR1[BuenosAires][Guayaquil] = 0;
		matrizR1[BuenosAires][LaPaz] = 0;
		matrizR1[BuenosAires][Iquique] = 0;
		matrizR1[BuenosAires][SantaCruz] = 0;
		matrizR1[BuenosAires][PortoAlegre] = 0;
		matrizR1[BuenosAires][Montevideo] = 0;
		matrizR1[BuenosAires][Rosario] = 0;
		matrizR1[BuenosAires][Florianopolis] = 0;
		matrizR1[BuenosAires][CiudadDelEste] = 0;
		matrizR1[BuenosAires][Curitiba] = 0;
		matrizR1[BuenosAires][BeloHorizonte] = 0;
		matrizR1[BuenosAires][PortoSeguro] = 0;
		matrizR1[BuenosAires][Salvador] = 0;
		matrizR1[BuenosAires][Recife] = 0;
		matrizR1[BuenosAires][Fortaleza] = 0;
		matrizR1[BuenosAires][Belem] = 0;
		matrizR1[BuenosAires][Manaos] = 0;
		matrizR1[BuenosAires][Leticia] = 0;
		matrizR1[BuenosAires][Cali] = 0;
		matrizR1[BuenosAires][Bogota] = 0;
		matrizR1[BuenosAires][Medellin] = 0;
		matrizR1[BuenosAires][Panama] = 0;
		matrizR1[BuenosAires][Cartagena] = 0;
		matrizR1[BuenosAires][Aruba] = 0;
		matrizR1[BuenosAires][Carajas] = 0;
		matrizR1[BuenosAires][VillaHermosa] = 0;
		matrizR1[BuenosAires][SanJuan] = 0;
		matrizR1[BuenosAires][PuntaCana] = 0;
		matrizR1[BuenosAires][Acapulco] = 0;
		matrizR1[BuenosAires][CiudadDeMexico] = 0;
		matrizR1[BuenosAires][Veracruz] = 0;
		matrizR1[BuenosAires][Merida] = 0;
		matrizR1[BuenosAires][Cancun] = 0;
		matrizR1[BuenosAires][LaHabana] = 0;

		matrizR1[BuenosAires][PuertoVallarta] = 0;
		matrizR1[BuenosAires][Guadalajara] = 0;
		matrizR1[BuenosAires][Leon] = 0;
		matrizR1[BuenosAires][Mazatlan] = 0;
		matrizR1[BuenosAires][SanJoseCabo] = 0;
		matrizR1[BuenosAires][Torreon] = 0;
		matrizR1[BuenosAires][Monterrey] = 0;
		matrizR1[BuenosAires][Hermosillo] = 0;
		matrizR1[BuenosAires][Houston] = 0;
		matrizR1[BuenosAires][NewOrleans] = 0;
		matrizR1[BuenosAires][Tampa] = 0;
		matrizR1[BuenosAires][Orlando] = 0;
		matrizR1[BuenosAires][Tijuana] = 0;
		matrizR1[BuenosAires][Phoenix] = 0;
		matrizR1[BuenosAires][Atlanta] = 0;
		matrizR1[BuenosAires][SanDiego] = 0;
		matrizR1[BuenosAires][LosAngeles] = 0;
		matrizR1[BuenosAires][LasVegas] = 0;
		matrizR1[BuenosAires][Charlotte] = 0;
		matrizR1[BuenosAires][Raleigh] = 0;
		matrizR1[BuenosAires][Washington] = 0;
		matrizR1[BuenosAires][Baltimore] = 0;
		matrizR1[BuenosAires][SanJose] = 0;
		matrizR1[BuenosAires][SanFrancisco] = 0;
		matrizR1[BuenosAires][Reno] = 0;
		matrizR1[BuenosAires][Denver] = 0;
		matrizR1[BuenosAires][SaltLakeCity] = 0;
		matrizR1[BuenosAires][Portland] = 0;
		matrizR1[BuenosAires][Seattle] = 0;
		matrizR1[BuenosAires][Vancouver] = 0;
		matrizR1[BuenosAires][Calgary] = 0;
		matrizR1[BuenosAires][Philadelphia] = 0;
		matrizR1[BuenosAires][SaintLouis] = 0;
		matrizR1[BuenosAires][Chicago] = 0;
		matrizR1[BuenosAires][Detroit] = 0;
		matrizR1[BuenosAires][Minneapolis] = 0;
		matrizR1[BuenosAires][Toronto] = 0;
		matrizR1[BuenosAires][Boston] = 0;
		matrizR1[BuenosAires][Montreal] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[BuenosAires][i] = 0;
		}

		matrizR1[Iquique][Lima] = 0;
		matrizR1[Iquique][Quito] = 0;
		matrizR1[Iquique][Guayaquil] = 0;
		matrizR1[Iquique][LaPaz] = 0;
		matrizR1[Iquique][BuenosAires] = 0;
		matrizR1[Iquique][PortoAlegre] = 0;
		matrizR1[Iquique][Cordoba] = 0;
		matrizR1[Iquique][Asuncion] = 0;
		matrizR1[Iquique][Iguazu] = 0;
		matrizR1[Iquique][Brasilia] = 0;
		matrizR1[Iquique][SaoPaulo] = 0;
		matrizR1[Iquique][PortoAlegre] = 0;
		matrizR1[Iquique][Brasilia] = 0;
		matrizR1[Iquique][Mendoza] = 0;
		matrizR1[Iquique][Montevideo] = 0;
		matrizR1[Iquique][Rosario] = 0;
		matrizR1[Iquique][Florianopolis] = 0;
		matrizR1[Iquique][CiudadDelEste] = 0;
		matrizR1[Iquique][Curitiba] = 0;
		matrizR1[Iquique][RioDeJaneiro] = 0;
		matrizR1[Iquique][BeloHorizonte] = 0;
		matrizR1[Iquique][PortoSeguro] = 0;
		matrizR1[Iquique][Salvador] = 0;
		matrizR1[Iquique][Recife] = 0;
		matrizR1[Iquique][Fortaleza] = 0;
		matrizR1[Iquique][Belem] = 0;
		matrizR1[Iquique][Manaos] = 0;
		matrizR1[Iquique][Leticia] = 0;
		matrizR1[Iquique][Cali] = 0;
		matrizR1[Iquique][Bogota] = 0;
		matrizR1[Iquique][Medellin] = 0;
		matrizR1[Iquique][Panama] = 0;
		matrizR1[Iquique][Cartagena] = 0;
		matrizR1[Iquique][Aruba] = 0;
		matrizR1[Iquique][Carajas] = 0;
		matrizR1[Iquique][VillaHermosa] = 0;
		matrizR1[Iquique][SanJuan] = 0;
		matrizR1[Iquique][PuntaCana] = 0;
		matrizR1[Iquique][Acapulco] = 0;
		matrizR1[Iquique][CiudadDeMexico] = 0;
		matrizR1[Iquique][Veracruz] = 0;
		matrizR1[Iquique][Merida] = 0;
		matrizR1[Iquique][Cancun] = 0;
		matrizR1[Iquique][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Iquique][i] = 0;
		}

		matrizR1[Cordoba][Quito] = 0;
		matrizR1[Cordoba][Guayaquil] = 0;
		matrizR1[Cordoba][SantaCruz] = 0;
		matrizR1[Cordoba][PortoAlegre] = 0;
		matrizR1[Cordoba][LaPaz] = 0;
		matrizR1[Cordoba][Iquique] = 0;
		matrizR1[Cordoba][Asuncion] = 0;
		matrizR1[Cordoba][Iguazu] = 0;
		matrizR1[Cordoba][Brasilia] = 0;
		matrizR1[Cordoba][Mendoza] = 0;
		matrizR1[Cordoba][Montevideo] = 0;
		matrizR1[Cordoba][Rosario] = 0;
		matrizR1[Cordoba][Florianopolis] = 0;
		matrizR1[Cordoba][CiudadDelEste] = 0;
		matrizR1[Cordoba][Curitiba] = 0;
		matrizR1[Cordoba][RioDeJaneiro] = 0;
		matrizR1[Cordoba][BeloHorizonte] = 0;
		matrizR1[Cordoba][PortoSeguro] = 0;
		matrizR1[Cordoba][Salvador] = 0;
		matrizR1[Cordoba][Recife] = 0;
		matrizR1[Cordoba][Fortaleza] = 0;
		matrizR1[Cordoba][Belem] = 0;
		matrizR1[Cordoba][Manaos] = 0;
		matrizR1[Cordoba][Leticia] = 0;
		matrizR1[Cordoba][Cali] = 0;
		matrizR1[Cordoba][Bogota] = 0;
		matrizR1[Cordoba][Medellin] = 0;
		matrizR1[Cordoba][Panama] = 0;
		matrizR1[Cordoba][Cartagena] = 0;
		matrizR1[Cordoba][Aruba] = 0;
		matrizR1[Cordoba][Carajas] = 0;
		matrizR1[Cordoba][VillaHermosa] = 0;
		matrizR1[Cordoba][SanJuan] = 0;
		matrizR1[Cordoba][PuntaCana] = 0;
		matrizR1[Cordoba][Acapulco] = 0;
		matrizR1[Cordoba][CiudadDeMexico] = 0;
		matrizR1[Cordoba][Veracruz] = 0;
		matrizR1[Cordoba][Merida] = 0;
		matrizR1[Cordoba][Cancun] = 0;
		matrizR1[Cordoba][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Cordoba][i] = 0;
		}

		matrizR1[SantaCruz][LaPaz] = 0;
		matrizR1[SantaCruz][Santiago] = 0;
		matrizR1[SantaCruz][Quito] = 0;
		matrizR1[SantaCruz][Guayaquil] = 0;
		matrizR1[SantaCruz][BuenosAires] = 0;
		matrizR1[SantaCruz][PortoAlegre] = 0;
		matrizR1[SantaCruz][Asuncion] = 0;
		matrizR1[SantaCruz][Iguazu] = 0;
		matrizR1[SantaCruz][Brasilia] = 0;
		matrizR1[SantaCruz][Iquique] = 0;
		matrizR1[SantaCruz][Cordoba] = 0;
		matrizR1[SantaCruz][SaoPaulo] = 0;
		matrizR1[SantaCruz][Mendoza] = 0;
		matrizR1[SantaCruz][Montevideo] = 0;
		matrizR1[SantaCruz][Rosario] = 0;
		matrizR1[SantaCruz][Florianopolis] = 0;
		matrizR1[SantaCruz][CiudadDelEste] = 0;
		matrizR1[SantaCruz][Curitiba] = 0;
		matrizR1[SantaCruz][RioDeJaneiro] = 0;
		matrizR1[SantaCruz][BeloHorizonte] = 0;
		matrizR1[SantaCruz][PortoSeguro] = 0;
		matrizR1[SantaCruz][Salvador] = 0;
		matrizR1[SantaCruz][Recife] = 0;
		matrizR1[SantaCruz][Fortaleza] = 0;
		matrizR1[SantaCruz][Belem] = 0;
		matrizR1[SantaCruz][Manaos] = 0;
		matrizR1[SantaCruz][Leticia] = 0;
		matrizR1[SantaCruz][Cali] = 0;
		matrizR1[SantaCruz][Bogota] = 0;
		matrizR1[SantaCruz][Medellin] = 0;
		matrizR1[SantaCruz][Panama] = 0;
		matrizR1[SantaCruz][Cartagena] = 0;
		matrizR1[SantaCruz][Aruba] = 0;
		matrizR1[SantaCruz][Carajas] = 0;
		matrizR1[SantaCruz][VillaHermosa] = 0;
		matrizR1[SantaCruz][SanJuan] = 0;
		matrizR1[SantaCruz][PuntaCana] = 0;
		matrizR1[SantaCruz][Acapulco] = 0;
		matrizR1[SantaCruz][CiudadDeMexico] = 0;
		matrizR1[SantaCruz][Veracruz] = 0;
		matrizR1[SantaCruz][Merida] = 0;
		matrizR1[SantaCruz][Cancun] = 0;
		matrizR1[SantaCruz][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[SantaCruz][i] = 0;
		}

		matrizR1[PortoAlegre][LaPaz] = 0;
		matrizR1[PortoAlegre][Lima] = 0;
		matrizR1[PortoAlegre][Santiago] = 0;
		matrizR1[PortoAlegre][Quito] = 0;
		matrizR1[PortoAlegre][Guayaquil] = 0;
		matrizR1[PortoAlegre][BuenosAires] = 0;
		matrizR1[PortoAlegre][Iquique] = 0;
		matrizR1[PortoAlegre][Cordoba] = 0;
		matrizR1[PortoAlegre][SantaCruz] = 0;
		matrizR1[PortoAlegre][Asuncion] = 0;
		matrizR1[PortoAlegre][Iguazu] = 0;
		matrizR1[PortoAlegre][Brasilia] = 0;
		matrizR1[PortoAlegre][Rosario] = 0;
		matrizR1[PortoAlegre][Florianopolis] = 0;
		matrizR1[PortoAlegre][CiudadDelEste] = 0;
		matrizR1[PortoAlegre][Curitiba] = 0;
		matrizR1[PortoAlegre][BeloHorizonte] = 0;
		matrizR1[PortoAlegre][PortoSeguro] = 0;
		matrizR1[PortoAlegre][Salvador] = 0;
		matrizR1[PortoAlegre][Recife] = 0;
		matrizR1[PortoAlegre][Fortaleza] = 0;
		matrizR1[PortoAlegre][Belem] = 0;
		matrizR1[PortoAlegre][Manaos] = 0;
		matrizR1[PortoAlegre][Leticia] = 0;
		matrizR1[PortoAlegre][Panama] = 0;
		matrizR1[PortoAlegre][Aruba] = 0;
		matrizR1[PortoAlegre][Carajas] = 0;
		matrizR1[PortoAlegre][SanJuan] = 0;
		matrizR1[PortoAlegre][Acapulco] = 0;
		matrizR1[PortoAlegre][Merida] = 0;
		matrizR1[PortoAlegre][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[PortoAlegre][i] = 0;
		}

		matrizR1[Asuncion][LaPaz] = 0;
		matrizR1[Asuncion][Quito] = 0;
		matrizR1[Asuncion][Guayaquil] = 0;
		matrizR1[Asuncion][SantaCruz] = 0;
		matrizR1[Asuncion][PortoAlegre] = 0;
		matrizR1[Asuncion][Iguazu] = 0;
		matrizR1[Asuncion][Brasilia] = 0;
		matrizR1[Asuncion][Iquique] = 0;
		matrizR1[Asuncion][Cordoba] = 0;
		matrizR1[Asuncion][Rosario] = 0;
		matrizR1[Asuncion][Florianopolis] = 0;
		matrizR1[Asuncion][CiudadDelEste] = 0;
		matrizR1[Asuncion][Curitiba] = 0;
		matrizR1[Asuncion][BeloHorizonte] = 0;
		matrizR1[Asuncion][PortoSeguro] = 0;
		matrizR1[Asuncion][Salvador] = 0;
		matrizR1[Asuncion][Recife] = 0;
		matrizR1[Asuncion][Fortaleza] = 0;
		matrizR1[Asuncion][Belem] = 0;
		matrizR1[Asuncion][Manaos] = 0;
		matrizR1[Asuncion][Leticia] = 0;
		matrizR1[Asuncion][Medellin] = 0;
		matrizR1[Asuncion][Panama] = 0;
		matrizR1[Asuncion][Aruba] = 0;
		matrizR1[Asuncion][Carajas] = 0;
		matrizR1[Asuncion][SanJuan] = 0;
		matrizR1[Asuncion][PuntaCana] = 0;
		matrizR1[Asuncion][Acapulco] = 0;
		matrizR1[Asuncion][Veracruz] = 0;
		matrizR1[Asuncion][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Asuncion][i] = 0;
		}

		matrizR1[Iguazu][LaPaz] = 0;
		matrizR1[Iguazu][Lima] = 0;
		matrizR1[Iguazu][Santiago] = 0;
		matrizR1[Iguazu][Quito] = 0;
		matrizR1[Iguazu][Guayaquil] = 0;
		matrizR1[Iguazu][SantaCruz] = 0;
		matrizR1[Iguazu][PortoAlegre] = 0;
		matrizR1[Iguazu][Asuncion] = 0;
		matrizR1[Iguazu][SaoPaulo] = 0;
		matrizR1[Iguazu][Brasilia] = 0;
		matrizR1[Iguazu][Iquique] = 0;
		matrizR1[Iguazu][Cordoba] = 0;
		matrizR1[Iguazu][Mendoza] = 0;
		matrizR1[Iguazu][Montevideo] = 0;
		matrizR1[Iguazu][Rosario] = 0;
		matrizR1[Iguazu][Florianopolis] = 0;
		matrizR1[Iguazu][CiudadDelEste] = 0;
		matrizR1[Iguazu][Curitiba] = 0;
		matrizR1[Iguazu][RioDeJaneiro] = 0;
		matrizR1[Iguazu][BeloHorizonte] = 0;
		matrizR1[Iguazu][PortoSeguro] = 0;
		matrizR1[Iguazu][Salvador] = 0;
		matrizR1[Iguazu][Recife] = 0;
		matrizR1[Iguazu][Fortaleza] = 0;
		matrizR1[Iguazu][Belem] = 0;
		matrizR1[Iguazu][Manaos] = 0;
		matrizR1[Iguazu][Leticia] = 0;
		matrizR1[Iguazu][Cali] = 0;
		matrizR1[Iguazu][Bogota] = 0;
		matrizR1[Iguazu][Medellin] = 0;
		matrizR1[Iguazu][Panama] = 0;
		matrizR1[Iguazu][Cartagena] = 0;
		matrizR1[Iguazu][Aruba] = 0;
		matrizR1[Iguazu][Carajas] = 0;
		matrizR1[Iguazu][VillaHermosa] = 0;
		matrizR1[Iguazu][SanJuan] = 0;
		matrizR1[Iguazu][PuntaCana] = 0;
		matrizR1[Iguazu][Acapulco] = 0;
		matrizR1[Iguazu][CiudadDeMexico] = 0;
		matrizR1[Iguazu][Veracruz] = 0;
		matrizR1[Iguazu][Merida] = 0;
		matrizR1[Iguazu][Cancun] = 0;
		matrizR1[Iguazu][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Iguazu][i] = 0;
		}

		matrizR1[SaoPaulo][Quito] = 0;
		matrizR1[SaoPaulo][Guayaquil] = 0;
		matrizR1[SaoPaulo][LaPaz] = 0;
		matrizR1[SaoPaulo][Iquique] = 0;
		matrizR1[SaoPaulo][SantaCruz] = 0;
		matrizR1[SaoPaulo][Iguazu] = 0;
		matrizR1[SaoPaulo][Mendoza] = 0;
		matrizR1[SaoPaulo][CiudadDelEste] = 0;
		matrizR1[SaoPaulo][PortoSeguro] = 0;
		matrizR1[SaoPaulo][Leticia] = 0;
		matrizR1[SaoPaulo][Cali] = 0;
		matrizR1[SaoPaulo][Medellin] = 0;
		matrizR1[SaoPaulo][Panama] = 0;
		matrizR1[SaoPaulo][Cartagena] = 0;
		matrizR1[SaoPaulo][Aruba] = 0;
		matrizR1[SaoPaulo][Carajas] = 0;
		matrizR1[SaoPaulo][VillaHermosa] = 0;
		matrizR1[SaoPaulo][SanJuan] = 0;
		matrizR1[SaoPaulo][PuntaCana] = 0;
		matrizR1[SaoPaulo][Acapulco] = 0;
		matrizR1[SaoPaulo][Veracruz] = 0;
		matrizR1[SaoPaulo][Merida] = 0;
		matrizR1[SaoPaulo][Cancun] = 0;
		matrizR1[SaoPaulo][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[SaoPaulo][i] = 0;
		}

		matrizR1[Brasilia][Lima] = 0;
		matrizR1[Brasilia][Santiago] = 0;
		matrizR1[Brasilia][Quito] = 0;
		matrizR1[Brasilia][Guayaquil] = 0;
		matrizR1[Brasilia][LaPaz] = 0;
		matrizR1[Brasilia][Iquique] = 0;
		matrizR1[Brasilia][SantaCruz] = 0;
		matrizR1[Brasilia][PortoAlegre] = 0;
		matrizR1[Brasilia][Asuncion] = 0;
		matrizR1[Brasilia][Iguazu] = 0;
		matrizR1[Brasilia][Cordoba] = 0;
		matrizR1[Brasilia][Mendoza] = 0;
		matrizR1[Brasilia][Montevideo] = 0;
		matrizR1[Brasilia][Rosario] = 0;
		matrizR1[Brasilia][Florianopolis] = 0;
		matrizR1[Brasilia][CiudadDelEste] = 0;
		matrizR1[Brasilia][Curitiba] = 0;
		matrizR1[Brasilia][BeloHorizonte] = 0;
		matrizR1[Brasilia][PortoSeguro] = 0;
		matrizR1[Brasilia][Salvador] = 0;
		matrizR1[Brasilia][Recife] = 0;
		matrizR1[Brasilia][Belem] = 0;
		matrizR1[Brasilia][Leticia] = 0;
		matrizR1[Brasilia][Cali] = 0;
		matrizR1[Brasilia][Bogota] = 0;
		matrizR1[Brasilia][Medellin] = 0;
		matrizR1[Brasilia][Panama] = 0;
		matrizR1[Brasilia][Cartagena] = 0;
		matrizR1[Brasilia][Aruba] = 0;
		matrizR1[Brasilia][Carajas] = 0;
		matrizR1[Brasilia][VillaHermosa] = 0;
		matrizR1[Brasilia][SanJuan] = 0;
		matrizR1[Brasilia][PuntaCana] = 0;
		matrizR1[Brasilia][Acapulco] = 0;
		matrizR1[Brasilia][CiudadDeMexico] = 0;
		matrizR1[Brasilia][Veracruz] = 0;
		matrizR1[Brasilia][Merida] = 0;
		matrizR1[Brasilia][Cancun] = 0;
		matrizR1[Brasilia][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Brasilia][i] = 0;
		}

		matrizR1[Mendoza][Lima] = 0;
		matrizR1[Mendoza][Quito] = 0;
		matrizR1[Mendoza][Guayaquil] = 0;
		matrizR1[Mendoza][LaPaz] = 0;
		matrizR1[Mendoza][Iquique] = 0;
		matrizR1[Mendoza][Cordoba] = 0;
		matrizR1[Mendoza][SantaCruz] = 0;
		matrizR1[Mendoza][PortoAlegre] = 0;
		matrizR1[Mendoza][Asuncion] = 0;
		matrizR1[Mendoza][Iguazu] = 0;
		matrizR1[Mendoza][SaoPaulo] = 0;
		matrizR1[Mendoza][Brasilia] = 0;
		matrizR1[Mendoza][Montevideo] = 0;
		matrizR1[Mendoza][Rosario] = 0;
		matrizR1[Mendoza][Florianopolis] = 0;
		matrizR1[Mendoza][CiudadDelEste] = 0;
		matrizR1[Mendoza][Curitiba] = 0;
		matrizR1[Mendoza][RioDeJaneiro] = 0;
		matrizR1[Mendoza][BeloHorizonte] = 0;
		matrizR1[Mendoza][PortoSeguro] = 0;
		matrizR1[Mendoza][Salvador] = 0;
		matrizR1[Mendoza][Recife] = 0;
		matrizR1[Mendoza][Fortaleza] = 0;
		matrizR1[Mendoza][Belem] = 0;
		matrizR1[Mendoza][Manaos] = 0;
		matrizR1[Mendoza][Leticia] = 0;
		matrizR1[Mendoza][Cali] = 0;
		matrizR1[Mendoza][Bogota] = 0;
		matrizR1[Mendoza][Medellin] = 0;
		matrizR1[Mendoza][Panama] = 0;
		matrizR1[Mendoza][Cartagena] = 0;
		matrizR1[Mendoza][Aruba] = 0;
		matrizR1[Mendoza][Carajas] = 0;
		matrizR1[Mendoza][VillaHermosa] = 0;
		matrizR1[Mendoza][SanJuan] = 0;
		matrizR1[Mendoza][PuntaCana] = 0;
		matrizR1[Mendoza][Acapulco] = 0;
		matrizR1[Mendoza][CiudadDeMexico] = 0;
		matrizR1[Mendoza][Veracruz] = 0;
		matrizR1[Mendoza][Merida] = 0;
		matrizR1[Mendoza][Cancun] = 0;
		matrizR1[Mendoza][LaHabana] = 0;

		matrizR1[Bogota][BuenosAires] = 0;
		matrizR1[Bogota][Iquique] = 0;
		matrizR1[Bogota][Cordoba] = 0;
		matrizR1[Bogota][SantaCruz] = 0;
		matrizR1[Bogota][PortoAlegre] = 0;
		matrizR1[Bogota][Asuncion] = 0;
		matrizR1[Bogota][Iguazu] = 0;
		matrizR1[Bogota][Quito] = 0;
		matrizR1[Bogota][Brasilia] = 0;
		matrizR1[Bogota][Mendoza] = 0;
		matrizR1[Bogota][Montevideo] = 0;
		matrizR1[Bogota][Rosario] = 0;
		matrizR1[Bogota][Florianopolis] = 0;
		matrizR1[Bogota][CiudadDelEste] = 0;
		matrizR1[Bogota][Curitiba] = 0;
		matrizR1[Bogota][RioDeJaneiro] = 0;
		matrizR1[Bogota][BeloHorizonte] = 0;
		matrizR1[Bogota][PortoSeguro] = 0;
		matrizR1[Bogota][Salvador] = 0;
		matrizR1[Bogota][Recife] = 0;
		matrizR1[Bogota][Fortaleza] = 0;
		matrizR1[Bogota][Belem] = 0;
		matrizR1[Bogota][Manaos] = 0;
		matrizR1[Bogota][Panama] = 0;
		matrizR1[Bogota][Carajas] = 0;
		matrizR1[Bogota][PuntaCana] = 0;
		matrizR1[Bogota][Acapulco] = 0;
		matrizR1[Bogota][CiudadDeMexico] = 0;
		matrizR1[Bogota][Merida] = 0;
		matrizR1[Bogota][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Bogota][i] = 0;
		}
		matrizR1[Medellin][Lima] = 0;
		matrizR1[Medellin][Santiago] = 0;
		matrizR1[Medellin][Quito] = 0;
		matrizR1[Medellin][Guayaquil] = 0;
		matrizR1[Medellin][LaPaz] = 0;
		matrizR1[Medellin][BuenosAires] = 0;
		matrizR1[Medellin][Iquique] = 0;
		matrizR1[Medellin][Cordoba] = 0;
		matrizR1[Medellin][SantaCruz] = 0;
		matrizR1[Medellin][PortoAlegre] = 0;
		matrizR1[Medellin][Asuncion] = 0;
		matrizR1[Medellin][Iguazu] = 0;
		matrizR1[Medellin][SaoPaulo] = 0;
		matrizR1[Medellin][Brasilia] = 0;
		matrizR1[Medellin][Mendoza] = 0;
		matrizR1[Medellin][Montevideo] = 0;
		matrizR1[Medellin][Rosario] = 0;
		matrizR1[Medellin][Florianopolis] = 0;
		matrizR1[Medellin][CiudadDelEste] = 0;
		matrizR1[Medellin][Curitiba] = 0;
		matrizR1[Medellin][RioDeJaneiro] = 0;
		matrizR1[Medellin][BeloHorizonte] = 0;
		matrizR1[Medellin][PortoSeguro] = 0;
		matrizR1[Medellin][Salvador] = 0;
		matrizR1[Medellin][Recife] = 0;
		matrizR1[Medellin][Fortaleza] = 0;
		matrizR1[Medellin][Leticia] = 0;
		matrizR1[Medellin][Cali] = 0;
		matrizR1[Medellin][Panama] = 0;
		matrizR1[Medellin][Aruba] = 0;
		matrizR1[Medellin][Carajas] = 0;
		matrizR1[Medellin][VillaHermosa] = 0;
		matrizR1[Medellin][SanJuan] = 0;
		matrizR1[Medellin][Acapulco] = 0;
		matrizR1[Medellin][CiudadDeMexico] = 0;
		matrizR1[Medellin][Veracruz] = 0;
		matrizR1[Medellin][Merida] = 0;
		matrizR1[Medellin][Cancun] = 0;
		matrizR1[Medellin][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Medellin][i] = 0;
		}
		matrizR1[Panama][Lima] = 0;
		matrizR1[Panama][Santiago] = 0;
		matrizR1[Panama][Quito] = 0;
		matrizR1[Panama][Guayaquil] = 0;
		matrizR1[Panama][LaPaz] = 0;
		matrizR1[Panama][BuenosAires] = 0;
		matrizR1[Panama][Iquique] = 0;
		matrizR1[Panama][Cordoba] = 0;
		matrizR1[Panama][SantaCruz] = 0;
		matrizR1[Panama][PortoAlegre] = 0;
		matrizR1[Panama][Asuncion] = 0;
		matrizR1[Panama][Iguazu] = 0;
		matrizR1[Panama][SaoPaulo] = 0;
		matrizR1[Panama][Brasilia] = 0;
		matrizR1[Panama][Mendoza] = 0;
		matrizR1[Panama][Montevideo] = 0;
		matrizR1[Panama][Rosario] = 0;
		matrizR1[Panama][Florianopolis] = 0;
		matrizR1[Panama][CiudadDelEste] = 0;
		matrizR1[Panama][Curitiba] = 0;
		matrizR1[Panama][RioDeJaneiro] = 0;
		matrizR1[Panama][BeloHorizonte] = 0;
		matrizR1[Panama][PortoSeguro] = 0;
		matrizR1[Panama][Salvador] = 0;
		matrizR1[Panama][Recife] = 0;
		matrizR1[Panama][Fortaleza] = 0;
		matrizR1[Panama][Belem] = 0;
		matrizR1[Panama][Manaos] = 0;
		matrizR1[Panama][Leticia] = 0;
		matrizR1[Panama][Cali] = 0;
		matrizR1[Panama][Bogota] = 0;
		matrizR1[Panama][Medellin] = 0;
		matrizR1[Panama][Cartagena] = 0;
		matrizR1[Panama][Aruba] = 0;
		matrizR1[Panama][Carajas] = 0;
		matrizR1[Panama][VillaHermosa] = 0;
		matrizR1[Panama][SanJuan] = 0;
		matrizR1[Panama][PuntaCana] = 0;
		matrizR1[Panama][Acapulco] = 0;
		matrizR1[Panama][CiudadDeMexico] = 0;
		matrizR1[Panama][Veracruz] = 0;
		matrizR1[Panama][Merida] = 0;
		matrizR1[Panama][Cancun] = 0;
		matrizR1[Panama][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Panama][i] = 0;
		}
		matrizR1[Cartagena][Quito] = 0;
		matrizR1[Cartagena][Guayaquil] = 0;
		matrizR1[Cartagena][LaPaz] = 0;
		matrizR1[Cartagena][Iquique] = 0;
		matrizR1[Cartagena][Cordoba] = 0;
		matrizR1[Cartagena][SantaCruz] = 0;
		matrizR1[Cartagena][PortoAlegre] = 0;
		matrizR1[Cartagena][Asuncion] = 0;
		matrizR1[Cartagena][Iguazu] = 0;
		matrizR1[Cartagena][Brasilia] = 0;
		matrizR1[Cartagena][Mendoza] = 0;
		matrizR1[Cartagena][Montevideo] = 0;
		matrizR1[Cartagena][Rosario] = 0;
		matrizR1[Cartagena][Florianopolis] = 0;
		matrizR1[Cartagena][CiudadDelEste] = 0;
		matrizR1[Cartagena][Curitiba] = 0;
		matrizR1[Cartagena][RioDeJaneiro] = 0;
		matrizR1[Cartagena][BeloHorizonte] = 0;
		matrizR1[Cartagena][PortoSeguro] = 0;
		matrizR1[Cartagena][Salvador] = 0;
		matrizR1[Cartagena][Recife] = 0;
		matrizR1[Cartagena][Fortaleza] = 0;
		matrizR1[Cartagena][Belem] = 0;
		matrizR1[Cartagena][Manaos] = 0;
		matrizR1[Cartagena][Leticia] = 0;
		matrizR1[Cartagena][Cali] = 0;
		matrizR1[Cartagena][Bogota] = 0;
		matrizR1[Cartagena][Medellin] = 0;
		matrizR1[Cartagena][Panama] = 0;
		matrizR1[Cartagena][Aruba] = 0;
		matrizR1[Cartagena][Carajas] = 0;
		matrizR1[Cartagena][VillaHermosa] = 0;
		matrizR1[Cartagena][SanJuan] = 0;
		matrizR1[Cartagena][PuntaCana] = 0;
		matrizR1[Cartagena][Acapulco] = 0;
		matrizR1[Cartagena][Veracruz] = 0;
		matrizR1[Cartagena][Merida] = 0;
		matrizR1[Cartagena][Cancun] = 0;
		matrizR1[Cartagena][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Cartagena][i] = 0;
		}
		matrizR1[Aruba][Lima] = 0;
		matrizR1[Aruba][Santiago] = 0;
		matrizR1[Aruba][Quito] = 0;
		matrizR1[Aruba][Guayaquil] = 0;
		matrizR1[Aruba][LaPaz] = 0;
		matrizR1[Aruba][BuenosAires] = 0;
		matrizR1[Aruba][Iquique] = 0;
		matrizR1[Aruba][Cordoba] = 0;
		matrizR1[Aruba][SantaCruz] = 0;
		matrizR1[Aruba][PortoAlegre] = 0;
		matrizR1[Aruba][Asuncion] = 0;
		matrizR1[Aruba][Iguazu] = 0;
		matrizR1[Aruba][Brasilia] = 0;
		matrizR1[Aruba][Mendoza] = 0;
		matrizR1[Aruba][Montevideo] = 0;
		matrizR1[Aruba][Rosario] = 0;
		matrizR1[Aruba][Florianopolis] = 0;
		matrizR1[Aruba][CiudadDelEste] = 0;
		matrizR1[Aruba][Curitiba] = 0;
		matrizR1[Aruba][RioDeJaneiro] = 0;
		matrizR1[Aruba][BeloHorizonte] = 0;
		matrizR1[Aruba][PortoSeguro] = 0;
		matrizR1[Aruba][Salvador] = 0;
		matrizR1[Aruba][Recife] = 0;
		matrizR1[Aruba][Fortaleza] = 0;
		matrizR1[Aruba][Belem] = 0;
		matrizR1[Aruba][Manaos] = 0;
		matrizR1[Aruba][Leticia] = 0;
		matrizR1[Aruba][Cali] = 0;
		matrizR1[Aruba][Medellin] = 0;
		matrizR1[Aruba][Panama] = 0;
		matrizR1[Aruba][Cartagena] = 0;
		matrizR1[Aruba][Carajas] = 0;
		matrizR1[Aruba][VillaHermosa] = 0;
		matrizR1[Aruba][SanJuan] = 0;
		matrizR1[Aruba][PuntaCana] = 0;
		matrizR1[Aruba][Acapulco] = 0;
		matrizR1[Aruba][CiudadDeMexico] = 0;
		matrizR1[Aruba][Veracruz] = 0;
		matrizR1[Aruba][Merida] = 0;
		matrizR1[Aruba][Cancun] = 0;
		matrizR1[Aruba][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Aruba][i] = 0;
		}
		matrizR1[Carajas][Lima] = 0;
		matrizR1[Carajas][Santiago] = 0;
		matrizR1[Carajas][Quito] = 0;
		matrizR1[Carajas][Guayaquil] = 0;
		matrizR1[Carajas][LaPaz] = 0;
		matrizR1[Carajas][BuenosAires] = 0;
		matrizR1[Carajas][Iquique] = 0;
		matrizR1[Carajas][Cordoba] = 0;
		matrizR1[Carajas][SantaCruz] = 0;
		matrizR1[Carajas][PortoAlegre] = 0;
		matrizR1[Carajas][Asuncion] = 0;
		matrizR1[Carajas][Iguazu] = 0;
		matrizR1[Carajas][SaoPaulo] = 0;
		matrizR1[Carajas][Brasilia] = 0;
		matrizR1[Carajas][Mendoza] = 0;
		matrizR1[Carajas][Montevideo] = 0;
		matrizR1[Carajas][Rosario] = 0;
		matrizR1[Carajas][Florianopolis] = 0;
		matrizR1[Carajas][CiudadDelEste] = 0;
		matrizR1[Carajas][Curitiba] = 0;
		matrizR1[Carajas][RioDeJaneiro] = 0;
		matrizR1[Carajas][BeloHorizonte] = 0;
		matrizR1[Carajas][PortoSeguro] = 0;
		matrizR1[Carajas][Salvador] = 0;
		matrizR1[Carajas][Recife] = 0;
		matrizR1[Carajas][Fortaleza] = 0;
		matrizR1[Carajas][Belem] = 0;
		matrizR1[Carajas][Manaos] = 0;
		matrizR1[Carajas][Leticia] = 0;
		matrizR1[Carajas][Cali] = 0;
		matrizR1[Carajas][Bogota] = 0;
		matrizR1[Carajas][Medellin] = 0;
		matrizR1[Carajas][Panama] = 0;
		matrizR1[Carajas][Cartagena] = 0;
		matrizR1[Carajas][Aruba] = 0;
		matrizR1[Carajas][Carajas] = 0;
		matrizR1[Carajas][VillaHermosa] = 0;
		matrizR1[Carajas][SanJuan] = 0;
		matrizR1[Carajas][PuntaCana] = 0;
		matrizR1[Carajas][Acapulco] = 0;
		matrizR1[Carajas][CiudadDeMexico] = 0;
		matrizR1[Carajas][Veracruz] = 0;
		matrizR1[Carajas][Merida] = 0;
		matrizR1[Carajas][Cancun] = 0;
		matrizR1[Carajas][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Carajas][i] = 0;
		}
		matrizR1[VillaHermosa][Lima] = 0;
		matrizR1[VillaHermosa][Santiago] = 0;
		matrizR1[VillaHermosa][Quito] = 0;
		matrizR1[VillaHermosa][Guayaquil] = 0;
		matrizR1[VillaHermosa][LaPaz] = 0;
		matrizR1[VillaHermosa][BuenosAires] = 0;
		matrizR1[VillaHermosa][Iquique] = 0;
		matrizR1[VillaHermosa][Cordoba] = 0;
		matrizR1[VillaHermosa][SantaCruz] = 0;
		matrizR1[VillaHermosa][PortoAlegre] = 0;
		matrizR1[VillaHermosa][Asuncion] = 0;
		matrizR1[VillaHermosa][Iguazu] = 0;
		matrizR1[VillaHermosa][SaoPaulo] = 0;
		matrizR1[VillaHermosa][Brasilia] = 0;
		matrizR1[VillaHermosa][Mendoza] = 0;
		matrizR1[VillaHermosa][Montevideo] = 0;
		matrizR1[VillaHermosa][Rosario] = 0;
		matrizR1[VillaHermosa][Florianopolis] = 0;
		matrizR1[VillaHermosa][CiudadDelEste] = 0;
		matrizR1[VillaHermosa][Curitiba] = 0;
		matrizR1[VillaHermosa][RioDeJaneiro] = 0;
		matrizR1[VillaHermosa][BeloHorizonte] = 0;
		matrizR1[VillaHermosa][PortoSeguro] = 0;
		matrizR1[VillaHermosa][Salvador] = 0;
		matrizR1[VillaHermosa][Recife] = 0;
		matrizR1[VillaHermosa][Fortaleza] = 0;
		matrizR1[VillaHermosa][Belem] = 0;
		matrizR1[VillaHermosa][Manaos] = 0;
		matrizR1[VillaHermosa][Leticia] = 0;
		matrizR1[VillaHermosa][Cali] = 0;
		matrizR1[VillaHermosa][Bogota] = 0;
		matrizR1[VillaHermosa][Medellin] = 0;
		matrizR1[VillaHermosa][Panama] = 0;
		matrizR1[VillaHermosa][Cartagena] = 0;
		matrizR1[VillaHermosa][Aruba] = 0;
		matrizR1[VillaHermosa][Carajas] = 0;
		matrizR1[VillaHermosa][SanJuan] = 0;
		matrizR1[VillaHermosa][PuntaCana] = 0;
		matrizR1[VillaHermosa][Acapulco] = 0;
		matrizR1[VillaHermosa][Veracruz] = 0;
		matrizR1[VillaHermosa][Merida] = 0;
		matrizR1[VillaHermosa][Cancun] = 0;
		matrizR1[VillaHermosa][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[VillaHermosa][i] = 0;
		}
		matrizR1[SanJuan][Lima] = 0;
		matrizR1[SanJuan][Santiago] = 0;
		matrizR1[SanJuan][Quito] = 0;
		matrizR1[SanJuan][Guayaquil] = 0;
		matrizR1[SanJuan][LaPaz] = 0;
		matrizR1[SanJuan][Iquique] = 0;
		matrizR1[SanJuan][Cordoba] = 0;
		matrizR1[SanJuan][SantaCruz] = 0;
		matrizR1[SanJuan][PortoAlegre] = 0;
		matrizR1[SanJuan][Asuncion] = 0;
		matrizR1[SanJuan][Iguazu] = 0;
		matrizR1[SanJuan][SaoPaulo] = 0;
		matrizR1[SanJuan][Brasilia] = 0;
		matrizR1[SanJuan][Mendoza] = 0;
		matrizR1[SanJuan][Montevideo] = 0;
		matrizR1[SanJuan][Rosario] = 0;
		matrizR1[SanJuan][Florianopolis] = 0;
		matrizR1[SanJuan][CiudadDelEste] = 0;
		matrizR1[SanJuan][Curitiba] = 0;
		matrizR1[SanJuan][RioDeJaneiro] = 0;
		matrizR1[SanJuan][BeloHorizonte] = 0;
		matrizR1[SanJuan][PortoSeguro] = 0;
		matrizR1[SanJuan][Salvador] = 0;
		matrizR1[SanJuan][Recife] = 0;
		matrizR1[SanJuan][Fortaleza] = 0;
		matrizR1[SanJuan][Belem] = 0;
		matrizR1[SanJuan][Manaos] = 0;
		matrizR1[SanJuan][Leticia] = 0;
		matrizR1[SanJuan][Cali] = 0;
		matrizR1[SanJuan][Bogota] = 0;
		matrizR1[SanJuan][Medellin] = 0;
		matrizR1[SanJuan][Panama] = 0;
		matrizR1[SanJuan][Cartagena] = 0;
		matrizR1[SanJuan][Aruba] = 0;
		matrizR1[SanJuan][Carajas] = 0;
		matrizR1[SanJuan][VillaHermosa] = 0;
		matrizR1[SanJuan][PuntaCana] = 0;
		matrizR1[SanJuan][Acapulco] = 0;
		matrizR1[SanJuan][CiudadDeMexico] = 0;
		matrizR1[SanJuan][Veracruz] = 0;
		matrizR1[SanJuan][Merida] = 0;
		matrizR1[SanJuan][Cancun] = 0;
		matrizR1[SanJuan][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[SanJuan][i] = 0;
		}
		matrizR1[PuntaCana][Santiago] = 0;
		matrizR1[PuntaCana][Quito] = 0;
		matrizR1[PuntaCana][Guayaquil] = 0;
		matrizR1[PuntaCana][LaPaz] = 0;
		matrizR1[PuntaCana][BuenosAires] = 0;
		matrizR1[PuntaCana][Iquique] = 0;
		matrizR1[PuntaCana][Cordoba] = 0;
		matrizR1[PuntaCana][SantaCruz] = 0;
		matrizR1[PuntaCana][PortoAlegre] = 0;
		matrizR1[PuntaCana][Asuncion] = 0;
		matrizR1[PuntaCana][Iguazu] = 0;
		matrizR1[PuntaCana][SaoPaulo] = 0;
		matrizR1[PuntaCana][Brasilia] = 0;
		matrizR1[PuntaCana][Mendoza] = 0;
		matrizR1[PuntaCana][Montevideo] = 0;
		matrizR1[PuntaCana][Rosario] = 0;
		matrizR1[PuntaCana][Florianopolis] = 0;
		matrizR1[PuntaCana][CiudadDelEste] = 0;
		matrizR1[PuntaCana][Curitiba] = 0;
		matrizR1[PuntaCana][RioDeJaneiro] = 0;
		matrizR1[PuntaCana][BeloHorizonte] = 0;
		matrizR1[PuntaCana][PortoSeguro] = 0;
		matrizR1[PuntaCana][Salvador] = 0;
		matrizR1[PuntaCana][Recife] = 0;
		matrizR1[PuntaCana][Fortaleza] = 0;
		matrizR1[PuntaCana][Belem] = 0;
		matrizR1[PuntaCana][Manaos] = 0;
		matrizR1[PuntaCana][Leticia] = 0;
		matrizR1[PuntaCana][Bogota] = 0;
		matrizR1[PuntaCana][Medellin] = 0;
		matrizR1[PuntaCana][Panama] = 0;
		matrizR1[PuntaCana][Cartagena] = 0;
		matrizR1[PuntaCana][Aruba] = 0;
		matrizR1[PuntaCana][Carajas] = 0;
		matrizR1[PuntaCana][VillaHermosa] = 0;
		matrizR1[PuntaCana][SanJuan] = 0;
		matrizR1[PuntaCana][Acapulco] = 0;
		matrizR1[PuntaCana][CiudadDeMexico] = 0;
		matrizR1[PuntaCana][Veracruz] = 0;
		matrizR1[PuntaCana][Merida] = 0;
		matrizR1[PuntaCana][Cancun] = 0;
		matrizR1[PuntaCana][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[PuntaCana][i] = 0;
		}
		matrizR1[Acapulco][Lima] = 0;
		matrizR1[Acapulco][Santiago] = 0;
		matrizR1[Acapulco][Quito] = 0;
		matrizR1[Acapulco][Guayaquil] = 0;
		matrizR1[Acapulco][LaPaz] = 0;
		matrizR1[Acapulco][BuenosAires] = 0;
		matrizR1[Acapulco][Iquique] = 0;
		matrizR1[Acapulco][Cordoba] = 0;
		matrizR1[Acapulco][SantaCruz] = 0;
		matrizR1[Acapulco][PortoAlegre] = 0;
		matrizR1[Acapulco][Asuncion] = 0;
		matrizR1[Acapulco][Iguazu] = 0;
		matrizR1[Acapulco][SaoPaulo] = 0;
		matrizR1[Acapulco][Brasilia] = 0;
		matrizR1[Acapulco][Mendoza] = 0;
		matrizR1[Acapulco][Montevideo] = 0;
		matrizR1[Acapulco][Rosario] = 0;
		matrizR1[Acapulco][Florianopolis] = 0;
		matrizR1[Acapulco][CiudadDelEste] = 0;
		matrizR1[Acapulco][Curitiba] = 0;
		matrizR1[Acapulco][RioDeJaneiro] = 0;
		matrizR1[Acapulco][BeloHorizonte] = 0;
		matrizR1[Acapulco][PortoSeguro] = 0;
		matrizR1[Acapulco][Salvador] = 0;
		matrizR1[Acapulco][Recife] = 0;
		matrizR1[Acapulco][Fortaleza] = 0;
		matrizR1[Acapulco][Belem] = 0;
		matrizR1[Acapulco][Manaos] = 0;
		matrizR1[Acapulco][Leticia] = 0;
		matrizR1[Acapulco][Cali] = 0;
		matrizR1[Acapulco][Bogota] = 0;
		matrizR1[Acapulco][Medellin] = 0;
		matrizR1[Acapulco][Panama] = 0;
		matrizR1[Acapulco][Cartagena] = 0;
		matrizR1[Acapulco][Aruba] = 0;
		matrizR1[Acapulco][Carajas] = 0;
		matrizR1[Acapulco][VillaHermosa] = 0;
		matrizR1[Acapulco][SanJuan] = 0;
		matrizR1[Acapulco][PuntaCana] = 0;
		matrizR1[Acapulco][Veracruz] = 0;
		matrizR1[Acapulco][Merida] = 0;
		matrizR1[Acapulco][Cancun] = 0;
		matrizR1[Acapulco][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Acapulco][i] = 0;
		}
		matrizR1[CiudadDeMexico][Quito] = 0;
		matrizR1[CiudadDeMexico][Guayaquil] = 0;
		matrizR1[CiudadDeMexico][LaPaz] = 0;
		matrizR1[CiudadDeMexico][BuenosAires] = 0;
		matrizR1[CiudadDeMexico][Iquique] = 0;
		matrizR1[CiudadDeMexico][Cordoba] = 0;
		matrizR1[CiudadDeMexico][SantaCruz] = 0;
		matrizR1[CiudadDeMexico][PortoAlegre] = 0;
		matrizR1[CiudadDeMexico][Asuncion] = 0;
		matrizR1[CiudadDeMexico][Iguazu] = 0;
		matrizR1[CiudadDeMexico][Brasilia] = 0;
		matrizR1[CiudadDeMexico][Mendoza] = 0;
		matrizR1[CiudadDeMexico][Montevideo] = 0;
		matrizR1[CiudadDeMexico][Rosario] = 0;
		matrizR1[CiudadDeMexico][Florianopolis] = 0;
		matrizR1[CiudadDeMexico][CiudadDelEste] = 0;
		matrizR1[CiudadDeMexico][Curitiba] = 0;
		matrizR1[CiudadDeMexico][RioDeJaneiro] = 0;
		matrizR1[CiudadDeMexico][BeloHorizonte] = 0;
		matrizR1[CiudadDeMexico][PortoSeguro] = 0;
		matrizR1[CiudadDeMexico][Salvador] = 0;
		matrizR1[CiudadDeMexico][Recife] = 0;
		matrizR1[CiudadDeMexico][Fortaleza] = 0;
		matrizR1[CiudadDeMexico][Belem] = 0;
		matrizR1[CiudadDeMexico][Manaos] = 0;
		matrizR1[CiudadDeMexico][Leticia] = 0;
		matrizR1[CiudadDeMexico][Bogota] = 0;
		matrizR1[CiudadDeMexico][Medellin] = 0;
		matrizR1[CiudadDeMexico][Panama] = 0;
		matrizR1[CiudadDeMexico][Cartagena] = 0;
		matrizR1[CiudadDeMexico][Aruba] = 0;
		matrizR1[CiudadDeMexico][Carajas] = 0;
		matrizR1[CiudadDeMexico][VillaHermosa] = 0;
		matrizR1[CiudadDeMexico][SanJuan] = 0;
		matrizR1[CiudadDeMexico][PuntaCana] = 0;
		matrizR1[CiudadDeMexico][Acapulco] = 0;
		matrizR1[CiudadDeMexico][Veracruz] = 0;
		matrizR1[CiudadDeMexico][Merida] = 0;
		matrizR1[CiudadDeMexico][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[CiudadDeMexico][i] = 0;
		}
		matrizR1[Veracruz][Lima] = 0;
		matrizR1[Veracruz][Santiago] = 0;
		matrizR1[Veracruz][Quito] = 0;
		matrizR1[Veracruz][Guayaquil] = 0;
		matrizR1[Veracruz][LaPaz] = 0;
		matrizR1[Veracruz][BuenosAires] = 0;
		matrizR1[Veracruz][Iquique] = 0;
		matrizR1[Veracruz][Cordoba] = 0;
		matrizR1[Veracruz][SantaCruz] = 0;
		matrizR1[Veracruz][PortoAlegre] = 0;
		matrizR1[Veracruz][Asuncion] = 0;
		matrizR1[Veracruz][Iguazu] = 0;
		matrizR1[Veracruz][Brasilia] = 0;
		matrizR1[Veracruz][Mendoza] = 0;
		matrizR1[Veracruz][Montevideo] = 0;
		matrizR1[Veracruz][Rosario] = 0;
		matrizR1[Veracruz][Florianopolis] = 0;
		matrizR1[Veracruz][CiudadDelEste] = 0;
		matrizR1[Veracruz][Curitiba] = 0;
		matrizR1[Veracruz][RioDeJaneiro] = 0;
		matrizR1[Veracruz][BeloHorizonte] = 0;
		matrizR1[Veracruz][PortoSeguro] = 0;
		matrizR1[Veracruz][Salvador] = 0;
		matrizR1[Veracruz][Recife] = 0;
		matrizR1[Veracruz][Fortaleza] = 0;
		matrizR1[Veracruz][Belem] = 0;
		matrizR1[Veracruz][Manaos] = 0;
		matrizR1[Veracruz][Leticia] = 0;
		matrizR1[Veracruz][Bogota] = 0;
		matrizR1[Veracruz][Medellin] = 0;
		matrizR1[Veracruz][Panama] = 0;
		matrizR1[Veracruz][Cartagena] = 0;
		matrizR1[Veracruz][Aruba] = 0;
		matrizR1[Veracruz][Carajas] = 0;
		matrizR1[Veracruz][VillaHermosa] = 0;
		matrizR1[Veracruz][SanJuan] = 0;
		matrizR1[Veracruz][PuntaCana] = 0;
		matrizR1[Veracruz][Acapulco] = 0;
		matrizR1[Veracruz][Veracruz] = 0;
		matrizR1[Veracruz][Merida] = 0;
		matrizR1[Veracruz][Cancun] = 0;
		matrizR1[Veracruz][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Veracruz][i] = 0;
		}
		matrizR1[Merida][Lima] = 0;
		matrizR1[Merida][Santiago] = 0;
		matrizR1[Merida][Quito] = 0;
		matrizR1[Merida][Guayaquil] = 0;
		matrizR1[Merida][LaPaz] = 0;
		matrizR1[Merida][BuenosAires] = 0;
		matrizR1[Merida][Iquique] = 0;
		matrizR1[Merida][Cordoba] = 0;
		matrizR1[Merida][SantaCruz] = 0;
		matrizR1[Merida][PortoAlegre] = 0;
		matrizR1[Merida][Asuncion] = 0;
		matrizR1[Merida][Iguazu] = 0;
		matrizR1[Merida][Brasilia] = 0;
		matrizR1[Merida][Mendoza] = 0;
		matrizR1[Merida][Montevideo] = 0;
		matrizR1[Merida][Rosario] = 0;
		matrizR1[Merida][Florianopolis] = 0;
		matrizR1[Merida][CiudadDelEste] = 0;
		matrizR1[Merida][Curitiba] = 0;
		matrizR1[Merida][RioDeJaneiro] = 0;
		matrizR1[Merida][BeloHorizonte] = 0;
		matrizR1[Merida][PortoSeguro] = 0;
		matrizR1[Merida][Salvador] = 0;
		matrizR1[Merida][Recife] = 0;
		matrizR1[Merida][Fortaleza] = 0;
		matrizR1[Merida][Belem] = 0;
		matrizR1[Merida][Manaos] = 0;
		matrizR1[Merida][Leticia] = 0;
		matrizR1[Merida][Bogota] = 0;
		matrizR1[Merida][Medellin] = 0;
		matrizR1[Merida][Panama] = 0;
		matrizR1[Merida][Cartagena] = 0;
		matrizR1[Merida][Aruba] = 0;
		matrizR1[Merida][Carajas] = 0;
		matrizR1[Merida][VillaHermosa] = 0;
		matrizR1[Merida][SanJuan] = 0;
		matrizR1[Merida][PuntaCana] = 0;
		matrizR1[Merida][Acapulco] = 0;
		matrizR1[Merida][Veracruz] = 0;
		matrizR1[Merida][Merida] = 0;
		matrizR1[Merida][Cancun] = 0;
		matrizR1[Merida][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Merida][i] = 0;
		}
		matrizR1[Cancun][Santiago] = 0;
		matrizR1[Cancun][Quito] = 0;
		matrizR1[Cancun][Guayaquil] = 0;
		matrizR1[Cancun][LaPaz] = 0;
		matrizR1[Cancun][BuenosAires] = 0;
		matrizR1[Cancun][Iquique] = 0;
		matrizR1[Cancun][Cordoba] = 0;
		matrizR1[Cancun][SantaCruz] = 0;
		matrizR1[Cancun][PortoAlegre] = 0;
		matrizR1[Cancun][Asuncion] = 0;
		matrizR1[Cancun][Iguazu] = 0;
		matrizR1[Cancun][Brasilia] = 0;
		matrizR1[Cancun][Mendoza] = 0;
		matrizR1[Cancun][Montevideo] = 0;
		matrizR1[Cancun][Rosario] = 0;
		matrizR1[Cancun][Florianopolis] = 0;
		matrizR1[Cancun][CiudadDelEste] = 0;
		matrizR1[Cancun][Curitiba] = 0;
		matrizR1[Cancun][RioDeJaneiro] = 0;
		matrizR1[Cancun][BeloHorizonte] = 0;
		matrizR1[Cancun][PortoSeguro] = 0;
		matrizR1[Cancun][Salvador] = 0;
		matrizR1[Cancun][Recife] = 0;
		matrizR1[Cancun][Fortaleza] = 0;
		matrizR1[Cancun][Belem] = 0;
		matrizR1[Cancun][Manaos] = 0;
		matrizR1[Cancun][Leticia] = 0;
		matrizR1[Cancun][Medellin] = 0;
		matrizR1[Cancun][Panama] = 0;
		matrizR1[Cancun][Cartagena] = 0;
		matrizR1[Cancun][Aruba] = 0;
		matrizR1[Cancun][Carajas] = 0;
		matrizR1[Cancun][VillaHermosa] = 0;
		matrizR1[Cancun][SanJuan] = 0;
		matrizR1[Cancun][PuntaCana] = 0;
		matrizR1[Cancun][Acapulco] = 0;
		matrizR1[Cancun][Veracruz] = 0;
		matrizR1[Cancun][Merida] = 0;
		matrizR1[Cancun][LaHabana] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[Cancun][i] = 0;
		}
		matrizR1[LaHabana][Santiago] = 0;
		matrizR1[LaHabana][Quito] = 0;
		matrizR1[LaHabana][Guayaquil] = 0;
		matrizR1[LaHabana][LaPaz] = 0;
		matrizR1[LaHabana][BuenosAires] = 0;
		matrizR1[LaHabana][Iquique] = 0;
		matrizR1[LaHabana][Cordoba] = 0;
		matrizR1[LaHabana][SantaCruz] = 0;
		matrizR1[LaHabana][PortoAlegre] = 0;
		matrizR1[LaHabana][Asuncion] = 0;
		matrizR1[LaHabana][Iguazu] = 0;
		matrizR1[LaHabana][Brasilia] = 0;
		matrizR1[LaHabana][Mendoza] = 0;
		matrizR1[LaHabana][Montevideo] = 0;
		matrizR1[LaHabana][Rosario] = 0;
		matrizR1[LaHabana][Florianopolis] = 0;
		matrizR1[LaHabana][CiudadDelEste] = 0;
		matrizR1[LaHabana][Curitiba] = 0;
		matrizR1[LaHabana][RioDeJaneiro] = 0;
		matrizR1[LaHabana][BeloHorizonte] = 0;
		matrizR1[LaHabana][PortoSeguro] = 0;
		matrizR1[LaHabana][Salvador] = 0;
		matrizR1[LaHabana][Recife] = 0;
		matrizR1[LaHabana][Fortaleza] = 0;
		matrizR1[LaHabana][Belem] = 0;
		matrizR1[LaHabana][Manaos] = 0;
		matrizR1[LaHabana][Leticia] = 0;
		matrizR1[LaHabana][Bogota] = 0;
		matrizR1[LaHabana][Medellin] = 0;
		matrizR1[LaHabana][Panama] = 0;
		matrizR1[LaHabana][Cartagena] = 0;
		matrizR1[LaHabana][Aruba] = 0;
		matrizR1[LaHabana][Carajas] = 0;
		matrizR1[LaHabana][VillaHermosa] = 0;
		matrizR1[LaHabana][SanJuan] = 0;
		matrizR1[LaHabana][PuntaCana] = 0;
		matrizR1[LaHabana][Acapulco] = 0;
		matrizR1[LaHabana][Veracruz] = 0;
		matrizR1[LaHabana][CiudadDeMexico] = 0;
		matrizR1[LaHabana][Merida] = 0;
		matrizR1[LaHabana][Cancun] = 0;
		for (int i = 87; i < 102; i++){
			matrizR1[LaHabana][i] = 0;
		}

		//-----------------ENZO-----------------------------

		matrizR1[Pucallpa][Santiago] = 0;
		matrizR1[Pucallpa][Quito] = 0;
		matrizR1[Pucallpa][Guayaquil] = 0;
		matrizR1[Pucallpa][LaPaz] = 0;
		matrizR1[Pucallpa][BuenosAires] = 0;
		matrizR1[Pucallpa][Iquique] = 0;
		matrizR1[Pucallpa][Cordoba] = 0;
		matrizR1[Pucallpa][SantaCruz] = 0;
		matrizR1[Pucallpa][PortoAlegre] = 0;
		matrizR1[Pucallpa][Asuncion] = 0;
		matrizR1[Pucallpa][Iguazu] = 0;
		matrizR1[Pucallpa][Brasilia] = 0;
		matrizR1[Pucallpa][Mendoza] = 0;
		matrizR1[Pucallpa][Montevideo] = 0;
		matrizR1[Pucallpa][Rosario] = 0;
		matrizR1[Pucallpa][Florianopolis] = 0;
		matrizR1[Pucallpa][CiudadDelEste] = 0;
		matrizR1[Pucallpa][Curitiba] = 0;
		matrizR1[Pucallpa][RioDeJaneiro] = 0;
		matrizR1[Pucallpa][BeloHorizonte] = 0;
		matrizR1[Pucallpa][PortoSeguro] = 0;
		matrizR1[Pucallpa][Salvador] = 0;
		matrizR1[Pucallpa][Recife] = 0;
		matrizR1[Pucallpa][Fortaleza] = 0;
		matrizR1[Pucallpa][Belem] = 0;
		matrizR1[Pucallpa][Manaos] = 0;
		matrizR1[Pucallpa][Leticia] = 0;
		matrizR1[Pucallpa][Bogota] = 0;
		matrizR1[Pucallpa][Medellin] = 0;
		matrizR1[Pucallpa][Panama] = 0;
		matrizR1[Pucallpa][Cartagena] = 0;
		matrizR1[Pucallpa][Aruba] = 0;
		matrizR1[Pucallpa][Carajas] = 0;
		matrizR1[Pucallpa][VillaHermosa] = 0;
		matrizR1[Pucallpa][SanJuan] = 0;
		matrizR1[Pucallpa][PuntaCana] = 0;
		matrizR1[Pucallpa][Acapulco] = 0;
		matrizR1[Pucallpa][Veracruz] = 0;
		matrizR1[Pucallpa][CiudadDeMexico] = 0;
		matrizR1[Pucallpa][Merida] = 0;
		matrizR1[Pucallpa][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[Pucallpa][i] = 0;
		}

		matrizR1[Ayacucho][Santiago] = 0;
		matrizR1[Ayacucho][Quito] = 0;
		matrizR1[Ayacucho][Guayaquil] = 0;
		matrizR1[Ayacucho][LaPaz] = 0;
		matrizR1[Ayacucho][BuenosAires] = 0;
		matrizR1[Ayacucho][Iquique] = 0;
		matrizR1[Ayacucho][Cordoba] = 0;
		matrizR1[Ayacucho][SantaCruz] = 0;
		matrizR1[Ayacucho][PortoAlegre] = 0;
		matrizR1[Ayacucho][Asuncion] = 0;
		matrizR1[Ayacucho][Iguazu] = 0;
		matrizR1[Ayacucho][Brasilia] = 0;
		matrizR1[Ayacucho][Mendoza] = 0;
		matrizR1[Ayacucho][Montevideo] = 0;
		matrizR1[Ayacucho][Rosario] = 0;
		matrizR1[Ayacucho][Florianopolis] = 0;
		matrizR1[Ayacucho][CiudadDelEste] = 0;
		matrizR1[Ayacucho][Curitiba] = 0;
		matrizR1[Ayacucho][RioDeJaneiro] = 0;
		matrizR1[Ayacucho][BeloHorizonte] = 0;
		matrizR1[Ayacucho][PortoSeguro] = 0;
		matrizR1[Ayacucho][Salvador] = 0;
		matrizR1[Ayacucho][Recife] = 0;
		matrizR1[Ayacucho][Fortaleza] = 0;
		matrizR1[Ayacucho][Belem] = 0;
		matrizR1[Ayacucho][Manaos] = 0;
		matrizR1[Ayacucho][Leticia] = 0;
		matrizR1[Ayacucho][Bogota] = 0;
		matrizR1[Ayacucho][Medellin] = 0;
		matrizR1[Ayacucho][Panama] = 0;
		matrizR1[Ayacucho][Cartagena] = 0;
		matrizR1[Ayacucho][Aruba] = 0;
		matrizR1[Ayacucho][Carajas] = 0;
		matrizR1[Ayacucho][VillaHermosa] = 0;
		matrizR1[Ayacucho][SanJuan] = 0;
		matrizR1[Ayacucho][PuntaCana] = 0;
		matrizR1[Ayacucho][Acapulco] = 0;
		matrizR1[Ayacucho][Veracruz] = 0;
		matrizR1[Ayacucho][CiudadDeMexico] = 0;
		matrizR1[Ayacucho][Merida] = 0;
		matrizR1[Ayacucho][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[Ayacucho][i] = 0;
		}

		matrizR1[Cusco][Santiago] = 0;
		matrizR1[Cusco][Quito] = 0;
		matrizR1[Cusco][Guayaquil] = 0;
		matrizR1[Cusco][LaPaz] = 0;
		matrizR1[Cusco][BuenosAires] = 0;
		matrizR1[Cusco][Iquique] = 0;
		matrizR1[Cusco][Cordoba] = 0;
		matrizR1[Cusco][SantaCruz] = 0;
		matrizR1[Cusco][PortoAlegre] = 0;
		matrizR1[Cusco][Asuncion] = 0;
		matrizR1[Cusco][Iguazu] = 0;
		matrizR1[Cusco][Brasilia] = 0;
		matrizR1[Cusco][Mendoza] = 0;
		matrizR1[Cusco][Montevideo] = 0;
		matrizR1[Cusco][Rosario] = 0;
		matrizR1[Cusco][Florianopolis] = 0;
		matrizR1[Cusco][CiudadDelEste] = 0;
		matrizR1[Cusco][Curitiba] = 0;
		matrizR1[Cusco][RioDeJaneiro] = 0;
		matrizR1[Cusco][BeloHorizonte] = 0;
		matrizR1[Cusco][PortoSeguro] = 0;
		matrizR1[Cusco][Salvador] = 0;
		matrizR1[Cusco][Recife] = 0;
		matrizR1[Cusco][Fortaleza] = 0;
		matrizR1[Cusco][Belem] = 0;
		matrizR1[Cusco][Manaos] = 0;
		matrizR1[Cusco][Leticia] = 0;
		matrizR1[Cusco][Bogota] = 0;
		matrizR1[Cusco][Medellin] = 0;
		matrizR1[Cusco][Panama] = 0;
		matrizR1[Cusco][Cartagena] = 0;
		matrizR1[Cusco][Aruba] = 0;
		matrizR1[Cusco][Carajas] = 0;
		matrizR1[Cusco][VillaHermosa] = 0;
		matrizR1[Cusco][SanJuan] = 0;
		matrizR1[Cusco][PuntaCana] = 0;
		matrizR1[Cusco][Acapulco] = 0;
		matrizR1[Cusco][Veracruz] = 0;
		matrizR1[Cusco][CiudadDeMexico] = 0;
		matrizR1[Cusco][Merida] = 0;
		matrizR1[Cusco][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[Cusco][i] = 0;
		}

		matrizR1[PuertoMaldonado][Santiago] = 0;
		matrizR1[PuertoMaldonado][Quito] = 0;
		matrizR1[PuertoMaldonado][Guayaquil] = 0;
		matrizR1[PuertoMaldonado][LaPaz] = 0;
		matrizR1[PuertoMaldonado][BuenosAires] = 0;
		matrizR1[PuertoMaldonado][Iquique] = 0;
		matrizR1[PuertoMaldonado][Cordoba] = 0;
		matrizR1[PuertoMaldonado][SantaCruz] = 0;
		matrizR1[PuertoMaldonado][PortoAlegre] = 0;
		matrizR1[PuertoMaldonado][Asuncion] = 0;
		matrizR1[PuertoMaldonado][Iguazu] = 0;
		matrizR1[PuertoMaldonado][Brasilia] = 0;
		matrizR1[PuertoMaldonado][Mendoza] = 0;
		matrizR1[PuertoMaldonado][Montevideo] = 0;
		matrizR1[PuertoMaldonado][Rosario] = 0;
		matrizR1[PuertoMaldonado][Florianopolis] = 0;
		matrizR1[PuertoMaldonado][CiudadDelEste] = 0;
		matrizR1[PuertoMaldonado][Curitiba] = 0;
		matrizR1[PuertoMaldonado][RioDeJaneiro] = 0;
		matrizR1[PuertoMaldonado][BeloHorizonte] = 0;
		matrizR1[PuertoMaldonado][PortoSeguro] = 0;
		matrizR1[PuertoMaldonado][Salvador] = 0;
		matrizR1[PuertoMaldonado][Recife] = 0;
		matrizR1[PuertoMaldonado][Fortaleza] = 0;
		matrizR1[PuertoMaldonado][Belem] = 0;
		matrizR1[PuertoMaldonado][Manaos] = 0;
		matrizR1[PuertoMaldonado][Leticia] = 0;
		matrizR1[PuertoMaldonado][Bogota] = 0;
		matrizR1[PuertoMaldonado][Medellin] = 0;
		matrizR1[PuertoMaldonado][Panama] = 0;
		matrizR1[PuertoMaldonado][Cartagena] = 0;
		matrizR1[PuertoMaldonado][Aruba] = 0;
		matrizR1[PuertoMaldonado][Carajas] = 0;
		matrizR1[PuertoMaldonado][VillaHermosa] = 0;
		matrizR1[PuertoMaldonado][SanJuan] = 0;
		matrizR1[PuertoMaldonado][PuntaCana] = 0;
		matrizR1[PuertoMaldonado][Acapulco] = 0;
		matrizR1[PuertoMaldonado][Veracruz] = 0;
		matrizR1[PuertoMaldonado][CiudadDeMexico] = 0;
		matrizR1[PuertoMaldonado][Merida] = 0;
		matrizR1[PuertoMaldonado][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[PuertoMaldonado][i] = 0;
		}

		matrizR1[Juliaca][Santiago] = 0;
		matrizR1[Juliaca][Quito] = 0;
		matrizR1[Juliaca][Guayaquil] = 0;
		matrizR1[Juliaca][LaPaz] = 0;
		matrizR1[Juliaca][BuenosAires] = 0;
		matrizR1[Juliaca][Iquique] = 0;
		matrizR1[Juliaca][Cordoba] = 0;
		matrizR1[Juliaca][SantaCruz] = 0;
		matrizR1[Juliaca][PortoAlegre] = 0;
		matrizR1[Juliaca][Asuncion] = 0;
		matrizR1[Juliaca][Iguazu] = 0;
		matrizR1[Juliaca][Brasilia] = 0;
		matrizR1[Juliaca][Mendoza] = 0;
		matrizR1[Juliaca][Montevideo] = 0;
		matrizR1[Juliaca][Rosario] = 0;
		matrizR1[Juliaca][Florianopolis] = 0;
		matrizR1[Juliaca][CiudadDelEste] = 0;
		matrizR1[Juliaca][Curitiba] = 0;
		matrizR1[Juliaca][RioDeJaneiro] = 0;
		matrizR1[Juliaca][BeloHorizonte] = 0;
		matrizR1[Juliaca][PortoSeguro] = 0;
		matrizR1[Juliaca][Salvador] = 0;
		matrizR1[Juliaca][Recife] = 0;
		matrizR1[Juliaca][Fortaleza] = 0;
		matrizR1[Juliaca][Belem] = 0;
		matrizR1[Juliaca][Manaos] = 0;
		matrizR1[Juliaca][Leticia] = 0;
		matrizR1[Juliaca][Bogota] = 0;
		matrizR1[Juliaca][Medellin] = 0;
		matrizR1[Juliaca][Panama] = 0;
		matrizR1[Juliaca][Cartagena] = 0;
		matrizR1[Juliaca][Aruba] = 0;
		matrizR1[Juliaca][Carajas] = 0;
		matrizR1[Juliaca][VillaHermosa] = 0;
		matrizR1[Juliaca][SanJuan] = 0;
		matrizR1[Juliaca][PuntaCana] = 0;
		matrizR1[Juliaca][Acapulco] = 0;
		matrizR1[Juliaca][Veracruz] = 0;
		matrizR1[Juliaca][CiudadDeMexico] = 0;
		matrizR1[Juliaca][Merida] = 0;
		matrizR1[Juliaca][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[Juliaca][i] = 0;
		}

		matrizR1[Arequipa][Santiago] = 0;
		matrizR1[Arequipa][Quito] = 0;
		matrizR1[Arequipa][Guayaquil] = 0;
		matrizR1[Arequipa][LaPaz] = 0;
		matrizR1[Arequipa][BuenosAires] = 0;
		matrizR1[Arequipa][Iquique] = 0;
		matrizR1[Arequipa][Cordoba] = 0;
		matrizR1[Arequipa][SantaCruz] = 0;
		matrizR1[Arequipa][PortoAlegre] = 0;
		matrizR1[Arequipa][Asuncion] = 0;
		matrizR1[Arequipa][Iguazu] = 0;
		matrizR1[Arequipa][Brasilia] = 0;
		matrizR1[Arequipa][Mendoza] = 0;
		matrizR1[Arequipa][Montevideo] = 0;
		matrizR1[Arequipa][Rosario] = 0;
		matrizR1[Arequipa][Florianopolis] = 0;
		matrizR1[Arequipa][CiudadDelEste] = 0;
		matrizR1[Arequipa][Curitiba] = 0;
		matrizR1[Arequipa][RioDeJaneiro] = 0;
		matrizR1[Arequipa][BeloHorizonte] = 0;
		matrizR1[Arequipa][PortoSeguro] = 0;
		matrizR1[Arequipa][Salvador] = 0;
		matrizR1[Arequipa][Recife] = 0;
		matrizR1[Arequipa][Fortaleza] = 0;
		matrizR1[Arequipa][Belem] = 0;
		matrizR1[Arequipa][Manaos] = 0;
		matrizR1[Arequipa][Leticia] = 0;
		matrizR1[Arequipa][Bogota] = 0;
		matrizR1[Arequipa][Medellin] = 0;
		matrizR1[Arequipa][Panama] = 0;
		matrizR1[Arequipa][Cartagena] = 0;
		matrizR1[Arequipa][Aruba] = 0;
		matrizR1[Arequipa][Carajas] = 0;
		matrizR1[Arequipa][VillaHermosa] = 0;
		matrizR1[Arequipa][SanJuan] = 0;
		matrizR1[Arequipa][PuntaCana] = 0;
		matrizR1[Arequipa][Acapulco] = 0;
		matrizR1[Arequipa][Veracruz] = 0;
		matrizR1[Arequipa][CiudadDeMexico] = 0;
		matrizR1[Arequipa][Merida] = 0;
		matrizR1[Arequipa][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[Arequipa][i] = 0;
		}

		matrizR1[Tacna][Santiago] = 0;
		matrizR1[Tacna][Quito] = 0;
		matrizR1[Tacna][Guayaquil] = 0;
		matrizR1[Tacna][LaPaz] = 0;
		matrizR1[Tacna][BuenosAires] = 0;
		matrizR1[Tacna][Iquique] = 0;
		matrizR1[Tacna][Cordoba] = 0;
		matrizR1[Tacna][SantaCruz] = 0;
		matrizR1[Tacna][PortoAlegre] = 0;
		matrizR1[Tacna][Asuncion] = 0;
		matrizR1[Tacna][Iguazu] = 0;
		matrizR1[Tacna][Brasilia] = 0;
		matrizR1[Tacna][Mendoza] = 0;
		matrizR1[Tacna][Montevideo] = 0;
		matrizR1[Tacna][Rosario] = 0;
		matrizR1[Tacna][Florianopolis] = 0;
		matrizR1[Tacna][CiudadDelEste] = 0;
		matrizR1[Tacna][Curitiba] = 0;
		matrizR1[Tacna][RioDeJaneiro] = 0;
		matrizR1[Tacna][BeloHorizonte] = 0;
		matrizR1[Tacna][PortoSeguro] = 0;
		matrizR1[Tacna][Salvador] = 0;
		matrizR1[Tacna][Recife] = 0;
		matrizR1[Tacna][Fortaleza] = 0;
		matrizR1[Tacna][Belem] = 0;
		matrizR1[Tacna][Manaos] = 0;
		matrizR1[Tacna][Leticia] = 0;
		matrizR1[Tacna][Bogota] = 0;
		matrizR1[Tacna][Medellin] = 0;
		matrizR1[Tacna][Panama] = 0;
		matrizR1[Tacna][Cartagena] = 0;
		matrizR1[Tacna][Aruba] = 0;
		matrizR1[Tacna][Carajas] = 0;
		matrizR1[Tacna][VillaHermosa] = 0;
		matrizR1[Tacna][SanJuan] = 0;
		matrizR1[Tacna][PuntaCana] = 0;
		matrizR1[Tacna][Acapulco] = 0;
		matrizR1[Tacna][Veracruz] = 0;
		matrizR1[Tacna][CiudadDeMexico] = 0;
		matrizR1[Tacna][Merida] = 0;
		matrizR1[Tacna][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[Tacna][i] = 0;
		}

		matrizR1[Tarapoto][Santiago] = 0;
		matrizR1[Tarapoto][Quito] = 0;
		matrizR1[Tarapoto][Guayaquil] = 0;
		matrizR1[Tarapoto][LaPaz] = 0;
		matrizR1[Tarapoto][BuenosAires] = 0;
		matrizR1[Tarapoto][Iquique] = 0;
		matrizR1[Tarapoto][Cordoba] = 0;
		matrizR1[Tarapoto][SantaCruz] = 0;
		matrizR1[Tarapoto][PortoAlegre] = 0;
		matrizR1[Tarapoto][Asuncion] = 0;
		matrizR1[Tarapoto][Iguazu] = 0;
		matrizR1[Tarapoto][Brasilia] = 0;
		matrizR1[Tarapoto][Mendoza] = 0;
		matrizR1[Tarapoto][Montevideo] = 0;
		matrizR1[Tarapoto][Rosario] = 0;
		matrizR1[Tarapoto][Florianopolis] = 0;
		matrizR1[Tarapoto][CiudadDelEste] = 0;
		matrizR1[Tarapoto][Curitiba] = 0;
		matrizR1[Tarapoto][RioDeJaneiro] = 0;
		matrizR1[Tarapoto][BeloHorizonte] = 0;
		matrizR1[Tarapoto][PortoSeguro] = 0;
		matrizR1[Tarapoto][Salvador] = 0;
		matrizR1[Tarapoto][Recife] = 0;
		matrizR1[Tarapoto][Fortaleza] = 0;
		matrizR1[Tarapoto][Belem] = 0;
		matrizR1[Tarapoto][Manaos] = 0;
		matrizR1[Tarapoto][Leticia] = 0;
		matrizR1[Tarapoto][Bogota] = 0;
		matrizR1[Tarapoto][Medellin] = 0;
		matrizR1[Tarapoto][Panama] = 0;
		matrizR1[Tarapoto][Cartagena] = 0;
		matrizR1[Tarapoto][Aruba] = 0;
		matrizR1[Tarapoto][Carajas] = 0;
		matrizR1[Tarapoto][VillaHermosa] = 0;
		matrizR1[Tarapoto][SanJuan] = 0;
		matrizR1[Tarapoto][PuntaCana] = 0;
		matrizR1[Tarapoto][Acapulco] = 0;
		matrizR1[Tarapoto][Veracruz] = 0;
		matrizR1[Tarapoto][CiudadDeMexico] = 0;
		matrizR1[Tarapoto][Merida] = 0;
		matrizR1[Tarapoto][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[Tarapoto][i] = 0;
		}

		matrizR1[Cajamarca][Santiago] = 0;
		matrizR1[Cajamarca][Quito] = 0;
		matrizR1[Cajamarca][Guayaquil] = 0;
		matrizR1[Cajamarca][LaPaz] = 0;
		matrizR1[Cajamarca][BuenosAires] = 0;
		matrizR1[Cajamarca][Iquique] = 0;
		matrizR1[Cajamarca][Cordoba] = 0;
		matrizR1[Cajamarca][SantaCruz] = 0;
		matrizR1[Cajamarca][PortoAlegre] = 0;
		matrizR1[Cajamarca][Asuncion] = 0;
		matrizR1[Cajamarca][Iguazu] = 0;
		matrizR1[Cajamarca][Brasilia] = 0;
		matrizR1[Cajamarca][Mendoza] = 0;
		matrizR1[Cajamarca][Montevideo] = 0;
		matrizR1[Cajamarca][Rosario] = 0;
		matrizR1[Cajamarca][Florianopolis] = 0;
		matrizR1[Cajamarca][CiudadDelEste] = 0;
		matrizR1[Cajamarca][Curitiba] = 0;
		matrizR1[Cajamarca][RioDeJaneiro] = 0;
		matrizR1[Cajamarca][BeloHorizonte] = 0;
		matrizR1[Cajamarca][PortoSeguro] = 0;
		matrizR1[Cajamarca][Salvador] = 0;
		matrizR1[Cajamarca][Recife] = 0;
		matrizR1[Cajamarca][Fortaleza] = 0;
		matrizR1[Cajamarca][Belem] = 0;
		matrizR1[Cajamarca][Manaos] = 0;
		matrizR1[Cajamarca][Leticia] = 0;
		matrizR1[Cajamarca][Bogota] = 0;
		matrizR1[Cajamarca][Medellin] = 0;
		matrizR1[Cajamarca][Panama] = 0;
		matrizR1[Cajamarca][Cartagena] = 0;
		matrizR1[Cajamarca][Aruba] = 0;
		matrizR1[Cajamarca][Carajas] = 0;
		matrizR1[Cajamarca][VillaHermosa] = 0;
		matrizR1[Cajamarca][SanJuan] = 0;
		matrizR1[Cajamarca][PuntaCana] = 0;
		matrizR1[Cajamarca][Acapulco] = 0;
		matrizR1[Cajamarca][Veracruz] = 0;
		matrizR1[Cajamarca][CiudadDeMexico] = 0;
		matrizR1[Cajamarca][Merida] = 0;
		matrizR1[Cajamarca][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[Cajamarca][i] = 0;
		}

		matrizR1[Trujillo][Santiago] = 0;
		matrizR1[Trujillo][Quito] = 0;
		matrizR1[Trujillo][Guayaquil] = 0;
		matrizR1[Trujillo][LaPaz] = 0;
		matrizR1[Trujillo][BuenosAires] = 0;
		matrizR1[Trujillo][Iquique] = 0;
		matrizR1[Trujillo][Cordoba] = 0;
		matrizR1[Trujillo][SantaCruz] = 0;
		matrizR1[Trujillo][PortoAlegre] = 0;
		matrizR1[Trujillo][Asuncion] = 0;
		matrizR1[Trujillo][Iguazu] = 0;
		matrizR1[Trujillo][Brasilia] = 0;
		matrizR1[Trujillo][Mendoza] = 0;
		matrizR1[Trujillo][Montevideo] = 0;
		matrizR1[Trujillo][Rosario] = 0;
		matrizR1[Trujillo][Florianopolis] = 0;
		matrizR1[Trujillo][CiudadDelEste] = 0;
		matrizR1[Trujillo][Curitiba] = 0;
		matrizR1[Trujillo][RioDeJaneiro] = 0;
		matrizR1[Trujillo][BeloHorizonte] = 0;
		matrizR1[Trujillo][PortoSeguro] = 0;
		matrizR1[Trujillo][Salvador] = 0;
		matrizR1[Trujillo][Recife] = 0;
		matrizR1[Trujillo][Fortaleza] = 0;
		matrizR1[Trujillo][Belem] = 0;
		matrizR1[Trujillo][Manaos] = 0;
		matrizR1[Trujillo][Leticia] = 0;
		matrizR1[Trujillo][Bogota] = 0;
		matrizR1[Trujillo][Medellin] = 0;
		matrizR1[Trujillo][Panama] = 0;
		matrizR1[Trujillo][Cartagena] = 0;
		matrizR1[Trujillo][Aruba] = 0;
		matrizR1[Trujillo][Carajas] = 0;
		matrizR1[Trujillo][VillaHermosa] = 0;
		matrizR1[Trujillo][SanJuan] = 0;
		matrizR1[Trujillo][PuntaCana] = 0;
		matrizR1[Trujillo][Acapulco] = 0;
		matrizR1[Trujillo][Veracruz] = 0;
		matrizR1[Trujillo][CiudadDeMexico] = 0;
		matrizR1[Trujillo][Merida] = 0;
		matrizR1[Trujillo][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[Trujillo][i] = 0;
		}

		matrizR1[Chiclayo][Santiago] = 0;
		matrizR1[Chiclayo][Quito] = 0;
		matrizR1[Chiclayo][Guayaquil] = 0;
		matrizR1[Chiclayo][LaPaz] = 0;
		matrizR1[Chiclayo][BuenosAires] = 0;
		matrizR1[Chiclayo][Iquique] = 0;
		matrizR1[Chiclayo][Cordoba] = 0;
		matrizR1[Chiclayo][SantaCruz] = 0;
		matrizR1[Chiclayo][PortoAlegre] = 0;
		matrizR1[Chiclayo][Asuncion] = 0;
		matrizR1[Chiclayo][Iguazu] = 0;
		matrizR1[Chiclayo][Brasilia] = 0;
		matrizR1[Chiclayo][Mendoza] = 0;
		matrizR1[Chiclayo][Montevideo] = 0;
		matrizR1[Chiclayo][Rosario] = 0;
		matrizR1[Chiclayo][Florianopolis] = 0;
		matrizR1[Chiclayo][CiudadDelEste] = 0;
		matrizR1[Chiclayo][Curitiba] = 0;
		matrizR1[Chiclayo][RioDeJaneiro] = 0;
		matrizR1[Chiclayo][BeloHorizonte] = 0;
		matrizR1[Chiclayo][PortoSeguro] = 0;
		matrizR1[Chiclayo][Salvador] = 0;
		matrizR1[Chiclayo][Recife] = 0;
		matrizR1[Chiclayo][Fortaleza] = 0;
		matrizR1[Chiclayo][Belem] = 0;
		matrizR1[Chiclayo][Manaos] = 0;
		matrizR1[Chiclayo][Leticia] = 0;
		matrizR1[Chiclayo][Bogota] = 0;
		matrizR1[Chiclayo][Medellin] = 0;
		matrizR1[Chiclayo][Panama] = 0;
		matrizR1[Chiclayo][Cartagena] = 0;
		matrizR1[Chiclayo][Aruba] = 0;
		matrizR1[Chiclayo][Carajas] = 0;
		matrizR1[Chiclayo][VillaHermosa] = 0;
		matrizR1[Chiclayo][SanJuan] = 0;
		matrizR1[Chiclayo][PuntaCana] = 0;
		matrizR1[Chiclayo][Acapulco] = 0;
		matrizR1[Chiclayo][Veracruz] = 0;
		matrizR1[Chiclayo][CiudadDeMexico] = 0;
		matrizR1[Chiclayo][Merida] = 0;
		matrizR1[Chiclayo][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[Chiclayo][i] = 0;
		}

		matrizR1[Iquitos][Santiago] = 0;
		matrizR1[Iquitos][Quito] = 0;
		matrizR1[Iquitos][Guayaquil] = 0;
		matrizR1[Iquitos][LaPaz] = 0;
		matrizR1[Iquitos][BuenosAires] = 0;
		matrizR1[Iquitos][Iquique] = 0;
		matrizR1[Iquitos][Cordoba] = 0;
		matrizR1[Iquitos][SantaCruz] = 0;
		matrizR1[Iquitos][PortoAlegre] = 0;
		matrizR1[Iquitos][Asuncion] = 0;
		matrizR1[Iquitos][Iguazu] = 0;
		matrizR1[Iquitos][Brasilia] = 0;
		matrizR1[Iquitos][Mendoza] = 0;
		matrizR1[Iquitos][Montevideo] = 0;
		matrizR1[Iquitos][Rosario] = 0;
		matrizR1[Iquitos][Florianopolis] = 0;
		matrizR1[Iquitos][CiudadDelEste] = 0;
		matrizR1[Iquitos][Curitiba] = 0;
		matrizR1[Iquitos][RioDeJaneiro] = 0;
		matrizR1[Iquitos][BeloHorizonte] = 0;
		matrizR1[Iquitos][PortoSeguro] = 0;
		matrizR1[Iquitos][Salvador] = 0;
		matrizR1[Iquitos][Recife] = 0;
		matrizR1[Iquitos][Fortaleza] = 0;
		matrizR1[Iquitos][Belem] = 0;
		matrizR1[Iquitos][Manaos] = 0;
		matrizR1[Iquitos][Leticia] = 0;
		matrizR1[Iquitos][Bogota] = 0;
		matrizR1[Iquitos][Medellin] = 0;
		matrizR1[Iquitos][Panama] = 0;
		matrizR1[Iquitos][Cartagena] = 0;
		matrizR1[Iquitos][Aruba] = 0;
		matrizR1[Iquitos][Carajas] = 0;
		matrizR1[Iquitos][VillaHermosa] = 0;
		matrizR1[Iquitos][SanJuan] = 0;
		matrizR1[Iquitos][PuntaCana] = 0;
		matrizR1[Iquitos][Acapulco] = 0;
		matrizR1[Iquitos][Veracruz] = 0;
		matrizR1[Iquitos][CiudadDeMexico] = 0;
		matrizR1[Iquitos][Merida] = 0;
		matrizR1[Iquitos][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[Iquitos][i] = 0;
		}

		matrizR1[Piura][Santiago] = 0;
		matrizR1[Piura][Quito] = 0;
		matrizR1[Piura][Guayaquil] = 0;
		matrizR1[Piura][LaPaz] = 0;
		matrizR1[Piura][BuenosAires] = 0;
		matrizR1[Piura][Iquique] = 0;
		matrizR1[Piura][Cordoba] = 0;
		matrizR1[Piura][SantaCruz] = 0;
		matrizR1[Piura][PortoAlegre] = 0;
		matrizR1[Piura][Asuncion] = 0;
		matrizR1[Piura][Iguazu] = 0;
		matrizR1[Piura][Brasilia] = 0;
		matrizR1[Piura][Mendoza] = 0;
		matrizR1[Piura][Montevideo] = 0;
		matrizR1[Piura][Rosario] = 0;
		matrizR1[Piura][Florianopolis] = 0;
		matrizR1[Piura][CiudadDelEste] = 0;
		matrizR1[Piura][Curitiba] = 0;
		matrizR1[Piura][RioDeJaneiro] = 0;
		matrizR1[Piura][BeloHorizonte] = 0;
		matrizR1[Piura][PortoSeguro] = 0;
		matrizR1[Piura][Salvador] = 0;
		matrizR1[Piura][Recife] = 0;
		matrizR1[Piura][Fortaleza] = 0;
		matrizR1[Piura][Belem] = 0;
		matrizR1[Piura][Manaos] = 0;
		matrizR1[Piura][Leticia] = 0;
		matrizR1[Piura][Bogota] = 0;
		matrizR1[Piura][Medellin] = 0;
		matrizR1[Piura][Panama] = 0;
		matrizR1[Piura][Cartagena] = 0;
		matrizR1[Piura][Aruba] = 0;
		matrizR1[Piura][Carajas] = 0;
		matrizR1[Piura][VillaHermosa] = 0;
		matrizR1[Piura][SanJuan] = 0;
		matrizR1[Piura][PuntaCana] = 0;
		matrizR1[Piura][Acapulco] = 0;
		matrizR1[Piura][Veracruz] = 0;
		matrizR1[Piura][CiudadDeMexico] = 0;
		matrizR1[Piura][Merida] = 0;
		matrizR1[Piura][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[Piura][i] = 0;
		}

		matrizR1[Talara][Santiago] = 0;
		matrizR1[Talara][Quito] = 0;
		matrizR1[Talara][Guayaquil] = 0;
		matrizR1[Talara][LaPaz] = 0;
		matrizR1[Talara][BuenosAires] = 0;
		matrizR1[Talara][Iquique] = 0;
		matrizR1[Talara][Cordoba] = 0;
		matrizR1[Talara][SantaCruz] = 0;
		matrizR1[Talara][PortoAlegre] = 0;
		matrizR1[Talara][Asuncion] = 0;
		matrizR1[Talara][Iguazu] = 0;
		matrizR1[Talara][Brasilia] = 0;
		matrizR1[Talara][Mendoza] = 0;
		matrizR1[Talara][Montevideo] = 0;
		matrizR1[Talara][Rosario] = 0;
		matrizR1[Talara][Florianopolis] = 0;
		matrizR1[Talara][CiudadDelEste] = 0;
		matrizR1[Talara][Curitiba] = 0;
		matrizR1[Talara][RioDeJaneiro] = 0;
		matrizR1[Talara][BeloHorizonte] = 0;
		matrizR1[Talara][PortoSeguro] = 0;
		matrizR1[Talara][Salvador] = 0;
		matrizR1[Talara][Recife] = 0;
		matrizR1[Talara][Fortaleza] = 0;
		matrizR1[Talara][Belem] = 0;
		matrizR1[Talara][Manaos] = 0;
		matrizR1[Talara][Leticia] = 0;
		matrizR1[Talara][Bogota] = 0;
		matrizR1[Talara][Medellin] = 0;
		matrizR1[Talara][Panama] = 0;
		matrizR1[Talara][Cartagena] = 0;
		matrizR1[Talara][Aruba] = 0;
		matrizR1[Talara][Carajas] = 0;
		matrizR1[Talara][VillaHermosa] = 0;
		matrizR1[Talara][SanJuan] = 0;
		matrizR1[Talara][PuntaCana] = 0;
		matrizR1[Talara][Acapulco] = 0;
		matrizR1[Talara][Veracruz] = 0;
		matrizR1[Talara][CiudadDeMexico] = 0;
		matrizR1[Talara][Merida] = 0;
		matrizR1[Talara][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[Talara][i] = 0;
		}

		matrizR1[Tumbes][Santiago] = 0;
		matrizR1[Tumbes][Quito] = 0;
		matrizR1[Tumbes][Guayaquil] = 0;
		matrizR1[Tumbes][LaPaz] = 0;
		matrizR1[Tumbes][BuenosAires] = 0;
		matrizR1[Tumbes][Iquique] = 0;
		matrizR1[Tumbes][Cordoba] = 0;
		matrizR1[Tumbes][SantaCruz] = 0;
		matrizR1[Tumbes][PortoAlegre] = 0;
		matrizR1[Tumbes][Asuncion] = 0;
		matrizR1[Tumbes][Iguazu] = 0;
		matrizR1[Tumbes][Brasilia] = 0;
		matrizR1[Tumbes][Mendoza] = 0;
		matrizR1[Tumbes][Montevideo] = 0;
		matrizR1[Tumbes][Rosario] = 0;
		matrizR1[Tumbes][Florianopolis] = 0;
		matrizR1[Tumbes][CiudadDelEste] = 0;
		matrizR1[Tumbes][Curitiba] = 0;
		matrizR1[Tumbes][RioDeJaneiro] = 0;
		matrizR1[Tumbes][BeloHorizonte] = 0;
		matrizR1[Tumbes][PortoSeguro] = 0;
		matrizR1[Tumbes][Salvador] = 0;
		matrizR1[Tumbes][Recife] = 0;
		matrizR1[Tumbes][Fortaleza] = 0;
		matrizR1[Tumbes][Belem] = 0;
		matrizR1[Tumbes][Manaos] = 0;
		matrizR1[Tumbes][Leticia] = 0;
		matrizR1[Tumbes][Bogota] = 0;
		matrizR1[Tumbes][Medellin] = 0;
		matrizR1[Tumbes][Panama] = 0;
		matrizR1[Tumbes][Cartagena] = 0;
		matrizR1[Tumbes][Aruba] = 0;
		matrizR1[Tumbes][Carajas] = 0;
		matrizR1[Tumbes][VillaHermosa] = 0;
		matrizR1[Tumbes][SanJuan] = 0;
		matrizR1[Tumbes][PuntaCana] = 0;
		matrizR1[Tumbes][Acapulco] = 0;
		matrizR1[Tumbes][Veracruz] = 0;
		matrizR1[Tumbes][CiudadDeMexico] = 0;
		matrizR1[Tumbes][Merida] = 0;
		matrizR1[Tumbes][Cancun] = 0;
		for (int i = 44; i < 102; i++){
			matrizR1[Tumbes][i] = 0;
		}

		//Hallamos la matriz R2, R3 y Matriz de Caminos:
		M_Matricez(matrizR1,matrizR1,matrizR2);
		M_Matricez(matrizR2, matrizR1, matrizR3);
		CopiarMatriz(matrizR1,matriz_caminos);
		HallarMatrizCaminos(matriz_caminos); 
		SumarMatricez(matriz_caminos,matrizR1,matriz_caminos);
		SumarMatricez(matriz_caminos, matrizR2, matriz_caminos);
	}
	~DatosM(){}
	void RellenarVacios(int mat[a][b], int valor){
		for (int i = 0; i < a; i++){
			for (int j = 0; j < b; j++){
				if (i != j) //Restringimos propiedad reflexiva:
					mat[i][j] = valor;
				else
					mat[i][j] = 0;
			}
		}
	}
	string* Separar(string Total){
			string* devolver = new string[2];
			bool seguir1 = true;
			bool seguir2 = false;
	
			string aux1 = "                                      ";
			string aux2 = "                                      ";

			int cont = 0;
			for (int i = 0; i < Total.size(); i++){
				if (Total[i] == ',') { seguir1 = false; seguir2 = true; }
				if (seguir1){ aux1[i] = Total[i]; }
				if (seguir2){ aux2[cont] = Total[i + 1]; cont++; }
			}
			char* Cadena1 = new char[50];
			char* Cadena2 = new char[50];
			strcpy(Cadena1, aux1.c_str());
			strcpy(Cadena2, aux2.c_str());
			string var1 = string(Cadena1);
			string var2 = string(Cadena2);
			devolver[0] = var1;
			devolver[1] = var2;
			return devolver;
	}
	string GetCiudad(int x){ return Ciudades[x];}
	int GetTamaño(){return a;}
	string GetVectores(int x,int y){ return Vectores[x][y]; }
	string* MostrarTrayectorias(string Ciudad,string Destino){
		string* Resultado = new string[3];
		string* d = new string[2];
		//Analizamos la matriz de directos:
		for (int i = 0; i < a; i++){
			for (int j = 0; j < b; j++){
				if (Separar(Ciudades[i])[0] == Ciudad && Separar(Ciudades[j])[0]==Destino){
					if (matrizR1[i][j] == 1 && Ciudad!=Destino){
						Resultado[0] = "Viaje Directo de " + Ciudades[i] + " hacia " + Ciudades[j];
						break;
					}
					else
					{
						Resultado[0] = "No existe viaje directo hacia esta ciudad";
						break;
					}
				}
			}
		}

		//Analizamos la matriz de 1 escala:
		for (int i = 0; i < a;i++){
			for (int j = 0; j < b;j++){
				if (Separar(Ciudades[i])[0] == Ciudad && Separar(Ciudades[j])[0] == Destino){
					d = Separar(Vectores[i][j]);
					if (matrizR2[i][j] == 1 && Ciudad != Destino && d[0] != "null                                  "){
						Resultado[1] = "Viaje con 1 escala de " + Ciudades[i] + " hacia " + Ciudades[j] + " a traves de " + d[0];
						break;
					}
					else
					{
						Resultado[1] = "No existe viaje de 1 escala hacia esta ciudad";
						break;
					}
				}
			}
		}
		//Analizamos la matriz de 2 escala:
		for (int i = 0; i < a; i++){
			for (int j = 0; j < b; j++){
				if (Separar(Ciudades[i])[0] == Ciudad && Separar(Ciudades[j])[0] == Destino){
					d = Separar(Vectores[i][j]);
					if (matrizR3[i][j] == 1 && Ciudad != Destino){	
						string aux = "                                  ";
						int indivalor = 0;
						for (int m = 0; m < d[1].size(); m++){
							if (d[1][m] != ' '){ aux[indivalor] = d[1][m]; indivalor++; }
						}
						if (aux != "null                              "){
							Resultado[2] = "Viaje con 2 escalas de " + Ciudades[i] + " hacia " + Ciudades[j] + " a traves de " + d[1];
							break;
						}
						else
						{
							Resultado[2] = "No existe viaje de 2 escalas hacia esta ciudad";
							break;
						}
					}
					else
					{
						Resultado[2] = "No existe viaje de 2 escalas hacia esta ciudad";
						break;
					}
				}
			}
		}
		return Resultado;
	}
	string MostrarConexion(string Ciudad,string Destino,int matAnalizada[a][b]){
		string Resultado = "null";
		for (int i = 0; i < a; i++){
			for (int j = 0; j < b; j++){
				if (Separar(Ciudades[i])[0] == Ciudad && Separar(Ciudades[j])[0] == Destino && Ciudad!=Destino){			
					Resultado = "Si existe conexion de " + Ciudades[i] + " hacia " + Ciudades[j] + " para algun valor mayor a dos escalas";		
					break;
				}
			}
		}
		return Resultado;
	}
};

